name: Delete runner VM
description: Delete runner VM using manage-vm.py
inputs:
  repo_owner:
    required: true
    description: "repo owner"
  repo:
    required: true
    description: "repo name"
  service_account_key:
    required: true
    description: "service account key"
  token:
    required: true
    description: "GITHUB_TOKEN"
  vm_parent_id:
    required: true
    description: "vm parent id"
  vm_id:
    required: true
    description: "vm id"

runs:
  using: composite
  steps:
    - name: write service account key to file
      shell: bash
      run: |
        export SERVICE_ACCOUNT_KEY=$(mktemp)
        echo "SERVICE_ACCOUNT_KEY=${SERVICE_ACCOUNT_KEY}" >> $GITHUB_ENV
        echo "${KEY_CONTENTS}" > $SERVICE_ACCOUNT_KEY
      env:
        KEY_CONTENTS: ${{ inputs.service_account_key }}
    - name: install dependencies
      shell: bash
      run: |
        pip install -r .github/scripts/requirements.txt
    - name: remove vm
      id: remove-vm
      shell: bash
      run: |
        python .github/scripts/nebius-manage-vm.py remove \
          --github-repo-owner "${REPO_OWNER}" \
          --github-repo "${REPO}" \
          --service-account-key "${SERVICE_ACCOUNT_KEY}" \
          --parent-id "${PARENT_ID}" \
          --id "${VM_ID}" \
          --apply
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        REPO_OWNER: ${{ inputs.repo_owner }}
        REPO: ${{ inputs.repo }}
        VM_ID: ${{ inputs.vm_id }}
        PARENT_ID: ${{ inputs.vm_parent_id }}
