name: Delete runner VM
description: Delete runner VM using manage-vm.py
inputs:
  repo_owner:
    required: true
    description: "repo owner"
  repo:
    required: true
    description: "repo name"
  nebius_config_yaml:
    required: false
    description: "Nebius CLI config.yaml content for SDK authentication"
  token:
    required: true
    description: "GITHUB_TOKEN"
  vm_parent_id:
    required: true
    description: "vm parent id"
  vm_id:
    required: true
    description: "vm id"

runs:
  using: composite
  steps:
    - name: set up nebius cli
      id: nebius-cli
      uses: ./.github/actions/nebius_cli
      with:
        config_yaml: ${{ inputs.nebius_config_yaml }}
    - name: install dependencies
      shell: bash
      run: |
        pip install -r .github/scripts/requirements.txt
    - name: remove vm
      id: remove-vm
      shell: bash
      run: |
        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/.github
        python3 -m scripts.nebius_manage_vm remove \
          --github-repo-owner "${REPO_OWNER}" \
          --github-repo "${REPO}" \
          --parent-id "${PARENT_ID}" \
          --id "${VM_ID}" \
          --apply
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        NEBIUS_IAM_TOKEN: ${{ steps.nebius-cli.outputs.NEBIUS_IAM_TOKEN }}
        REPO_OWNER: ${{ inputs.repo_owner }}
        REPO: ${{ inputs.repo }}
        VM_ID: ${{ inputs.vm_id }}
        PARENT_ID: ${{ inputs.vm_parent_id }}
