GO_LIBRARY()
IF (TRUE)
    SRCS(
        attr.go
        attr_string.go
        content.go
        context.go
        css.go
        delim_string.go
        doc.go
        element_string.go
        error.go
        escape.go
        html.go
        jsctx_string.go
        js.go
        state_string.go
        template.go
        testdata
        transition.go
        url.go
        urlpart_string.go
    )
ENDIF()
END()
