name: Prepare GH cli tool
description: Install GH cli

runs:
  using: composite
  steps:
    - name: Set up GH CLI
      shell: bash
      run: |
        set -x
        if [ ! -f "/usr/bin/gh" ];
        then
          sudo mkdir -p -m 755 /etc/apt/keyrings 
          sudo wget -nv -O/etc/apt/keyrings/githubcli-archive-keyring.gpg https://cli.github.com/packages/githubcli-archive-keyring.gpg 
          sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg 
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null 
          sudo apt-get -o Dpkg::Lock::Timeout=600 update
          sudo apt-get -o Dpkg::Lock::Timeout=600 install gh -y
        else
          echo "GH CLI already installed"
        fi
