#!/bin/sh

# Check unwanted trailing whitespace or space/tab indents;
git diff --check --cached

if [ $? -ne 0 ]; then
    echo
    echo Pre-commit checks failed! Check trailing spaces listed above!
    exit 1
fi
