RECURSE_FOR_TESTS(
    max-file-count-test
    service-kikimr-auth-test
    service-kikimr-datashard-like-test
    service-kikimr-emergency-test
    service-kikimr-memshard-test
    service-kikimr-nemesis-test
    service-kikimr-test
    service-kikimr-newfeatures-test
    service-local-test
)
