RECURSE_FOR_TESTS(
    service-kikimr-auth-test
    service-kikimr-emergency-test
    service-kikimr-nemesis-test
    service-kikimr-test
    service-kikimr-newfeatures-test
    service-kikimr-localdb-compaction-test
    service-local-test
)
