PACKAGE()

# image generated by ../build-image

IF(ARCH_X86_64)
    # build-image --arch amd64 --release resolute --out rootfs.resolute.amd64.uncompressed.img --plain-pwd --ssh-key ../keys/id_rsa --repo-mirror http://archive.ubuntu.com/ubuntu --cloud-images-mirror https://cloud-images.ubuntu.com
    # qemu-img convert -c -p -f qcow2 -O qcow2 rootfs.resolute.amd64.uncompressed.img rootfs.resolute.amd64.img
    FROM_SANDBOX(
        FILE
        1234444001
        RENAME RESOURCE
        OUT_NOAUTO rootfs.img
    )
ELSEIF (ARCH_ARM64)
    # build-image --arch arm64 --release resolute --out rootfs.resolute.arm64.uncompressed.img --plain-pwd --ssh-key ../keys/id_rsa --repo-mirror http://archive.ubuntu.com/ubuntu --cloud-images-mirror https://cloud-images.ubuntu.com
    # qemu-img convert -c -p -f qcow2 -O qcow2 rootfs.resolute.arm64.uncompressed.img rootfs.resolute.arm64.img
    FROM_SANDBOX(
        FILE
        1234444002
        RENAME RESOURCE
        OUT_NOAUTO rootfs.img
    )
ELSE()
    MESSAGE(FATAL_ERROR "Unsupported platform")
ENDIF()

END()
