---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: nbs-csi-controller
value: 900000000
globalDefault: false
description: "This priority class should be used for core kubevirt components only."

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: nbs-csi-node
value: 900001000
globalDefault: false
description: "This priority class should be used for core kubevirt components only."
