---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nbs-server-config-node
  namespace: nbs
data:
  nbs-server.txt: |-
    ServerConfig {
      Host: "localhost"
      Port: 9766
      DataHost: "localhost"
      DataPort: 9767
      StrictContractValidation: true
      UnixSocketPath: "/run/nbsd/grpc.sock"
      ThreadsCount: 4
      VhostEnabled: true
      VhostThreadsCount: 4
      NodeType: "nbs"
      EndpointStorageType: ENDPOINT_STORAGE_FILE
      EndpointStorageDir: "/Berkanavt/nbs-server/endpoints"
      NbdEnabled: true
      NbdThreadsCount: 4
      GrpcKeepAliveTime: 10000
      GrpcKeepAliveTimeout: 1000
      GrpcKeepAlivePermitWithoutCalls: true
      GrpcHttp2MinRecvPingIntervalWithoutData: 1000
      NbdDevicePrefix: "/mnt/dev/nbd"
    }
    LocalServiceConfig {
      DataDir: "/Berkanavt/nbs-server/data"
    }



  nbs_server.cfg: |-
    nbs_home="${nbs_home:-"/Berkanavt/nbs-server"}"
    nbs_config="${nbs_home}/cfg"
    nbs_server_file="${nbs_config}/nbs-server.txt"

    nbs_arg="${nbs_arg}${nbs_server_file:+ --server-file ${nbs_server_file}}"

    nbs_arg="${nbs_arg} --service=local"
    nbs_arg="${nbs_arg} --mon-port=8766"
    nbs_arg="${nbs_arg} --verbose"
