name: Prepare nebius cli tool to display various parameters
description: Install nebius cli and display vm IP
inputs:
  instance_id:
    required: false
    description: "runner instance-id"
  sa_json:
    required: true
    description: ""
outputs:
  runner_ipv4:
    value: ${{ steps.result.outputs.runner_ipv4 }}
    description: "runner ipv4"

runs:
  using: composite
  steps:
    - name: set up home
      shell: bash
      run: echo "HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: set up path
      shell: bash
      run: echo "PATH=$PATH:$HOME/.nebius/bin" >> $GITHUB_ENV

    - name: Set up Nebius CLI
      shell: bash
      env:
        SA_JSON: ${{ inputs.sa_json }}
      run: |
        set -x
        if [ ! -f "$HOME/.nebius/bin/nebius" ];
        then 
          curl -sSL https://storage.eu-north1.nebius.cloud/cli/install.sh | bash
          cat <<EOF > sa.json
        ${SA_JSON}
        EOF
        else
          echo "Nebius CLI already installed"
        fi
        if [ ! -f "$HOME/.nebius/config.yaml" ];
        then
          jq -r '."subject-credentials"."private-key"'  sa.json > private.pem
          echo "::add-mask::$(jq -r '."subject-credentials"."kid"' sa.json)"
          public_key_id=$(jq -r '."subject-credentials"."kid"' sa.json)
          echo "::add-mask::$(jq -r '."subject-credentials"."iss"' sa.json)"
          service_account_id=$(jq -r '."subject-credentials"."iss"' sa.json)
          echo "::add-mask::tenant-e00en3r863f7me6wtd"
          
          nebius profile create --endpoint api.eu-north1.nebius.cloud \
                                --profile nbs-github-user-sa \
                                --parent-id tenant-e00en3r863f7me6wtd \
                                --public-key-id "${public_key_id}" \
                                --private-key-file private.pem \
                                --service-account-id "${service_account_id}" 
          else
            echo "Nebius profile already created"
          fi

    - id: result
      name: print ipv4 address of the vm
      shell: bash
      env:
        INSTANCE_ID: ${{ inputs.instance_id }}
      run: |
        export GITHUB_RUNNER_IPV4=$(nebius compute instance get "${INSTANCE_ID}" --format json | jq -r .network_interfaces[].primary_v4_address.one_to_one_nat.address)
        export GITHUB_RUNNER_IPV4=$(nebius compute instance get --id "${INSTANCE_ID}" --format json | jq -r '.status.network_interfaces[0].public_ip_address.address')
        echo "GITHUB_RUNNER_IPV4=${GITHUB_RUNNER_IPV4}" | tee -a $GITHUB_ENV
        echo "runner_ipv4=${GITHUB_RUNNER_IPV4}" >> $GITHUB_OUTPUT
        echo "ssh github@${GITHUB_RUNNER_IPV4}" | tee -a $GITHUB_SUMMARY
