name: Run tests with cmake
description: Run tests using cmake infrastructure

runs:
  using: composite
  steps:
    - name: prepare
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: |
        {
          echo "SHELLOPTS=$SHELLOPTS:xtrace"
          echo "ARTIFACTS_DIR=${TMP_DIR}/artifacts"
          echo "SUMMARY_DIR=${ARTIFACTS_DIR}/summary"
          echo "SUMMARY_LINKS=$(mktemp)"
        } >> $GITHUB_ENV

    - name: create dirs
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: |
        mkdir -p "$ARTIFACTS_DIR" "$SUMMARY_DIR"
    - name: ctest
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: |
        cd $TMP_DIR

        ctest -j 60 --output-junit $ARTIFACTS_DIR/junit.xml -O "$TMP_DIR/ctest.log"  || (
          ctest -j 60 --rerun-failed --output-on-failure --output-junit $ARTIFACTS_DIR/junit_rerun.xml -O "$TMP_DIR/ctest_rerun.log"
        )

    - name: Generate summary
      if: always()
      shell: bash --noprofile --norc -eo pipefail -x {0}
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        if [ -f "${ARTIFACTS_DIR}/junit.xml" ]; then
          if [ -f "${ARTIFACTS_DIR}/junit_rerun.xml" ]; then
            .github/scripts/tests/generate-summary.py \
              --summary-out-path "${SUMMARY_DIR}" \
              --summary-url-prefix "${S3_URL_PREFIX}/summary/" \
              "CTest" ctest.html "${ARTIFACTS_DIR}/junit.xml" \
              "CTest Rerun" ctest_rerun.html "${ARTIFACTS_DIR}/junit_rerun.xml"
          else
            .github/scripts/tests/generate-summary.py \
              --summary-out-path "${SUMMARY_DIR}" \
              --summary-url-prefix "${S3_URL_PREFIX}/summary/" \
              "CTest" ctest.html "${ARTIFACTS_DIR}/junit.xml"
          fi
        fi

    - name: Sync logs to S3
      if: always()
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: |
        echo "::group::s3-sync"
        [ -f "${TMP_DIR}/ctest.log" ] && {
          s3cmd sync --acl-private --no-progress --stats --no-check-md5 "${TMP_DIR}/ctest.log" "$S3_BUCKET_PATH/build_logs/"
          echo "[ctest.log](${S3_WEBSITE_PREFIX}/build_logs/ctest.log)" | tee -a $GITHUB_STEP_SUMMARY
        }
        [ -f "${TMP_DIR}/ctest_rerun.log" ] && {
          s3cmd sync --acl-private --no-progress --stats --no-check-md5 "${TMP_DIR}/ctest_rerun.log" "$S3_BUCKET_PATH/build_logs/"
          echo "[ctest_rerun.log](${S3_WEBSITE_PREFIX}/build_logs/ctest_rerun.log)" | tee -a $GITHUB_STEP_SUMMARY
        }
        [ -f "${ARTIFACTS_DIR}/junit.xml" ] && {
          s3cmd sync --acl-private --no-progress --stats --no-check-md5 "$ARTIFACTS_DIR/junit.xml" "$S3_BUCKET_PATH/artifacts/"
          echo "[junit.xml](${S3_WEBSITE_PREFIX}/artifacts/junit.xml)" | tee -a $GITHUB_STEP_SUMMARY
        }
        [ -f "${ARTIFACTS_DIR}/junit_rerun.xml" ] && {
          s3cmd sync --acl-private --no-progress --stats --no-check-md5 "$ARTIFACTS_DIR/junit_rerun.xml" "$S3_BUCKET_PATH/artifacts/"
          echo "[junit_rerun.xml](${S3_WEBSITE_PREFIX}/artifacts/junit_rerun.xml)" | tee -a $GITHUB_STEP_SUMMARY
        }
        [ -f "${SUMMARY_DIR}/ctest.html" ] && {
          s3cmd sync --acl-private --no-progress --stats --no-check-md5 "${SUMMARY_DIR}/ctest.html" "$S3_BUCKET_PATH/summary/"
          echo "[ctest.html](${S3_WEBSITE_PREFIX}/summary/ctest.html)" | tee -a $GITHUB_STEP_SUMMARY
        }
        [ -f "${SUMMARY_DIR}/ctest_rerun.html" ] && {
          s3cmd sync --acl-private --no-progress --stats --no-check-md5 "${SUMMARY_DIR}/ctest_rerun.html" "$S3_BUCKET_PATH/summary/"
          echo "[ctest_rerun.html](${S3_WEBSITE_PREFIX}/summary/ctest_rerun.html)" | tee -a $GITHUB_STEP_SUMMARY
        }
        echo "::endgroup::"

    - name: Create directory listing on s3
      if: always()
      shell: bash
      run: |
        echo "::group::generate-listing"
        python3 .github/scripts/index.py "$S3_BUCKET_PATH" --generate-indexes --apply
        echo "::endgroup::"

    - name: show free space
      if: always()
      shell: bash
      run: df -h
