name: Run tests with cmake
description: Run tests using cmake infrastructure
runs:
  using: composite
  steps:
    - name: ctest
      shell: bash
      run: |
        cd $TMP_DIR
        ctest | tee -a "$TMP_DIR/ctest.log"

    - name: Sync logs to S3
      if: always()
      shell: bash
      run: |
        echo "::group::s3-sync"
        [ -f "$TMP_DIR/ctest.log" ] && {
          s3cmd sync --acl-private --no-progress --stats --no-check-md5 "$TMP_DIR/ctest.log" "$S3_BUCKET_PATH/build_logs/"
          echo ${S3_WEBSITE_PREFIX}/build_logs/ctest.log
        }
        echo "::endgroup::"

    - name: show free space
      if: always()
      shell: bash
      run: df -h
