syntax = "proto3";

package pools;

import "cloud/disk_manager/internal/pkg/services/pools/protos/configure_pool_task.proto";

option go_package = "github.com/ydb-platform/nbs/cloud/disk_manager/internal/pkg/services/pools/protos";

////////////////////////////////////////////////////////////////////////////////

message OptimizeBaseDisksTaskState {
    repeated ConfigurePoolRequest ConfigurePoolForImageSizeRequests = 1;
    repeated ConfigurePoolRequest PoolReductionRequests = 2;
    repeated string IdleBaseDiskIds = 3;
    bool CollectedResourcesToOptimize = 4;
}
