# Generated by devtools/yamaker.

LIBRARY()

LICENSE(BSD-3-Clause)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

PEERDIR(
    contrib/libs/spdk/lib/json
    contrib/libs/spdk/lib/jsonrpc
    contrib/libs/spdk/lib/log
    contrib/libs/spdk/lib/rpc
)

ADDINCL(contrib/libs/spdk/include)

NO_COMPILER_WARNINGS()

NO_RUNTIME()

SRCS(
    GLOBAL sock.c
    GLOBAL sock_rpc.c
)

END()
