LIBRARY()

SRCS(
    appdata.cpp
    cache_policy.cpp
    core_ydb.cpp
    core_ydbc.cpp
    cracked_page.cpp
    filter.cpp
    mapper.cpp
    merger.cpp
    mvp_mem_profiler.cpp
    mvp_security_printer.cpp
    mvp_startup_options.cpp
    mvp_startup_options_validation.cpp
    mvp_startup_options_migration.cpp
    mvp_test_runtime.cpp
    mvp_token_exchange.cpp
    mvp_tokens.cpp
    parser.cpp
    reducer.cpp
    utils.cpp
)

PEERDIR(
    contrib/libs/googleapis-common-protos
    contrib/libs/jwt-cpp
    contrib/libs/yaml-cpp
    library/cpp/lfalloc/alloc_profiler
    library/cpp/lwtrace/protos
    library/cpp/protobuf/json
    library/cpp/string_utils/url
    contrib/ydb/core/protos
    contrib/ydb/core/util
    contrib/ydb/core/viewer/json
    contrib/ydb/library/actors/core
    contrib/ydb/library/actors/http
    contrib/ydb/library/actors/protos
    contrib/ydb/library/protobuf_printer
    contrib/ydb/library/security
    contrib/ydb/library/yaml_json
    contrib/ydb/mvp/core/protos
    contrib/ydb/mvp/security/simple
    contrib/ydb/public/api/grpc
    contrib/ydb/public/api/protos
    contrib/ydb/public/api/client/nc_private
    contrib/ydb/public/api/client/nc_private/iam/v1
    contrib/ydb/public/api/client/yc_private/accessservice
    contrib/ydb/public/api/client/yc_private/iam
    contrib/ydb/public/api/client/yc_private/resourcemanager
    contrib/ydb/public/api/client/yc_private/ydb/v1
    contrib/ydb/public/sdk/cpp/src/client/datastreams
    contrib/ydb/public/sdk/cpp/src/client/draft
    contrib/ydb/public/sdk/cpp/src/client/persqueue_public
    contrib/ydb/public/sdk/cpp/src/client/scheme
    contrib/ydb/public/sdk/cpp/src/client/table
    contrib/ydb/public/sdk/cpp/src/client/topic
    contrib/ydb/public/sdk/cpp/src/library/operation_id
)

END()

RECURSE_FOR_TESTS(
    ut
)
