name: Checkout helper
description: Checkout helper
inputs:
  ref:
    required: true
    description: "Ref to build"
    default: "main"
  sparse:
    required: true
    description: ""
    default: ""
outputs:
  runner_ipv4:
    value: ${{ steps.result.outputs.runner_ipv4 }}
    description: "runner ipv4"

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      if: github.event.pull_request.head.sha == ''
      with:
        submodules: true
        ref: ${{ inputs.ref }}
        sparse-checkout: ${{ inputs.sparse || '' }}
    - name: Checkout PR
      uses: actions/checkout@v4
      if: github.event.pull_request.head.sha != ''
      with:
        submodules: true
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: ${{ !contains(github.event.pull_request.labels.*.name, 'rebase') && 1 || 0 }}
        sparse-checkout: ${{ inputs.sparse || '' }}
    - name: Rebase PR
      if: ${{ github.event.pull_request.head.sha != '' && contains(github.event.pull_request.labels.*.name, 'rebase') }}
      shell: bash
      run: |
        git config user.email "robot-nbs@nebius.com"
        git config user.name "Rebase Robotovich"
        git fetch origin ${{ github.event.pull_request.base.ref }}
        git rebase origin/${{ github.event.pull_request.base.ref }}
