RECURSE(
    python
    recipes
)

RECURSE_FOR_TESTS(
    auth
    build_arcadia_test
    client
    client_sharded
    client_sharded_dir
    client_sharded_dir_resize
    close_to_open_consistency
    config_dispatcher
    endpoints
    fio
    fio_index
    fio_index_migration
    fio_migration
    fs_posix_compliance
    guest_cache
    loadtest
    profile_log
    registration
    service
    xfs_suite
)
