name: Prepare ncp tool to display various parameters
description: Install ncp and display vm IP
inputs:
  instance_id:
    required: false
    description: "runner instance-id"
  sa_json:
    required: true
    description: ""
outputs:
  runner_ipv4:
    value: ${{ steps.result.outputs.runner_ipv4 }}
    description: "runner ipv4"

runs:
  using: composite
  steps:
    - name: env
      shell: bash
      run: |
        echo "PATH=$PATH:/root/nebius-cloud/bin" >> $GITHUB_ENV
        echo "HOME=/root" >> $GITHUB_ENV
    - name: install ncp
      shell: bash
      run: |
        curl -sSL https://storage.ai.nebius.cloud/ncp/install.sh | bash
    - name: configure ncp
      shell: bash
      run: |
        cat <<EOF > sa.json
        ${{ inputs.sa_json }}
        EOF

        ncp config profile create nbs-github-user-sa
        ncp config set service-account-key sa.json
        ncp config set endpoint api.ai.nebius.cloud:443

    - id: result
      name: print ipv4 address of the vm
      shell: bash
      run: |
        export GITHUB_RUNNER_IPV4=$(ncp compute instance get ${{ inputs.instance_id }} --format json | jq -r .network_interfaces[].primary_v4_address.one_to_one_nat.address)
        echo "GITHUB_RUNNER_IPV4=${GITHUB_RUNNER_IPV4}" >> $GITHUB_ENV
        echo "runner_ipv4=${GITHUB_RUNNER_IPV4}" >> $GITHUB_OUTPUT
        echo "ssh github@${GITHUB_RUNNER_IPV4}" | tee -a $GITHUB_SUMMARY

