name: Prepare ncp tool to display various parameters
description: Install ncp and display vm IP
inputs:
  runner_label:
    required: false
    description: "runner label"
  sa_json:
    required: true
    description: ""
runs:
  using: composite
  steps:
    - name: env
      shell: bash
      run: |
        echo "PATH=$PATH:/root/nebius-cloud/bin" >> $GITHUB_ENV
    - name: install ncp
      shell: bash
      run: |
        curl -sSL https://storage.ai.nebius.cloud/ncp/install.sh | bash
    - name: configure ncp
      shell: bash
      run: |
        set -x

        cat <<EOF > sa.json
        ${{ inputs.sa_json }}
        EOF

        ncp config profile create nbs-github-user-sa
        ncp config set service-account-key sa.json
        ncp config set endpoint api.ai.nebius.cloud:443

    - name: print ipv4 address of the vm
      shell: bash
      run: |
        export GITHUB_RUNNER_IPV4=$(ncp compute instance get ${{ inputs.runner_label }} --format json | jq -r .network_interfaces[].primary_v4_address.one_to_one_nat.address)
        echo "GITHUB_RUNNER_IPV4=${GITHUB_RUNNER_IPV4}" >> $GITHUB_ENV
        echo "ssh -i ~/.ssh/gh-runner github@${GITHUB_RUNNER_IPV4}"

