"""Fixed frames produced by python-zstandard 0.25.0, not by our YA adapter.

The reference payload is bytes(range(256)) repeated to 4 MiB. Both frames
include the Zstandard checksum; one omits the decompressed-size header.
"""

import base64


FRAME = base64.b64decode(
    "KLUv/YRYAABAAFwIAAQQAAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4v"
    "MDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1u"
    "b3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+w"
    "sbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna29zd3t/g4eLj5OXm5+jp6uvs7e7v8PHy"
    "8/T19vf4+fr7/P3+/wEAAP3+A/maAkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQ"
    "AkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQ"
    "AkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQ"
    "AkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQ"
    "AkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQ"
    "AkwAAAgAAQD8/zkQAkwAAAgAAQD8/zkQAk0AAAgAAQD8/zkQAucbgSM="
)
UNKNOWN_SIZE_FRAME = base64.b64decode(
    "KLUv/QRYXAgABBAAAQIDBAUGBwgJCgsMDQ4PEBESExQVFhcYGRobHB0eHyAhIiMkJSYnKCkqKywtLi8wMTIzNDU2"
    "Nzg5Ojs8PT4/QEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaW1xdXl9gYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4"
    "eXp7fH1+f4CBgoOEhYaHiImKi4yNjo+QkZKTlJWWl5iZmpucnZ6foKGio6SlpqeoqaqrrK2ur7CxsrO0tba3uLm6"
    "u7y9vr/AwcLDxMXGx8jJysvMzc7P0NHS09TV1tfY2drb3N3e3+Dh4uPk5ebn6Onq6+zt7u/w8fLz9PX29/j5+vv8"
    "/f7/AQAA/f4D+ZoCTAAACAABAPz/ORACTAAACAABAPz/ORACTAAACAABAPz/ORACTAAACAABAPz/ORACTAAACAABAPz/ORAC"
    "TAAACAABAPz/ORACTAAACAABAPz/ORACTAAACAABAPz/ORACTAAACAABAPz/ORACTAAACAABAPz/ORACTAAACAABAPz/ORAC"
    "TAAACAABAPz/ORACTAAACAABAPz/ORACTAAACAABAPz/ORACTAAACAABAPz/ORACTAAACAABAPz/ORACTAAACAABAPz/ORAC"
    "TAAACAABAPz/ORACTAAACAABAPz/ORACTAAACAABAPz/ORACTAAACAABAPz/ORACTAAACAABAPz/ORACTAAACAABAPz/ORAC"
    "TAAACAABAPz/ORACTAAACAABAPz/ORACTAAACAABAPz/ORACTAAACAABAPz/ORACTAAACAABAPz/ORACTAAACAABAPz/ORAC"
    "TAAACAABAPz/ORACTQAACAABAPz/ORAC5xuBIw=="
)
SHORT_FRAME = base64.b64decode(
    "KLUv/QRYVAAAEAAAAQD7/znAAgIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAAC"
    "ABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAPv/DwCRPwtY"
)
LONG_FRAME = base64.b64decode(
    "KLUv/QRYVAAAEAAAAQD7/znAAgIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAAC"
    "ABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAAJAAAAg3Vo4w=="
)
