sequenceDiagram
    box Blockstore Server
    participant P as Partition
    participant C as Rdma Client
    end
    box Disk Agent
    participant S as Rdma Server
    participant T as Rdma Target
    end

    Note over P: Receive<br/>Read/WriteBlocksRequest
    P-->>C: Searialize<br/>Read/WriteDeviceBlocksRequest<br/>(WRITE: COPY DATA BUFFER)
    C->>S: IBV_WR_SEND<br/>(HEADER)
    S->>C: IBV_WR_RDMA_READ<br/>(READ: MSG, WRITE: MSG + DATA)
    S-->>T: Deserialize<br/>Read/WriteDeviceBlocksRequest
    Note over T: Construct<br/>Read/WriteBlocksRequest
    Note over T: AIO Read/Write<br/>(COPY DATA BUFFER)
    Note over T: Read/WriteBlocksResponse
    T-->>S: Serialize<br/>Read/WriteDeviceBlocksResponse
    S->>C: IBV_WR_RDMA_WRITE<br/>(READ: MSG + DATA, WRITE: MSG)
    S->>C: IBV_WR_SEND<br/>(HEADER)
    C-->>P: Deserialize<br/>Read/WriteDeviceBlocksResponse<br/>(READ: COPY DATA BUFFER)
    Note over P: Complete<br/>Read/WriteBlocksResponse
