actor_system_config:
  batch_executor: 2
  executor:
  - {name: System, spin_threshold: '10', threads: 8, type: BASIC}
  - {name: User, spin_threshold: '10', threads: 8, type: BASIC}
  - {name: Batch, spin_threshold: '1', threads: 8, type: BASIC}
  - {name: IO, threads: 1, type: IO}
  - {name: IC, spin_threshold: '10', threads: 3, time_per_mailbox_micro_secs: 100,
    type: BASIC}
  io_executor: 3
  scheduler: {progress_threshold: '10000', resolution: '256', spin_threshold: '0'}
  service_executor:
  - {executor_id: 4, service_name: Interconnect}
  sys_executor: 0
  user_executor: 1
blob_storage_config:
  service_set:
    availability_domains: ['1']
    groups:
    - erasure_species: 4
      group_generation: 1
      group_id: 0
      rings:
      - fail_domains:
        - vdisk_locations:
          - {node_id: 1, path: /dev/disk/by-partlabel/NVMEKIKIMR01, pdisk_category: '1',
            pdisk_guid: '10738122723267084431', pdisk_id: 1}
        - vdisk_locations:
          - {node_id: 2, path: /dev/disk/by-partlabel/NVMEKIKIMR01, pdisk_category: '1',
            pdisk_guid: '16106689533420805170', pdisk_id: 1}
        - vdisk_locations:
          - {node_id: 3, path: /dev/disk/by-partlabel/NVMEKIKIMR01, pdisk_category: '1',
            pdisk_guid: '15479661826898200215', pdisk_id: 1}
        - vdisk_locations:
          - {node_id: 4, path: /dev/disk/by-partlabel/NVMEKIKIMR01, pdisk_category: '1',
            pdisk_guid: '5795881613215917266', pdisk_id: 1}
        - vdisk_locations:
          - {node_id: 5, path: /dev/disk/by-partlabel/NVMEKIKIMR01, pdisk_category: '1',
            pdisk_guid: '18089278276041197701', pdisk_id: 1}
        - vdisk_locations:
          - {node_id: 6, path: /dev/disk/by-partlabel/NVMEKIKIMR01, pdisk_category: '1',
            pdisk_guid: '7117908886488453734', pdisk_id: 1}
        - vdisk_locations:
          - {node_id: 7, path: /dev/disk/by-partlabel/NVMEKIKIMR01, pdisk_category: '1',
            pdisk_guid: '12400000310110999597', pdisk_id: 1}
        - vdisk_locations:
          - {node_id: 8, path: /dev/disk/by-partlabel/NVMEKIKIMR01, pdisk_category: '1',
            pdisk_guid: '16321399264440587887', pdisk_id: 1}
bootstrap_config: {}
channel_profile_config:
  profile:
  - channel:
    - {erasure_species: block-4-2, pdisk_category: '1', vdisk_category: Default}
    - {erasure_species: block-4-2, pdisk_category: '1', vdisk_category: Default}
    - {erasure_species: block-4-2, pdisk_category: '1', vdisk_category: Default}
    profile_id: 0
domains_config:
  disable_builtin_security: true
  domain:
  - domain_id: 1
    name: my_cluster
    plan_resolution: '10'
    scheme_root: '72057594046678944'
    ssid: [1]
    storage_pool_types:
    - kind: ssd
      pool_config:
        box_id: '1'
        erasure_species: block-4-2
        geometry: {domain_level_begin: 10, domain_level_end: 50, num_fail_domains_per_fail_realm: 8,
          num_fail_realms: 1, num_vdisks_per_fail_domain: 1, realm_level_begin: 10,
          realm_level_end: 20}
        kind: ssd
        pdisk_filter:
        - property:
          - {type: SSD}
        vdisk_kind: Default
    - kind: ssdmirror
      pool_config:
        box_id: '1'
        erasure_species: mirror-3of4
        geometry: {domain_level_begin: 10, domain_level_end: 50, num_fail_domains_per_fail_realm: 8,
          num_fail_realms: 1, num_vdisks_per_fail_domain: 1, realm_level_begin: 10,
          realm_level_end: 20}
        kind: ssdmirror
        pdisk_filter:
        - property:
          - {type: SSD}
        vdisk_kind: Default
    - kind: rot
      pool_config:
        box_id: '1'
        erasure_species: block-4-2
        geometry: {domain_level_begin: 10, domain_level_end: 50, num_fail_domains_per_fail_realm: 8,
          num_fail_realms: 1, num_vdisks_per_fail_domain: 1, realm_level_begin: 10,
          realm_level_end: 20}
        kind: rot
        pdisk_filter:
        - property:
          - {type: ROT}
        vdisk_kind: Default
    - kind: rotmirror
      pool_config:
        box_id: '1'
        erasure_species: mirror-3of4
        geometry: {domain_level_begin: 10, domain_level_end: 50, num_fail_domains_per_fail_realm: 8,
          num_fail_realms: 1, num_vdisks_per_fail_domain: 1, realm_level_begin: 10,
          realm_level_end: 20}
        kind: rotmirror
        pdisk_filter:
        - property:
          - {type: ROT}
        vdisk_kind: Default
  state_storage:
  - ring:
      node: [1, 2, 3, 4, 5, 6, 7, 8]
      nto_select: 5
    ssid: 1
dynamic_nameservice_config: {max_static_node_id: 50000}
feature_flags: {enable_separate_solomon_shard_for_pdisk: true, enable_vpatch: true}
grpc_config:
  grpc_memory_quota_bytes: '1073741824'
  host: '[::]'
  keep_alive_enable: true
  keep_alive_idle_timeout_trigger_sec: 90
  keep_alive_max_probe_count: 3
  keep_alive_probe_interval_sec: 10
  port: 2135
  start_grpc_proxy: true
  streaming_config: {enable_output_streams: true}
hosts:
- host: my.host1
  location: {body: 1, data_center: my_dc, rack: 'lab-1:1'}
  node_id: 1
- host: my.host2
  location: {body: 2, data_center: my_dc, rack: 'lab-2:1'}
  node_id: 2
- host: my.host3
  location: {body: 3, data_center: my_dc, rack: 'lab-3:1'}
  node_id: 3
- host: my.host4
  location: {body: 4, data_center: my_dc, rack: 'lab-4:1'}
  node_id: 4
- host: my.host5
  location: {body: 5, data_center: my_dc, rack: 'lab-5:1'}
  node_id: 5
- host: my.host6
  location: {body: 6, data_center: my_dc, rack: 'lab-6:1'}
  node_id: 6
- host: my.host7
  location: {body: 7, data_center: my_dc, rack: 'lab-7:1'}
  node_id: 7
- host: my.host8
  location: {body: 8, data_center: my_dc, rack: 'lab-8:1'}
  node_id: 8
interconnect_config:
  handshake_timeout_duration: {seconds: '1'}
  max_inflight_amount_of_data_in_kb: 10240
  start_tcp: true
kqpconfig:
  enable: true
  settings:
  - {name: _ResultRowsLimit, value: '10000'}
log_config: {default_level: 3}
nameservice_config:
  accept_uuid: ['2452520']
  cluster_uuid: '2452520'
pqconfig: {enabled: false}
static_erasure: block-4-2
system_tablets:
  cms:
  - info: {tablet_id: '72057594037936128'}
    node: [1, 2, 3, 4, 5, 6, 7, 8]
  console:
  - info: {tablet_id: '72057594037936131'}
    node: [1, 2, 3, 4, 5, 6, 7, 8]
  flat_bs_controller:
  - info: {tablet_id: '72057594037932033'}
    node: [1, 2, 3, 4, 5, 6, 7, 8]
  flat_hive:
  - info: {tablet_id: '72057594037968897'}
    node: [1, 2, 3, 4, 5, 6, 7, 8]
  flat_schemeshard:
  - info: {tablet_id: '72057594046678944'}
    node: [1, 2, 3, 4, 5, 6, 7, 8]
  flat_tx_coordinator:
  - info: {tablet_id: '72057594046316545'}
    node: [1, 2, 3, 4, 5, 6, 7, 8]
  - info: {tablet_id: '72057594046316546'}
    node: [1, 2, 3, 4, 5, 6, 7, 8]
  - info: {tablet_id: '72057594046316547'}
    node: [1, 2, 3, 4, 5, 6, 7, 8]
  node_broker:
  - info: {tablet_id: '72057594037936129'}
    node: [1, 2, 3, 4, 5, 6, 7, 8]
  tenant_slot_broker:
  - info: {tablet_id: '72057594037936130'}
    node: [1, 2, 3, 4, 5, 6, 7, 8]
  tx_allocator:
  - info: {tablet_id: '72057594046447617'}
    node: [1, 2, 3, 4, 5, 6, 7, 8]
  - info: {tablet_id: '72057594046447618'}
    node: [1, 2, 3, 4, 5, 6, 7, 8]
  - info: {tablet_id: '72057594046447619'}
    node: [1, 2, 3, 4, 5, 6, 7, 8]
  tx_mediator:
  - info: {tablet_id: '72057594046382081'}
    node: [1, 2, 3, 4, 5, 6, 7, 8]
  - info: {tablet_id: '72057594046382082'}
    node: [1, 2, 3, 4, 5, 6, 7, 8]
  - info: {tablet_id: '72057594046382083'}
    node: [1, 2, 3, 4, 5, 6, 7, 8]
vdisk_config:
  vdisk_kinds:
  - base_kind: Default
    config: {allow_keep_flags: false, fresh_use_dreg: true}
    kind: Log
  - base_kind: Default
    config: {hull_comp_level0_max_ssts_at_once: 2, hull_comp_sorted_parts_num: 1}
    kind: LocalMode

