LIBRARY()

SRCS(
    fresh_blocks_companion_client.cpp
    io_companion_client.cpp
    part2_addblobs_logic.cpp
    part2.cpp
    part2_actor.cpp
    part2_actor_addblobs.cpp
    part2_actor_addconfirmedblobs.cpp
    part2_actor_addgarbage.cpp
    part2_actor_addunconfirmedblobs.cpp
    part2_actor_changedblocks.cpp
    part2_actor_checkpoint.cpp
    part2_actor_checkrange.cpp
    part2_actor_cleanup.cpp
    part2_actor_collectgarbage.cpp
    part2_actor_compaction.cpp
    part2_actor_compactrange.cpp
    part2_actor_confirmblobs.cpp
    part2_actor_deletegarbage.cpp
    part2_actor_deleteunconfirmedblobs.cpp
    part2_actor_describeblocks.cpp
    part2_actor_flush.cpp
    part2_actor_getusedblocks.cpp
    part2_actor_initschema.cpp
    part2_actor_level_compaction.cpp
    part2_actor_loadstate.cpp
    part2_actor_metadata_rebuild_blockcount.cpp
    part2_actor_metadata_rebuild_usedblocks.cpp
    part2_actor_metadata_rebuild.cpp
    part2_actor_monitoring.cpp
    part2_actor_monitoring_check.cpp
    part2_actor_monitoring_compaction.cpp
    part2_actor_monitoring_describe.cpp
    part2_actor_monitoring_garbage.cpp
    part2_actor_monitoring_view.cpp
    part2_actor_readblobinfo.cpp
    part2_actor_readblocks.cpp
    part2_actor_scan_disk.cpp
    part2_actor_statpartition.cpp
    part2_actor_stats.cpp
    part2_actor_trimfreshlog.cpp
    part2_actor_waitready.cpp
    part2_actor_writeblocks.cpp
    part2_actor_writefreshblocks.cpp
    part2_actor_writemergedblocks.cpp
    part2_actor_writemixedblocks.cpp
    part2_actor_writequeue.cpp
    part2_actor_zeroblocks.cpp
    part2_cleanup_logic.cpp
    part2_compaction_logic.cpp
    part2_readblobinfo_logic.cpp
    part2_counters.cpp
    part2_database.cpp
    part2_schema.cpp
    part2_state.cpp
)

PEERDIR(
    cloud/blockstore/libs/common
    cloud/blockstore/libs/diagnostics
    cloud/blockstore/libs/kikimr
    cloud/blockstore/libs/storage/api
    cloud/blockstore/libs/storage/core
    cloud/blockstore/libs/storage/partition2/model
    cloud/blockstore/libs/storage/partition_common
    cloud/blockstore/libs/storage/protos

    cloud/storage/core/libs/api
    cloud/storage/core/libs/common
    cloud/storage/core/libs/tablet
    cloud/storage/core/libs/viewer

    library/cpp/blockcodecs
    library/cpp/cgiparam
    library/cpp/containers/dense_hash
    library/cpp/lwtrace
    library/cpp/monlib/service/pages

    contrib/ydb/core/base
    contrib/ydb/core/blobstorage
    contrib/ydb/core/node_whiteboard
    contrib/ydb/core/scheme
    contrib/ydb/core/tablet
    contrib/ydb/core/tablet_flat
    contrib/ydb/library/actors/core
)

END()

RECURSE(
    model
)

RECURSE_FOR_TESTS(
    ut
)
