use_walle: False
use_fixed_tablet_types: True
require_address: False
cluster_uuid: "2452520"
static_pdisk_type: SSD
static_erasure: block-4-2
fail_domain_type: body
features:
  enable_separate_solomon_shard_for_PDisk: true
  enable_VPatch: true
monitoring_address: "::"
hosts:
  - name: my.host1
    body: '1'
    datacenter: 'my_dc'
    rack: 'lab-1:1'
    drives: &disk_set_nvme3_hdd1
      - path: /dev/disk/by-partlabel/NVMEKIKIMR01
        type: SSD
      - path: /dev/disk/by-partlabel/NVMEKIKIMR02
        type: SSD
      - path: /dev/disk/by-partlabel/NVMEKIKIMR03
        type: SSD
      - path: /dev/disk/by-partlabel/ROTKIKIMR01
        type: ROT
  - name: my.host2
    body: '2'
    datacenter: 'my_dc'
    rack: 'lab-2:1'
    drives: *disk_set_nvme3_hdd1
  - name: my.host3
    body: '3'
    datacenter: 'my_dc'
    rack: 'lab-3:1'
    drives: *disk_set_nvme3_hdd1
  - name: my.host4
    body: '4'
    datacenter: 'my_dc'
    rack: 'lab-4:1'
    drives: *disk_set_nvme3_hdd1
  - name: my.host5
    body: '5'
    datacenter: 'my_dc'
    rack: 'lab-5:1'
    drives: *disk_set_nvme3_hdd1
  - name: my.host6
    body: '6'
    datacenter: 'my_dc'
    rack: 'lab-6:1'
    drives: *disk_set_nvme3_hdd1
  - name: my.host7
    body: '7'
    datacenter: 'my_dc'
    rack: 'lab-7:1'
    drives: *disk_set_nvme3_hdd1
  - name: my.host8
    body: '8'
    datacenter: 'my_dc'
    rack: 'lab-8:1'
    drives: *disk_set_nvme3_hdd1
ic:
  max_inflight_amount_of_data_in_KB: 10240
  handshake_timeout_duration:
    seconds: 1
kqp:
  result_rows_limit: 10000
log:
  default: 3
domains:
  - domain_name: my_cluster
    storage_pool_kinds:
      - kind: "ssd"
        erasure: block-4-2
        fail_domain_type: body
        filter_properties:
          type: SSD
      - kind: "rot"
        erasure: block-4-2
        fail_domain_type: body
        filter_properties:
          type: ROT
      - kind: "ssdmirror"
        erasure: mirror-3of4
        fail_domain_type: body
        filter_properties:
          type: SSD
      - kind: "rotmirror"
        erasure: mirror-3of4
        fail_domain_type: body
        filter_properties:
          type: ROT
    databases:
      - name: NBS
        storage_units:
          - kind: ssd
            count: 10
          - kind: rot
            count: 5
          - kind: rotmirror
            count: 5
          - kind: ssdmirror
            count: 10
        overridden_configs:
          nbs:
            enable: true
            names:
              suppress_version_check: True
          nbs_control:
            enable: true
      - name: NFS
        storage_units:
          - kind: ssd
            count: 20
          - kind: rot
            count: 1
        overridden_configs:
          nfs:
            enable: true
sys:
  scheduler:
    resolution: 256
  executors:
    user:
      threads: 8
      spin_threshold: 10
    system:
      threads: 8
      spin_threshold: 10
    io:
      threads: 1
    batch:
      threads: 8

