syntax = "proto3";

import "cloud/filestore/public/api/protos/data.proto";

package NCloud.NFileStore.NProto;

message TQueuedCreateHandleRequest
{
    TCreateHandleRequest Request = 1;
    uint64 Handle = 2;
    uint64 NodeId = 3;

    // Stored separately for convenience. This value is also contained in
    // Request.Headers.RequestId.
    uint64 OriginalRequestId = 4;
}

message TQueueEntry
{
     oneof Request {
          TQueuedCreateHandleRequest QueuedCreateHandleRequest = 1;
          TDestroyHandleRequest DestroyHandleRequest = 2;
    }
}
