LIBRARY()

SRCS(
    kqp_expression.cpp
    kqp_olap_expr_inspection.cpp
    kqp_operator.cpp
    kqp_plan_conversion_utils.cpp
    kqp_plan_to_json.cpp
    kqp_rbo_compute_statistics.cpp
    kqp_rbo_context.cpp
    kqp_rbo_statistics.cpp
    kqp_rbo_transformer.cpp
    kqp_rbo_type_ann.cpp
    kqp_rbo_utils.cpp
    kqp_rbo.cpp
    kqp_rewrite_select.cpp
    kqp_stage_graph.cpp
    analysis/logical_aliases.cpp
    analysis/logical_liveness.cpp
    analysis/logical_name_constraints.cpp
    logical_renames.cpp
    traces/kqp_rbo_trace_format.cpp
    traces/kqp_rbo_trace.cpp
    traces/kqp_rbo_trace_log.cpp
    traces/kqp_rbo_trace_output.cpp
    traces/kqp_rbo_rule_trace.cpp
)

PEERDIR(
    library/cpp/containers/absl_flat_hash
    library/cpp/containers/stack_vector
    contrib/ydb/core/kqp/common
    contrib/ydb/core/kqp/opt/cbo
    contrib/ydb/core/kqp/opt/cbo/solver
    contrib/ydb/core/kqp/opt/logical
    contrib/ydb/core/kqp/opt/peephole
    contrib/ydb/core/kqp/opt/physical
    contrib/ydb/core/kqp/opt/rbo/html_log
    contrib/ydb/core/kqp/opt/rbo/rules
    contrib/ydb/core/kqp/opt/rbo/physical_conversion
    contrib/ydb/library/yql/dq/common
    contrib/ydb/library/yql/dq/opt
    contrib/ydb/library/yql/dq/type_ann
    contrib/ydb/library/yql/providers/s3/expr_nodes
    contrib/ydb/library/yql/providers/s3/statistics
    contrib/ydb/library/yql/utils/plan
    contrib/ydb/core/kqp/provider
    contrib/ydb/library/formats/arrow/protos
    contrib/ydb/library/yql/core/extract_predicate
)

YQL_LAST_ABI_VERSION()

END()
