// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.0
// source: cloud/storage/core/protos/certificate.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TCertificate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CertFile           *string `protobuf:"bytes,1,opt,name=CertFile" json:"CertFile,omitempty"`
	CertPrivateKeyFile *string `protobuf:"bytes,2,opt,name=CertPrivateKeyFile" json:"CertPrivateKeyFile,omitempty"`
}

func (x *TCertificate) Reset() {
	*x = TCertificate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_storage_core_protos_certificate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCertificate) ProtoMessage() {}

func (x *TCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_storage_core_protos_certificate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCertificate.ProtoReflect.Descriptor instead.
func (*TCertificate) Descriptor() ([]byte, []int) {
	return file_cloud_storage_core_protos_certificate_proto_rawDescGZIP(), []int{0}
}

func (x *TCertificate) GetCertFile() string {
	if x != nil && x.CertFile != nil {
		return *x.CertFile
	}
	return ""
}

func (x *TCertificate) GetCertPrivateKeyFile() string {
	if x != nil && x.CertPrivateKeyFile != nil {
		return *x.CertPrivateKeyFile
	}
	return ""
}

var File_cloud_storage_core_protos_certificate_proto protoreflect.FileDescriptor

var file_cloud_storage_core_protos_certificate_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x4e,
	0x43, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x0c,
	0x54, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x43, 0x65, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x43, 0x65, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x43, 0x65, 0x72, 0x74,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x43, 0x65, 0x72, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x4b, 0x65, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x61, 0x2e, 0x79, 0x61,
	0x6e, 0x64, 0x65, 0x78, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x72, 0x75, 0x2f, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
}

var (
	file_cloud_storage_core_protos_certificate_proto_rawDescOnce sync.Once
	file_cloud_storage_core_protos_certificate_proto_rawDescData = file_cloud_storage_core_protos_certificate_proto_rawDesc
)

func file_cloud_storage_core_protos_certificate_proto_rawDescGZIP() []byte {
	file_cloud_storage_core_protos_certificate_proto_rawDescOnce.Do(func() {
		file_cloud_storage_core_protos_certificate_proto_rawDescData = protoimpl.X.CompressGZIP(file_cloud_storage_core_protos_certificate_proto_rawDescData)
	})
	return file_cloud_storage_core_protos_certificate_proto_rawDescData
}

var file_cloud_storage_core_protos_certificate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cloud_storage_core_protos_certificate_proto_goTypes = []interface{}{
	(*TCertificate)(nil), // 0: NCloud.NProto.TCertificate
}
var file_cloud_storage_core_protos_certificate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cloud_storage_core_protos_certificate_proto_init() }
func file_cloud_storage_core_protos_certificate_proto_init() {
	if File_cloud_storage_core_protos_certificate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cloud_storage_core_protos_certificate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TCertificate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cloud_storage_core_protos_certificate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_storage_core_protos_certificate_proto_goTypes,
		DependencyIndexes: file_cloud_storage_core_protos_certificate_proto_depIdxs,
		MessageInfos:      file_cloud_storage_core_protos_certificate_proto_msgTypes,
	}.Build()
	File_cloud_storage_core_protos_certificate_proto = out.File
	file_cloud_storage_core_protos_certificate_proto_rawDesc = nil
	file_cloud_storage_core_protos_certificate_proto_goTypes = nil
	file_cloud_storage_core_protos_certificate_proto_depIdxs = nil
}
