# Generated by devtools/yamaker.

LIBRARY()

LICENSE(LGPL-2.1-only)
LICENSE_TEXTS(contrib/libs/libnl/COPYING)

NO_COMPILER_WARNINGS()
NO_RUNTIME()

IF (NETLINK == "local")
    DEFAULT(LOCAL_NETLINK_CFLAGS -I/usr/include/libnl3)
    GLOBAL_CFLAGS(${LOCAL_NETLINK_CFLAGS})

    DEFAULT(LOCAL_NETLINK_LDFLAGS -L/usr/lib/x86_64-linux-gnu -lnl-idiag-3)
    LDFLAGS(${LOCAL_NETLINK_LDFLAGS})
ELSE()
    ADDINCL(
        GLOBAL contrib/libs/libnl/include
    )
    PEERDIR(
        contrib/libs/libnl/lib/nl-3
    )
    SRCS(
        idiag.c
        idiag_meminfo_obj.c
        idiag_msg_obj.c
        idiag_req_obj.c
        idiag_vegasinfo_obj.c
    )
ENDIF()

END()
