# Generated by devtools/yamaker.

LIBRARY()

OWNER(g:cpp-contrib)

LICENSE(LGPL-2.1-only)

LICENSE_TEXTS(contrib/restricted/libnl/COPYING)

PEERDIR(
    contrib/libs/linux-headers
)

ADDINCL(
    GLOBAL contrib/restricted/libnl/include
)

NO_COMPILER_WARNINGS()

NO_RUNTIME()

CFLAGS(
    -DHAVE_CONFIG_H
    -DSYSCONFDIR=\"/etc/libnl\"
)

SRCDIR(contrib/restricted/libnl/lib)

SRCS(
    addr.c
    attr.c
    cache.c
    cache_mngr.c
    cache_mngt.c
    data.c
    error.c
    handlers.c
    hash.c
    hashtable.c
    mpls.c
    msg.c
    nl.c
    object.c
    socket.c
    utils.c
    version.c
)

END()
