#include <profiler/symbolizer.h>

#include <gtest/gtest.h>

#include <unistd.h>

// Non-static so the symbol is exported to .dynsym, which backtrace_syminfo
// reads on all platforms and build configurations (including coverage).
__attribute__((noinline)) void knownFunction()
{
}

TEST(Symbolizer, ReadMappingsSucceeds)
{
    Symbolizer sym;

    int r = sym.readSelfMappings();
    EXPECT_EQ(r, 0);

    r = sym.readMappings(::getpid());
    EXPECT_EQ(r, 0);
}

TEST(Symbolizer, ResolveKnownFunction)
{
    Symbolizer sym;

    int r = sym.readSelfMappings();
    ASSERT_EQ(r, 0);

    r = sym.readMappings(::getpid());
    ASSERT_EQ(r, 0);

    uint64_t addr = reinterpret_cast<uint64_t>(reinterpret_cast<void *>(&knownFunction));
    const std::string & name = sym.resolve(addr);

    EXPECT_NE(name.find("knownFunction"), std::string::npos);
}

TEST(Symbolizer, ResolveUnmappedAddressReturnsHex)
{
    Symbolizer sym;

    int r = sym.readSelfMappings();
    ASSERT_EQ(r, 0);

    r = sym.readMappings(::getpid());
    ASSERT_EQ(r, 0);

    const std::string & name = sym.resolve(0x1234);
    EXPECT_EQ(name, "0x1234");
}

TEST(Symbolizer, CacheReturnsSameReference)
{
    Symbolizer sym;

    int r = sym.readSelfMappings();
    ASSERT_EQ(r, 0);

    r = sym.readMappings(::getpid());
    ASSERT_EQ(r, 0);

    uint64_t addr = reinterpret_cast<uint64_t>(reinterpret_cast<void *>(&knownFunction));
    const std::string & first = sym.resolve(addr);
    const std::string & second = sym.resolve(addr);

    EXPECT_EQ(&first, &second);
}


TEST(Symbolizer, DemangleOptions)
{
    constexpr auto stripAll = static_cast<int>(Symbolizer::DemangleOptions::StripAnonymousNamespace)
        | static_cast<int>(Symbolizer::DemangleOptions::StripArguments);

    EXPECT_EQ(
        (static_cast<int>(Symbolizer::DemangleOptions::StripAll) & static_cast<int>(Symbolizer::DemangleOptions::StripAnonymousNamespace)),
        static_cast<int>(Symbolizer::DemangleOptions::StripAnonymousNamespace));
    EXPECT_EQ(
        (static_cast<int>(Symbolizer::DemangleOptions::StripAll) & static_cast<int>(Symbolizer::DemangleOptions::StripArguments)),
        static_cast<int>(Symbolizer::DemangleOptions::StripArguments));
    EXPECT_NE(static_cast<int>(Symbolizer::DemangleOptions::StripAll), static_cast<int>(Symbolizer::DemangleOptions::StripNone));
    EXPECT_EQ(stripAll, static_cast<int>(Symbolizer::DemangleOptions::StripAll));
}

TEST(Symbolizer, DemangleResults)
{
    /*
    Mangled symbols generated by script like this:

    g++ -std=c++20 -c -x c++ -o /tmp/mangle.o - <<'CPP'
    #include <string>

    namespace foo {

    // foo::bar1
    [[gnu::used]] void bar1() {}

    struct Bar4 {
        [[gnu::used]] void bar4(int) const {}
    };

    } // namespace foo

    int main() {
    }
    CPP

    nm -C /tmp/mangle.o | egrep 'bar|f'
    nm /tmp/mangle.o | egrep 'bar|f'
    */
    const char * bar1Mangled = "_ZN3foo4bar1Ev";
    EXPECT_EQ(Symbolizer::demangle(bar1Mangled, Symbolizer::DemangleOptions::StripAll), "foo::bar1");
    EXPECT_EQ(Symbolizer::demangle(bar1Mangled, Symbolizer::DemangleOptions::StripNone), "foo::bar1()");

    const char * bar2Mangled = "_Z4bar2v";
    EXPECT_EQ(Symbolizer::demangle(bar2Mangled, Symbolizer::DemangleOptions::StripAll), "bar2");
    EXPECT_EQ(Symbolizer::demangle(bar2Mangled, Symbolizer::DemangleOptions::StripNone), "bar2()");

    const char * bar3Mangled = "_ZN3foo4bar3Ei";
    EXPECT_EQ(Symbolizer::demangle(bar3Mangled, Symbolizer::DemangleOptions::StripAll), "foo::bar3");
    EXPECT_EQ(Symbolizer::demangle(bar3Mangled, Symbolizer::DemangleOptions::StripNone), "foo::bar3(int)");

    const char * bar4Mangled = "_ZNK3foo4Bar44bar4Ei";
    EXPECT_EQ(Symbolizer::demangle(bar4Mangled, Symbolizer::DemangleOptions::StripAll), "foo::Bar4::bar4");
    EXPECT_EQ(Symbolizer::demangle(bar4Mangled, Symbolizer::DemangleOptions::StripNone), "foo::Bar4::bar4(int) const");

    const char * bar5Mangled = "_Z4bar5iNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE";
    EXPECT_EQ(Symbolizer::demangle(bar5Mangled, Symbolizer::DemangleOptions::StripAll), "bar5");
    // Expected: "bar5(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)"
    const auto bar5Demangled = Symbolizer::demangle(bar5Mangled, Symbolizer::DemangleOptions::StripNone);
    // Using .find() instead of EXPECT_EQ because libc++ and libstdc++ have different
    // demangling styles for the allocator template parameter.
    EXPECT_EQ(0, bar5Demangled.find("bar5(int,"));
    EXPECT_NE(bar5Demangled.find("basic_string"), std::string::npos);

    const char * bar6Mangled = "_ZN12_GLOBAL__N_13foo4bar6Ev";
    EXPECT_EQ(Symbolizer::demangle(bar6Mangled, Symbolizer::DemangleOptions::StripAll), "foo::bar6");
    EXPECT_EQ(Symbolizer::demangle(bar6Mangled, Symbolizer::DemangleOptions::StripAnonymousNamespace), "foo::bar6()");
    EXPECT_EQ(Symbolizer::demangle(bar6Mangled, Symbolizer::DemangleOptions::StripArguments), "(anonymous namespace)::foo::bar6");
    EXPECT_EQ(Symbolizer::demangle(bar6Mangled, Symbolizer::DemangleOptions::StripNone), "(anonymous namespace)::foo::bar6()");

    const char * bar7Mangled = "_ZN12_GLOBAL__N_13foo12_GLOBAL__N_14bar7Ev";
    EXPECT_EQ(Symbolizer::demangle(bar7Mangled, Symbolizer::DemangleOptions::StripAll), "foo::bar7");
    EXPECT_EQ(
        Symbolizer::demangle(bar7Mangled, Symbolizer::DemangleOptions::StripNone),
        "(anonymous namespace)::foo::(anonymous namespace)::bar7()");

    const char * bar8Mangled = "_ZN3foo12_GLOBAL__N_14bar8Ev";
    EXPECT_EQ(Symbolizer::demangle(bar8Mangled, Symbolizer::DemangleOptions::StripAll), "foo::bar8");
    EXPECT_EQ(Symbolizer::demangle(bar8Mangled, Symbolizer::DemangleOptions::StripNone), "foo::(anonymous namespace)::bar8()");

    const char * bar9Mangled = "_ZN12_GLOBAL__N_13foo12_GLOBAL__N_14bar9EiNS_3xyzE";
    EXPECT_EQ(Symbolizer::demangle(bar9Mangled, Symbolizer::DemangleOptions::StripAll), "foo::bar9");
    EXPECT_EQ(
        Symbolizer::demangle(bar9Mangled, Symbolizer::DemangleOptions::StripNone),
        "(anonymous namespace)::foo::(anonymous namespace)::bar9(int, (anonymous namespace)::xyz)");

    const char * bar10Mangled = "_ZNK12_GLOBAL__N_13foo5Bar105bar10Ei";
    EXPECT_EQ(Symbolizer::demangle(bar10Mangled, Symbolizer::DemangleOptions::StripAll), "foo::Bar10::bar10");
    EXPECT_EQ(
        Symbolizer::demangle(bar10Mangled, Symbolizer::DemangleOptions::StripNone), "(anonymous namespace)::foo::Bar10::bar10(int) const");

    const char * bar11Mangled = "_ZN12_GLOBAL__N_15bar11EiNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE";
    EXPECT_EQ(Symbolizer::demangle(bar11Mangled, Symbolizer::DemangleOptions::StripAll), "bar11");
    // Expected: "(anonymous namespace)::bar11(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)"
    const auto bar11Demangled = Symbolizer::demangle(bar11Mangled, Symbolizer::DemangleOptions::StripNone);
    // Using .find() instead of EXPECT_EQ because libc++ and libstdc++ have different
    // demangling styles for the allocator template parameter.
    EXPECT_EQ(0, bar11Demangled.find("(anonymous namespace)::bar11(int,"));
    EXPECT_NE(bar11Demangled.find("basic_string"), std::string::npos);

    const char * fpMangled = "_Z1fPFviE";
    EXPECT_EQ(Symbolizer::demangle(fpMangled, Symbolizer::DemangleOptions::StripNone), "f(void (*)(int))");
    EXPECT_EQ(Symbolizer::demangle(fpMangled, Symbolizer::DemangleOptions::StripAll), "f");
}
