RECURSE(
    selftest

    local
    local-auth
    local-bsgroup-failure
    local-change-device
    local-checkpoint
    local-checksums
    local-discovery
    local-edgecase
    local-emergency
    local-encryption
    local-endpoints
    local-metrics
    local-mirror
    local-mirror-lagging
    local-nemesis
    local-newfeatures
    local-nonrepl
    local-null
    local-overflow
    local-overlay
    local-throttling
    local-user-metrics
    local-v2
    compaction
)
