name: Delete runner VM
description: Delete runner VM using create-vm.py
inputs:
  repo_owner:
    required: true
    description: "repo owner"
  repo:
    required: true
    description: "repo name"
  service_account_key:
    required: true
    description: "service account key"
  token:
    required: true
    description: "GITHUB_TOKEN"
  vm_id:
    required: true
    description: "vm id"


runs:
  using: composite
  steps:
    - name: write service account key to file
      shell: bash
      run: |
        export SERVICE_ACCOUNT_KEY=$(mktemp)
        echo "SERVICE_ACCOUNT_KEY=${SERVICE_ACCOUNT_KEY}" >> $GITHUB_ENV
        echo "${key_contents}" > $SERVICE_ACCOUNT_KEY
      env:
        key_contents: ${{ inputs.service_account_key }}
    - name: install dependencies
      shell: bash
      run: |
        pip install yandexcloud==0.258.0 PyGithub==2.2.0
    - name: remove vm
      id: remove-vm
      shell: bash
      run: |
        python .github/scripts/create-vm.py remove \
          --github-repo-owner "${REPO_OWNER}" \
          --github-repo "${REPO}" \
          --service-account-key "${SERVICE_ACCOUNT_KEY}" \
          --id "${VM_ID}" \
          --apply
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        REPO_OWNER: ${{ inputs.repo_owner }}
        REPO: ${{ inputs.repo }}
        VM_ID: ${{ inputs.vm_id }}