syntax = "proto3";

import "cloud/filestore/public/api/protos/ping.proto";
import "cloud/storage/core/protos/drain.proto";

package NCloud.NFileStore.NProtoPrivate;

option go_package = "github.com/ydb-platform/nbs/cloud/filestore/private/api/protos";

////////////////////////////////////////////////////////////////////////////////
// DrainNode

message TDrainNodeRequest
{
    // Deprecated in favor of DownPolicy.
    bool KeepDown = 1 [deprecated = true];

    // Controls whether and for how long the node stays down after draining.
    NCloud.NProto.EDrainDownPolicy DownPolicy = 2;
}

message TDrainNodeResponse
{
}

////////////////////////////////////////////////////////////////////////////////
// ReassignTablet

message TReassignTabletRequest
{
    uint64 TabletId = 1;
    repeated uint32 Channels = 2;
}

message TReassignTabletResponse
{
}

////////////////////////////////////////////////////////////////////////////////
// ListLocalFileStores request/response.

message TListLocalFileStoresRequest
{
}

message TListLocalFileStoresResponse
{
    repeated string FileSystemIds = 1;
}

////////////////////////////////////////////////////////////////////////////////
// Toggle service state request/response

message TToggleServiceStateRequest
{
    // Desired service state.
    NProto.EServiceState DesiredServiceState = 1;
}

message TToggleServiceStateResponse
{
}
