apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
   - name: pause
     image: ubuntu:latest
     command:
       - sleep
       - "3600"
     volumeMounts:
       - name: my-volume
         mountPath: /tmp
  volumes:
   - name: my-volume
     persistentVolumeClaim:
       claimName: my-pvc
       readOnly: false