client_methods = [
    ("ping", "Ping"),
    ("create_volume", "CreateVolume"),
    ("destroy_volume", "DestroyVolume"),
    ("resize_volume", "ResizeVolume"),
    ("alter_volume", "AlterVolume"),
    ("assign_volume", "AssignVolume"),
    ("stat_volume", "StatVolume"),
    ("mount_volume", "MountVolume"),
    ("unmount_volume", "UnmountVolume"),
    ("read_blocks", "ReadBlocks"),
    ("write_blocks", "WriteBlocks"),
    ("zero_blocks", "ZeroBlocks"),
    ("create_checkpoint", "CreateCheckpoint"),
    ("delete_checkpoint", "DeleteCheckpoint"),
    ("get_changed_blocks", "GetChangedBlocks"),
    ("describe_volume", "DescribeVolume"),
    ("describe_volume_model", "DescribeVolumeModel"),
    ("list_volumes", "ListVolumes"),
    ("discover_instances", "DiscoverInstances"),
    ("query_available_storage", "QueryAvailableStorage"),
    ("start_endpoint", "StartEndpoint"),
    ("stop_endpoint", "StopEndpoint"),
    ("refresh_endpoint", "RefreshEndpoint"),
    ("list_endpoints", "ListEndpoints"),
    ("cancel_endpoint_in_flight_requests", "CancelEndpointInFlightRequests"),
]
