let rowsElement;
let filterForm;
let filterElement;
let clearFilterElement;
let filterStatus;
let minimumDurationElement;
let clearMinimumDurationElement;
let testPhaseElement;
let clearFiltersElement;
let rowLoadSizeElement;
let timelineModeElement;
let rowLoader;
let rowLoadButton;
let rowStatus;
let traceElement;
let traceHeadElement;
let columnResizerElement;
let columnResizeState = null;
let toolbarResizeObserver = null;
let model;
let traceIndex;
let spans;
let children;
let roots;
let expanded;
let limits;
let visible;
let selected = null;
let searchCache = [];
let rowBudget = INITIAL_ROW_BUDGET;
let filterTimer;
