# Generated by devtools/yamaker.

LIBRARY()

LICENSE(BSD-3-Clause)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

PEERDIR(
    contrib/libs/dpdk/drivers/bus/pci
    contrib/libs/dpdk/drivers/mempool/ring
    contrib/libs/dpdk/lib/librte_eal
    contrib/libs/dpdk/lib/librte_mempool
    contrib/libs/spdk/lib/log
)

ADDINCL(contrib/libs/spdk/include)

NO_COMPILER_WARNINGS()

NO_RUNTIME()

CFLAGS(-DALLOW_EXPERIMENTAL_API)

SRCS(
    GLOBAL pci_idxd.c
    GLOBAL pci_ioat.c
    GLOBAL pci_virtio.c
    GLOBAL pci_vmd.c
    GLOBAL sigbus_handler.c
    env.c
    init.c
    memory.c
    pci.c
    pci_event.c
    threads.c
)

END()
