name: Test threads calculator
description: Calculate threads for tests basd on VM preset
inputs:
  vm_preset:
    required: true
    description: "vm preset"
  tests_size:
    required: true
    description: "tests size"

outputs:
  build_threads:
    description: "Number of threads for building code"
    value: ${{ steps.calculate-threads.outputs.build_threads }}
  test_threads:
    description: "Number of threads for launching tests"
    value: ${{ steps.calculate-threads.outputs.test_threads }}
  link_threads:
    description: "Number of threads used for linking"
    value: ${{ steps.calculate-threads.outputs.link_threads }}

runs:
  using: composite
  steps:
    - name: Calculate threads
      id: calculate-threads
      shell: bash
      run: |
        echo "vm_preset: ${VM_PRESET}"
        echo "tests_size: ${TESTS_SIZE}"
        echo "checking size of the tests could be small, medium, large and combination of them"
        test_threads=0
        if [[ $TESTS_SIZE == *"large"* ]]; then
          case "$VM_PRESET" in
            # for large tests we need 6 vcpu per thread
            "256vcpu-1024gb")
                test_threads=42
                build_threads=256
            ;;
            "224vcpu-896gb")
                test_threads=38
                build_threads=224
            ;;
            "192vcpu-768gb")
                test_threads=32
                build_threads=192
            ;;
            "160vcpu-640gb")
                test_threads=26
                build_threads=160
            ;;
            "128vcpu-512gb")
                test_threads=21
                build_threads=128
            ;;
            "96vcpu-384gb")
                test_threads=16
                build_threads=96
            ;;
            "80vcpu-320gb")
                test_threads=14
                build_threads=80
            ;;
            "64vcpu-256gb")
                test_threads=10
                build_threads=64
            ;;
            "48vcpu-192gb")
                test_threads=8
                build_threads=48
            ;;
            "32vcpu-128gb")
                test_threads=5
                build_threads=32
            ;;
            "16vcpu-64gb")
                test_threads=3
                build_threads=16
            ;;
            "8vcpu-32gb")
                test_threads=2
                build_threads=8
            ;;
            "4vcpu-16gb")
                test_threads=1
                build_threads=4
            ;;
            "2vcpu-8gb")
                test_threads=1
                build_threads=2
            ;;
            *)
              echo "Unknown vm_preset: $VM_PRESET"
              exit 1
            ;;
          esac
        else
          case "$VM_PRESET" in
            "256vcpu-1024gb")
                test_threads=64
                build_threads=256
            ;;
            "224vcpu-896gb")
                test_threads=56
                build_threads=224
            ;;
            "192vcpu-768gb")
                test_threads=48
                build_threads=192
            ;;
            "160vcpu-640gb")
                test_threads=40
                build_threads=160
            ;;
            "128vcpu-512gb")
                test_threads=32
                build_threads=128
            ;;
            "96vcpu-384gb")
                test_threads=24
                build_threads=96
            ;;
            "80vcpu-320gb")
                test_threads=20
                build_threads=80
            ;;
            "64vcpu-256gb")
                test_threads=16
                build_threads=64
            ;;
            "48vcpu-192gb")
                test_threads=12
                build_threads=48
            ;;
            "32vcpu-128gb")
                test_threads=8
                build_threads=32
            ;;
            "16vcpu-64gb")
                test_threads=4
                build_threads=16
            ;;
            "8vcpu-32gb")
                test_threads=2
                build_threads=8
            ;;
            "4vcpu-16gb")
                test_threads=1
                build_threads=4
            ;;
            "2vcpu-8gb")
                test_threads=1
                build_threads=2
            ;;
            *)
              echo "Unknown vm_preset: $VM_PRESET"
              exit 1
            ;;
          esac
        fi
        link_threads=$(( test_threads * 2 ))
        {
          echo "build_threads=$build_threads"
          echo "test_threads=$test_threads"
          echo "link_threads=$link_threads"
        } | tee -a $GITHUB_OUTPUT

      env:
        VM_PRESET: ${{ inputs.vm_preset || '80vcpu-320gb' }}
        TESTS_SIZE: ${{ inputs.tests_size || 'small,medium,large' }}
