from devtools.yamaker.modules import py_srcs
from devtools.yamaker.project import NixProject, get_project_meta_module
from devtools.yamaker import python


protobuf_module = get_project_meta_module("contrib/libs/protobuf")


def post_install(self):
    dist_files = python.extract_dist_info(self)

    # Pythonize.
    with self.yamakes["."] as pb:
        pb.to_py_library(
            PY_SRCS=py_srcs(self.dstdir),
            RESOURCE_FILES=python.prepare_resource_files(self, *dist_files),
        )
        pb.PY_REGISTER.add("google.protobuf.pyext._message")
        # replace _pb2.py sources from wheel with the files generated by our build system
        pb.PEERDIR.add(f"{protobuf_module.protobuf.arcdir}/builtin_proto/protos_from_protobuf")
        pb.PEERDIR.add(f"{protobuf_module.protobuf.arcdir}/builtin_proto/protos_from_protoc")


python_protobuf = NixProject(
    owners=["g:python-contrib"],
    arcdir="contrib/python/protobuf/py3",
    nixattr=python.make_nixattr("protobuf"),
    copy_sources=["google/**/*.py"],
    copy_sources_except=["google/**/*_pb2.py"],
    put_with={
        f"_api_implementation.cpython-{python._VERSION_DOTLESS}-x86_64-linux-gnu": {
            f"_message.cpython-{python._VERSION_DOTLESS}-x86_64-linux-gnu",
        },
    },
    build_install_subdir=python.BUILD_INSTALL_SUBDIR,
    post_build=protobuf_module.protobuf.post_build,
    post_install=post_install,
)
