syntax = "proto2";

package backup;

import "cloud/tasks/persistence/config/config.proto";

option go_package = "github.com/ydb-platform/nbs/cloud/disk_manager/internal/pkg/dataplane/backup/config";

////////////////////////////////////////////////////////////////////////////////

message SnapshotStorageBackupConfig {
    required persistence.S3Config S3Config = 1;
    required string S3Bucket = 2;
    optional string S3KeyPrefix = 3;
    optional string BackupChunksTaskScheduleInterval = 4 [default = "10s"];
}
