syntax = "proto2";

package backup;

import "cloud/tasks/persistence/config/config.proto";

option go_package = "github.com/ydb-platform/nbs/cloud/disk_manager/internal/pkg/dataplane/backup/config";

////////////////////////////////////////////////////////////////////////////////

message SnapshotStorageBackupConfig {
    required persistence.S3Config S3Config = 1;
    required string S3Bucket = 2;
    optional string S3KeyPrefix = 3;
    optional string BackupChunksTaskScheduleInterval = 4 [default = "10s"];
    // Number of chunks put into backup_queue in one transaction.
    optional uint32 EnqueueBatchSize = 5 [default = 1000];
    // Number of chunks copied by one dataplane.BackupChunks iteration.
    optional uint32 BackupChunksBatchSize = 6 [default = 100];
    optional uint32 BackupChunksWorkerCount = 7 [default = 10];
}
