# Generated by devtools/yamaker from nixpkgs 24.05.

LIBRARY()

LICENSE(
    GPL-2.0-or-later WITH Linux-syscall-note AND
    LGPL-2.0-or-later AND
    LGPL-2.1-or-later AND
    MIT
)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

SUBSCRIBER(
    g:cpp-contrib
    g:yt
)

VERSION(2026-02-27)

ORIGINAL_SOURCE(https://github.com/compudj/librseq/archive/b67e281c2e0b4e1081e66ced6ec4f57844de0e6a.tar.gz)

PEERDIR(
    contrib/libs/libc_compat
)

ADDINCL(
    GLOBAL contrib/libs/librseq/include
    contrib/libs/librseq/src
)

NO_COMPILER_WARNINGS()

NO_RUNTIME()

CFLAGS(
    -DHAVE_CONFIG_H
)

SRCS(
    src/rseq-mempool.c
    src/rseq.c
    src/smp.c
)

END()
