// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.0
// source: cloud/blockstore/tools/common/go/cms/proto/console_config.proto

package kikimr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TConfigItem_EKind int32

const (
	TConfigItem_NamedConfigsItem TConfigItem_EKind = 100
)

// Enum value maps for TConfigItem_EKind.
var (
	TConfigItem_EKind_name = map[int32]string{
		100: "NamedConfigsItem",
	}
	TConfigItem_EKind_value = map[string]int32{
		"NamedConfigsItem": 100,
	}
)

func (x TConfigItem_EKind) Enum() *TConfigItem_EKind {
	p := new(TConfigItem_EKind)
	*p = x
	return p
}

func (x TConfigItem_EKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TConfigItem_EKind) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_enumTypes[0].Descriptor()
}

func (TConfigItem_EKind) Type() protoreflect.EnumType {
	return &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_enumTypes[0]
}

func (x TConfigItem_EKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TConfigItem_EKind) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TConfigItem_EKind(num)
	return nil
}

// Deprecated: Use TConfigItem_EKind.Descriptor instead.
func (TConfigItem_EKind) EnumDescriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{11, 0}
}

type TConfigItem_EMergeStrategy int32

const (
	TConfigItem_OVERWRITE                TConfigItem_EMergeStrategy = 1
	TConfigItem_MERGE                    TConfigItem_EMergeStrategy = 2
	TConfigItem_MERGE_OVERWRITE_REPEATED TConfigItem_EMergeStrategy = 3
)

// Enum value maps for TConfigItem_EMergeStrategy.
var (
	TConfigItem_EMergeStrategy_name = map[int32]string{
		1: "OVERWRITE",
		2: "MERGE",
		3: "MERGE_OVERWRITE_REPEATED",
	}
	TConfigItem_EMergeStrategy_value = map[string]int32{
		"OVERWRITE":                1,
		"MERGE":                    2,
		"MERGE_OVERWRITE_REPEATED": 3,
	}
)

func (x TConfigItem_EMergeStrategy) Enum() *TConfigItem_EMergeStrategy {
	p := new(TConfigItem_EMergeStrategy)
	*p = x
	return p
}

func (x TConfigItem_EMergeStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TConfigItem_EMergeStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_enumTypes[1].Descriptor()
}

func (TConfigItem_EMergeStrategy) Type() protoreflect.EnumType {
	return &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_enumTypes[1]
}

func (x TConfigItem_EMergeStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TConfigItem_EMergeStrategy) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TConfigItem_EMergeStrategy(num)
	return nil
}

// Deprecated: Use TConfigItem_EMergeStrategy.Descriptor instead.
func (TConfigItem_EMergeStrategy) EnumDescriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{11, 1}
}

type TConfigItemId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         *uint64 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Generation *uint64 `protobuf:"varint,2,opt,name=Generation" json:"Generation,omitempty"`
}

func (x *TConfigItemId) Reset() {
	*x = TConfigItemId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TConfigItemId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TConfigItemId) ProtoMessage() {}

func (x *TConfigItemId) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TConfigItemId.ProtoReflect.Descriptor instead.
func (*TConfigItemId) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{0}
}

func (x *TConfigItemId) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *TConfigItemId) GetGeneration() uint64 {
	if x != nil && x.Generation != nil {
		return *x.Generation
	}
	return 0
}

type TItemIds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []uint64 `protobuf:"varint,1,rep,name=Ids" json:"Ids,omitempty"`
}

func (x *TItemIds) Reset() {
	*x = TItemIds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TItemIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TItemIds) ProtoMessage() {}

func (x *TItemIds) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TItemIds.ProtoReflect.Descriptor instead.
func (*TItemIds) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{1}
}

func (x *TItemIds) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type TNodeIds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []uint32 `protobuf:"varint,1,rep,name=Nodes" json:"Nodes,omitempty"`
}

func (x *TNodeIds) Reset() {
	*x = TNodeIds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TNodeIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TNodeIds) ProtoMessage() {}

func (x *TNodeIds) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TNodeIds.ProtoReflect.Descriptor instead.
func (*TNodeIds) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{2}
}

func (x *TNodeIds) GetNodes() []uint32 {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type THosts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hosts []string `protobuf:"bytes,1,rep,name=Hosts" json:"Hosts,omitempty"`
}

func (x *THosts) Reset() {
	*x = THosts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *THosts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*THosts) ProtoMessage() {}

func (x *THosts) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use THosts.ProtoReflect.Descriptor instead.
func (*THosts) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{3}
}

func (x *THosts) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type TTenants struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenants []string `protobuf:"bytes,1,rep,name=Tenants" json:"Tenants,omitempty"`
}

func (x *TTenants) Reset() {
	*x = TTenants{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TTenants) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTenants) ProtoMessage() {}

func (x *TTenants) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTenants.ProtoReflect.Descriptor instead.
func (*TTenants) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{4}
}

func (x *TTenants) GetTenants() []string {
	if x != nil {
		return x.Tenants
	}
	return nil
}

type TNodeTypes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeTypes []string `protobuf:"bytes,1,rep,name=NodeTypes" json:"NodeTypes,omitempty"`
}

func (x *TNodeTypes) Reset() {
	*x = TNodeTypes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TNodeTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TNodeTypes) ProtoMessage() {}

func (x *TNodeTypes) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TNodeTypes.ProtoReflect.Descriptor instead.
func (*TNodeTypes) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{5}
}

func (x *TNodeTypes) GetNodeTypes() []string {
	if x != nil {
		return x.NodeTypes
	}
	return nil
}

type TTenantAndNodeType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant   *string `protobuf:"bytes,1,opt,name=Tenant" json:"Tenant,omitempty"`
	NodeType *string `protobuf:"bytes,2,opt,name=NodeType" json:"NodeType,omitempty"`
}

func (x *TTenantAndNodeType) Reset() {
	*x = TTenantAndNodeType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TTenantAndNodeType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTenantAndNodeType) ProtoMessage() {}

func (x *TTenantAndNodeType) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTenantAndNodeType.ProtoReflect.Descriptor instead.
func (*TTenantAndNodeType) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{6}
}

func (x *TTenantAndNodeType) GetTenant() string {
	if x != nil && x.Tenant != nil {
		return *x.Tenant
	}
	return ""
}

func (x *TTenantAndNodeType) GetNodeType() string {
	if x != nil && x.NodeType != nil {
		return *x.NodeType
	}
	return ""
}

type TTenantAndNodeTypes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantAndNodeTypes []*TTenantAndNodeType `protobuf:"bytes,1,rep,name=TenantAndNodeTypes" json:"TenantAndNodeTypes,omitempty"`
}

func (x *TTenantAndNodeTypes) Reset() {
	*x = TTenantAndNodeTypes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TTenantAndNodeTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTenantAndNodeTypes) ProtoMessage() {}

func (x *TTenantAndNodeTypes) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTenantAndNodeTypes.ProtoReflect.Descriptor instead.
func (*TTenantAndNodeTypes) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{7}
}

func (x *TTenantAndNodeTypes) GetTenantAndNodeTypes() []*TTenantAndNodeType {
	if x != nil {
		return x.TenantAndNodeTypes
	}
	return nil
}

type TCookies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cookies []string `protobuf:"bytes,1,rep,name=Cookies" json:"Cookies,omitempty"`
}

func (x *TCookies) Reset() {
	*x = TCookies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TCookies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCookies) ProtoMessage() {}

func (x *TCookies) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCookies.ProtoReflect.Descriptor instead.
func (*TCookies) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{8}
}

func (x *TCookies) GetCookies() []string {
	if x != nil {
		return x.Cookies
	}
	return nil
}

type TUsageScope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Filter:
	//	*TUsageScope_NodeFilter
	//	*TUsageScope_HostFilter
	//	*TUsageScope_TenantAndNodeTypeFilter
	Filter isTUsageScope_Filter `protobuf_oneof:"Filter"`
}

func (x *TUsageScope) Reset() {
	*x = TUsageScope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TUsageScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TUsageScope) ProtoMessage() {}

func (x *TUsageScope) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TUsageScope.ProtoReflect.Descriptor instead.
func (*TUsageScope) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{9}
}

func (m *TUsageScope) GetFilter() isTUsageScope_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (x *TUsageScope) GetNodeFilter() *TNodeIds {
	if x, ok := x.GetFilter().(*TUsageScope_NodeFilter); ok {
		return x.NodeFilter
	}
	return nil
}

func (x *TUsageScope) GetHostFilter() *THosts {
	if x, ok := x.GetFilter().(*TUsageScope_HostFilter); ok {
		return x.HostFilter
	}
	return nil
}

func (x *TUsageScope) GetTenantAndNodeTypeFilter() *TTenantAndNodeType {
	if x, ok := x.GetFilter().(*TUsageScope_TenantAndNodeTypeFilter); ok {
		return x.TenantAndNodeTypeFilter
	}
	return nil
}

type isTUsageScope_Filter interface {
	isTUsageScope_Filter()
}

type TUsageScope_NodeFilter struct {
	NodeFilter *TNodeIds `protobuf:"bytes,1,opt,name=NodeFilter,oneof"`
}

type TUsageScope_HostFilter struct {
	HostFilter *THosts `protobuf:"bytes,2,opt,name=HostFilter,oneof"`
}

type TUsageScope_TenantAndNodeTypeFilter struct {
	TenantAndNodeTypeFilter *TTenantAndNodeType `protobuf:"bytes,3,opt,name=TenantAndNodeTypeFilter,oneof"`
}

func (*TUsageScope_NodeFilter) isTUsageScope_Filter() {}

func (*TUsageScope_HostFilter) isTUsageScope_Filter() {}

func (*TUsageScope_TenantAndNodeTypeFilter) isTUsageScope_Filter() {}

type TNodeAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId   *uint32 `protobuf:"varint,1,opt,name=NodeId" json:"NodeId,omitempty"`
	Host     *string `protobuf:"bytes,2,opt,name=Host" json:"Host,omitempty"`
	Tenant   *string `protobuf:"bytes,3,opt,name=Tenant" json:"Tenant,omitempty"`
	NodeType *string `protobuf:"bytes,4,opt,name=NodeType" json:"NodeType,omitempty"`
}

func (x *TNodeAttributes) Reset() {
	*x = TNodeAttributes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TNodeAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TNodeAttributes) ProtoMessage() {}

func (x *TNodeAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TNodeAttributes.ProtoReflect.Descriptor instead.
func (*TNodeAttributes) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{10}
}

func (x *TNodeAttributes) GetNodeId() uint32 {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return 0
}

func (x *TNodeAttributes) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

func (x *TNodeAttributes) GetTenant() string {
	if x != nil && x.Tenant != nil {
		return *x.Tenant
	}
	return ""
}

func (x *TNodeAttributes) GetNodeType() string {
	if x != nil && x.NodeType != nil {
		return *x.NodeType
	}
	return ""
}

type TConfigItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            *TConfigItemId `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Kind          *uint32        `protobuf:"varint,2,opt,name=Kind" json:"Kind,omitempty"`
	Config        *TAppConfig    `protobuf:"bytes,3,opt,name=Config" json:"Config,omitempty"`
	UsageScope    *TUsageScope   `protobuf:"bytes,4,opt,name=UsageScope" json:"UsageScope,omitempty"`
	Order         *uint32        `protobuf:"varint,5,opt,name=Order" json:"Order,omitempty"`
	MergeStrategy *uint32        `protobuf:"varint,6,opt,name=MergeStrategy" json:"MergeStrategy,omitempty"`
	Cookie        *string        `protobuf:"bytes,7,opt,name=Cookie" json:"Cookie,omitempty"`
}

func (x *TConfigItem) Reset() {
	*x = TConfigItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TConfigItem) ProtoMessage() {}

func (x *TConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TConfigItem.ProtoReflect.Descriptor instead.
func (*TConfigItem) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{11}
}

func (x *TConfigItem) GetId() *TConfigItemId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TConfigItem) GetKind() uint32 {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return 0
}

func (x *TConfigItem) GetConfig() *TAppConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *TConfigItem) GetUsageScope() *TUsageScope {
	if x != nil {
		return x.UsageScope
	}
	return nil
}

func (x *TConfigItem) GetOrder() uint32 {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return 0
}

func (x *TConfigItem) GetMergeStrategy() uint32 {
	if x != nil && x.MergeStrategy != nil {
		return *x.MergeStrategy
	}
	return 0
}

func (x *TConfigItem) GetCookie() string {
	if x != nil && x.Cookie != nil {
		return *x.Cookie
	}
	return ""
}

type TAddConfigItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigItem      *TConfigItem `protobuf:"bytes,1,opt,name=ConfigItem" json:"ConfigItem,omitempty"`
	EnableAutoSplit *bool        `protobuf:"varint,2,opt,name=EnableAutoSplit" json:"EnableAutoSplit,omitempty"`
}

func (x *TAddConfigItem) Reset() {
	*x = TAddConfigItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TAddConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TAddConfigItem) ProtoMessage() {}

func (x *TAddConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TAddConfigItem.ProtoReflect.Descriptor instead.
func (*TAddConfigItem) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{12}
}

func (x *TAddConfigItem) GetConfigItem() *TConfigItem {
	if x != nil {
		return x.ConfigItem
	}
	return nil
}

func (x *TAddConfigItem) GetEnableAutoSplit() bool {
	if x != nil && x.EnableAutoSplit != nil {
		return *x.EnableAutoSplit
	}
	return false
}

type TRemoveConfigItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigItemId *TConfigItemId `protobuf:"bytes,1,opt,name=ConfigItemId" json:"ConfigItemId,omitempty"`
}

func (x *TRemoveConfigItem) Reset() {
	*x = TRemoveConfigItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TRemoveConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TRemoveConfigItem) ProtoMessage() {}

func (x *TRemoveConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TRemoveConfigItem.ProtoReflect.Descriptor instead.
func (*TRemoveConfigItem) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{13}
}

func (x *TRemoveConfigItem) GetConfigItemId() *TConfigItemId {
	if x != nil {
		return x.ConfigItemId
	}
	return nil
}

type TRemoveConfigItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Filter:
	//	*TRemoveConfigItems_CookieFilter
	Filter isTRemoveConfigItems_Filter `protobuf_oneof:"Filter"`
}

func (x *TRemoveConfigItems) Reset() {
	*x = TRemoveConfigItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TRemoveConfigItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TRemoveConfigItems) ProtoMessage() {}

func (x *TRemoveConfigItems) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TRemoveConfigItems.ProtoReflect.Descriptor instead.
func (*TRemoveConfigItems) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{14}
}

func (m *TRemoveConfigItems) GetFilter() isTRemoveConfigItems_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (x *TRemoveConfigItems) GetCookieFilter() *TCookies {
	if x, ok := x.GetFilter().(*TRemoveConfigItems_CookieFilter); ok {
		return x.CookieFilter
	}
	return nil
}

type isTRemoveConfigItems_Filter interface {
	isTRemoveConfigItems_Filter()
}

type TRemoveConfigItems_CookieFilter struct {
	CookieFilter *TCookies `protobuf:"bytes,1,opt,name=CookieFilter,oneof"`
}

func (*TRemoveConfigItems_CookieFilter) isTRemoveConfigItems_Filter() {}

type TModifyConfigItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigItem *TConfigItem `protobuf:"bytes,1,opt,name=ConfigItem" json:"ConfigItem,omitempty"`
}

func (x *TModifyConfigItem) Reset() {
	*x = TModifyConfigItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TModifyConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TModifyConfigItem) ProtoMessage() {}

func (x *TModifyConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TModifyConfigItem.ProtoReflect.Descriptor instead.
func (*TModifyConfigItem) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{15}
}

func (x *TModifyConfigItem) GetConfigItem() *TConfigItem {
	if x != nil {
		return x.ConfigItem
	}
	return nil
}

type TConfigureAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//	*TConfigureAction_AddConfigItem
	//	*TConfigureAction_RemoveConfigItem
	//	*TConfigureAction_ModifyConfigItem
	//	*TConfigureAction_RemoveConfigItems
	Action isTConfigureAction_Action `protobuf_oneof:"Action"`
}

func (x *TConfigureAction) Reset() {
	*x = TConfigureAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TConfigureAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TConfigureAction) ProtoMessage() {}

func (x *TConfigureAction) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TConfigureAction.ProtoReflect.Descriptor instead.
func (*TConfigureAction) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{16}
}

func (m *TConfigureAction) GetAction() isTConfigureAction_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *TConfigureAction) GetAddConfigItem() *TAddConfigItem {
	if x, ok := x.GetAction().(*TConfigureAction_AddConfigItem); ok {
		return x.AddConfigItem
	}
	return nil
}

func (x *TConfigureAction) GetRemoveConfigItem() *TRemoveConfigItem {
	if x, ok := x.GetAction().(*TConfigureAction_RemoveConfigItem); ok {
		return x.RemoveConfigItem
	}
	return nil
}

func (x *TConfigureAction) GetModifyConfigItem() *TModifyConfigItem {
	if x, ok := x.GetAction().(*TConfigureAction_ModifyConfigItem); ok {
		return x.ModifyConfigItem
	}
	return nil
}

func (x *TConfigureAction) GetRemoveConfigItems() *TRemoveConfigItems {
	if x, ok := x.GetAction().(*TConfigureAction_RemoveConfigItems); ok {
		return x.RemoveConfigItems
	}
	return nil
}

type isTConfigureAction_Action interface {
	isTConfigureAction_Action()
}

type TConfigureAction_AddConfigItem struct {
	AddConfigItem *TAddConfigItem `protobuf:"bytes,1,opt,name=AddConfigItem,oneof"`
}

type TConfigureAction_RemoveConfigItem struct {
	RemoveConfigItem *TRemoveConfigItem `protobuf:"bytes,2,opt,name=RemoveConfigItem,oneof"`
}

type TConfigureAction_ModifyConfigItem struct {
	ModifyConfigItem *TModifyConfigItem `protobuf:"bytes,3,opt,name=ModifyConfigItem,oneof"`
}

type TConfigureAction_RemoveConfigItems struct {
	RemoveConfigItems *TRemoveConfigItems `protobuf:"bytes,4,opt,name=RemoveConfigItems,oneof"`
}

func (*TConfigureAction_AddConfigItem) isTConfigureAction_Action() {}

func (*TConfigureAction_RemoveConfigItem) isTConfigureAction_Action() {}

func (*TConfigureAction_ModifyConfigItem) isTConfigureAction_Action() {}

func (*TConfigureAction_RemoveConfigItems) isTConfigureAction_Action() {}

type TConfigureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actions             []*TConfigureAction `protobuf:"bytes,1,rep,name=Actions" json:"Actions,omitempty"`
	DryRun              *bool               `protobuf:"varint,2,opt,name=DryRun" json:"DryRun,omitempty"`
	FillAffectedConfigs *bool               `protobuf:"varint,3,opt,name=FillAffectedConfigs" json:"FillAffectedConfigs,omitempty"`
}

func (x *TConfigureRequest) Reset() {
	*x = TConfigureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TConfigureRequest) ProtoMessage() {}

func (x *TConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TConfigureRequest.ProtoReflect.Descriptor instead.
func (*TConfigureRequest) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{17}
}

func (x *TConfigureRequest) GetActions() []*TConfigureAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *TConfigureRequest) GetDryRun() bool {
	if x != nil && x.DryRun != nil {
		return *x.DryRun
	}
	return false
}

func (x *TConfigureRequest) GetFillAffectedConfigs() bool {
	if x != nil && x.FillAffectedConfigs != nil {
		return *x.FillAffectedConfigs
	}
	return false
}

type TConfigureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status          *TStatus                              `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
	AddedItemIds    []uint64                              `protobuf:"varint,2,rep,name=AddedItemIds" json:"AddedItemIds,omitempty"`
	AffectedConfigs []*TConfigureResponse_TAffectedConfig `protobuf:"bytes,3,rep,name=AffectedConfigs" json:"AffectedConfigs,omitempty"`
}

func (x *TConfigureResponse) Reset() {
	*x = TConfigureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TConfigureResponse) ProtoMessage() {}

func (x *TConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TConfigureResponse.ProtoReflect.Descriptor instead.
func (*TConfigureResponse) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{18}
}

func (x *TConfigureResponse) GetStatus() *TStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TConfigureResponse) GetAddedItemIds() []uint64 {
	if x != nil {
		return x.AddedItemIds
	}
	return nil
}

func (x *TConfigureResponse) GetAffectedConfigs() []*TConfigureResponse_TAffectedConfig {
	if x != nil {
		return x.AffectedConfigs
	}
	return nil
}

type TGetConfigItemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemIds                 []uint64             `protobuf:"varint,1,rep,name=ItemIds" json:"ItemIds,omitempty"`
	NodeFilter              *TNodeIds            `protobuf:"bytes,2,opt,name=NodeFilter" json:"NodeFilter,omitempty"`
	HostFilter              *THosts              `protobuf:"bytes,3,opt,name=HostFilter" json:"HostFilter,omitempty"`
	TenantFilter            *TTenants            `protobuf:"bytes,4,opt,name=TenantFilter" json:"TenantFilter,omitempty"`
	NodeTypeFilter          *TNodeTypes          `protobuf:"bytes,5,opt,name=NodeTypeFilter" json:"NodeTypeFilter,omitempty"`
	TenantAndNodeTypeFilter *TTenantAndNodeTypes `protobuf:"bytes,6,opt,name=TenantAndNodeTypeFilter" json:"TenantAndNodeTypeFilter,omitempty"`
	UsageScopes             []*TUsageScope       `protobuf:"bytes,7,rep,name=UsageScopes" json:"UsageScopes,omitempty"`
	CookieFilter            *TCookies            `protobuf:"bytes,8,opt,name=CookieFilter" json:"CookieFilter,omitempty"`
	ItemKinds               []uint32             `protobuf:"varint,10,rep,name=ItemKinds" json:"ItemKinds,omitempty"`
}

func (x *TGetConfigItemsRequest) Reset() {
	*x = TGetConfigItemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TGetConfigItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TGetConfigItemsRequest) ProtoMessage() {}

func (x *TGetConfigItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TGetConfigItemsRequest.ProtoReflect.Descriptor instead.
func (*TGetConfigItemsRequest) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{19}
}

func (x *TGetConfigItemsRequest) GetItemIds() []uint64 {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

func (x *TGetConfigItemsRequest) GetNodeFilter() *TNodeIds {
	if x != nil {
		return x.NodeFilter
	}
	return nil
}

func (x *TGetConfigItemsRequest) GetHostFilter() *THosts {
	if x != nil {
		return x.HostFilter
	}
	return nil
}

func (x *TGetConfigItemsRequest) GetTenantFilter() *TTenants {
	if x != nil {
		return x.TenantFilter
	}
	return nil
}

func (x *TGetConfigItemsRequest) GetNodeTypeFilter() *TNodeTypes {
	if x != nil {
		return x.NodeTypeFilter
	}
	return nil
}

func (x *TGetConfigItemsRequest) GetTenantAndNodeTypeFilter() *TTenantAndNodeTypes {
	if x != nil {
		return x.TenantAndNodeTypeFilter
	}
	return nil
}

func (x *TGetConfigItemsRequest) GetUsageScopes() []*TUsageScope {
	if x != nil {
		return x.UsageScopes
	}
	return nil
}

func (x *TGetConfigItemsRequest) GetCookieFilter() *TCookies {
	if x != nil {
		return x.CookieFilter
	}
	return nil
}

func (x *TGetConfigItemsRequest) GetItemKinds() []uint32 {
	if x != nil {
		return x.ItemKinds
	}
	return nil
}

type TGetConfigItemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      *TStatus       `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
	ConfigItems []*TConfigItem `protobuf:"bytes,2,rep,name=ConfigItems" json:"ConfigItems,omitempty"`
}

func (x *TGetConfigItemsResponse) Reset() {
	*x = TGetConfigItemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TGetConfigItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TGetConfigItemsResponse) ProtoMessage() {}

func (x *TGetConfigItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TGetConfigItemsResponse.ProtoReflect.Descriptor instead.
func (*TGetConfigItemsResponse) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{20}
}

func (x *TGetConfigItemsResponse) GetStatus() *TStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TGetConfigItemsResponse) GetConfigItems() []*TConfigItem {
	if x != nil {
		return x.ConfigItems
	}
	return nil
}

type TGetNodeConfigItemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node      *TNodeAttributes `protobuf:"bytes,1,opt,name=Node" json:"Node,omitempty"`
	ItemKinds []uint32         `protobuf:"varint,2,rep,name=ItemKinds" json:"ItemKinds,omitempty"`
}

func (x *TGetNodeConfigItemsRequest) Reset() {
	*x = TGetNodeConfigItemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TGetNodeConfigItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TGetNodeConfigItemsRequest) ProtoMessage() {}

func (x *TGetNodeConfigItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TGetNodeConfigItemsRequest.ProtoReflect.Descriptor instead.
func (*TGetNodeConfigItemsRequest) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{21}
}

func (x *TGetNodeConfigItemsRequest) GetNode() *TNodeAttributes {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *TGetNodeConfigItemsRequest) GetItemKinds() []uint32 {
	if x != nil {
		return x.ItemKinds
	}
	return nil
}

type TGetNodeConfigItemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      *TStatus       `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
	ConfigItems []*TConfigItem `protobuf:"bytes,2,rep,name=ConfigItems" json:"ConfigItems,omitempty"`
}

func (x *TGetNodeConfigItemsResponse) Reset() {
	*x = TGetNodeConfigItemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TGetNodeConfigItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TGetNodeConfigItemsResponse) ProtoMessage() {}

func (x *TGetNodeConfigItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TGetNodeConfigItemsResponse.ProtoReflect.Descriptor instead.
func (*TGetNodeConfigItemsResponse) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{22}
}

func (x *TGetNodeConfigItemsResponse) GetStatus() *TStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TGetNodeConfigItemsResponse) GetConfigItems() []*TConfigItem {
	if x != nil {
		return x.ConfigItems
	}
	return nil
}

type TGetNodeConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node      *TNodeAttributes `protobuf:"bytes,1,opt,name=Node" json:"Node,omitempty"`
	ItemKinds []uint32         `protobuf:"varint,2,rep,name=ItemKinds" json:"ItemKinds,omitempty"`
}

func (x *TGetNodeConfigRequest) Reset() {
	*x = TGetNodeConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TGetNodeConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TGetNodeConfigRequest) ProtoMessage() {}

func (x *TGetNodeConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TGetNodeConfigRequest.ProtoReflect.Descriptor instead.
func (*TGetNodeConfigRequest) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{23}
}

func (x *TGetNodeConfigRequest) GetNode() *TNodeAttributes {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *TGetNodeConfigRequest) GetItemKinds() []uint32 {
	if x != nil {
		return x.ItemKinds
	}
	return nil
}

type TGetNodeConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *TStatus    `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
	Config *TAppConfig `protobuf:"bytes,2,opt,name=Config" json:"Config,omitempty"`
}

func (x *TGetNodeConfigResponse) Reset() {
	*x = TGetNodeConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TGetNodeConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TGetNodeConfigResponse) ProtoMessage() {}

func (x *TGetNodeConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TGetNodeConfigResponse.ProtoReflect.Descriptor instead.
func (*TGetNodeConfigResponse) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{24}
}

func (x *TGetNodeConfigResponse) GetStatus() *TStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TGetNodeConfigResponse) GetConfig() *TAppConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type TConfigsConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UsageScopeRestrictions *TConfigsConfig_TUsageScopeRestrictions `protobuf:"bytes,1,opt,name=UsageScopeRestrictions" json:"UsageScopeRestrictions,omitempty"`
}

func (x *TConfigsConfig) Reset() {
	*x = TConfigsConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TConfigsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TConfigsConfig) ProtoMessage() {}

func (x *TConfigsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TConfigsConfig.ProtoReflect.Descriptor instead.
func (*TConfigsConfig) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{25}
}

func (x *TConfigsConfig) GetUsageScopeRestrictions() *TConfigsConfig_TUsageScopeRestrictions {
	if x != nil {
		return x.UsageScopeRestrictions
	}
	return nil
}

type TConfigureResponse_TAffectedConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant    *string     `protobuf:"bytes,1,opt,name=Tenant" json:"Tenant,omitempty"`
	NodeType  *string     `protobuf:"bytes,2,opt,name=NodeType" json:"NodeType,omitempty"`
	OldConfig *TAppConfig `protobuf:"bytes,3,opt,name=OldConfig" json:"OldConfig,omitempty"`
	NewConfig *TAppConfig `protobuf:"bytes,4,opt,name=NewConfig" json:"NewConfig,omitempty"`
}

func (x *TConfigureResponse_TAffectedConfig) Reset() {
	*x = TConfigureResponse_TAffectedConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TConfigureResponse_TAffectedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TConfigureResponse_TAffectedConfig) ProtoMessage() {}

func (x *TConfigureResponse_TAffectedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TConfigureResponse_TAffectedConfig.ProtoReflect.Descriptor instead.
func (*TConfigureResponse_TAffectedConfig) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{18, 0}
}

func (x *TConfigureResponse_TAffectedConfig) GetTenant() string {
	if x != nil && x.Tenant != nil {
		return *x.Tenant
	}
	return ""
}

func (x *TConfigureResponse_TAffectedConfig) GetNodeType() string {
	if x != nil && x.NodeType != nil {
		return *x.NodeType
	}
	return ""
}

func (x *TConfigureResponse_TAffectedConfig) GetOldConfig() *TAppConfig {
	if x != nil {
		return x.OldConfig
	}
	return nil
}

func (x *TConfigureResponse_TAffectedConfig) GetNewConfig() *TAppConfig {
	if x != nil {
		return x.NewConfig
	}
	return nil
}

type TConfigsConfig_TUsageScopeRestrictions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllowedNodeIdUsageScopeKinds    []uint32 `protobuf:"varint,1,rep,name=AllowedNodeIdUsageScopeKinds" json:"AllowedNodeIdUsageScopeKinds,omitempty"`
	AllowedHostUsageScopeKinds      []uint32 `protobuf:"varint,2,rep,name=AllowedHostUsageScopeKinds" json:"AllowedHostUsageScopeKinds,omitempty"`
	AllowedTenantUsageScopeKinds    []uint32 `protobuf:"varint,3,rep,name=AllowedTenantUsageScopeKinds" json:"AllowedTenantUsageScopeKinds,omitempty"`
	AllowedNodeTypeUsageScopeKinds  []uint32 `protobuf:"varint,4,rep,name=AllowedNodeTypeUsageScopeKinds" json:"AllowedNodeTypeUsageScopeKinds,omitempty"`
	DisallowedDomainUsageScopeKinds []uint32 `protobuf:"varint,5,rep,name=DisallowedDomainUsageScopeKinds" json:"DisallowedDomainUsageScopeKinds,omitempty"`
}

func (x *TConfigsConfig_TUsageScopeRestrictions) Reset() {
	*x = TConfigsConfig_TUsageScopeRestrictions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TConfigsConfig_TUsageScopeRestrictions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TConfigsConfig_TUsageScopeRestrictions) ProtoMessage() {}

func (x *TConfigsConfig_TUsageScopeRestrictions) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TConfigsConfig_TUsageScopeRestrictions.ProtoReflect.Descriptor instead.
func (*TConfigsConfig_TUsageScopeRestrictions) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP(), []int{25, 0}
}

func (x *TConfigsConfig_TUsageScopeRestrictions) GetAllowedNodeIdUsageScopeKinds() []uint32 {
	if x != nil {
		return x.AllowedNodeIdUsageScopeKinds
	}
	return nil
}

func (x *TConfigsConfig_TUsageScopeRestrictions) GetAllowedHostUsageScopeKinds() []uint32 {
	if x != nil {
		return x.AllowedHostUsageScopeKinds
	}
	return nil
}

func (x *TConfigsConfig_TUsageScopeRestrictions) GetAllowedTenantUsageScopeKinds() []uint32 {
	if x != nil {
		return x.AllowedTenantUsageScopeKinds
	}
	return nil
}

func (x *TConfigsConfig_TUsageScopeRestrictions) GetAllowedNodeTypeUsageScopeKinds() []uint32 {
	if x != nil {
		return x.AllowedNodeTypeUsageScopeKinds
	}
	return nil
}

func (x *TConfigsConfig_TUsageScopeRestrictions) GetDisallowedDomainUsageScopeKinds() []uint32 {
	if x != nil {
		return x.DisallowedDomainUsageScopeKinds
	}
	return nil
}

var File_cloud_blockstore_tools_common_go_cms_proto_console_config_proto protoreflect.FileDescriptor

var file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDesc = []byte{
	0x0a, 0x3f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x67, 0x6f, 0x2f, 0x63, 0x6d, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e,
	0x73, 0x6f, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c,
	0x65, 0x1a, 0x37, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x6d, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x3d, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x74, 0x6f, 0x6f,
	0x6c, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x6d, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x5f, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x0d, 0x54, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1c, 0x0a, 0x08, 0x54, 0x49,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x04, 0x52, 0x03, 0x49, 0x64, 0x73, 0x22, 0x20, 0x0a, 0x08, 0x54, 0x4e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x05, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x1e, 0x0a, 0x06, 0x54, 0x48,
	0x6f, 0x73, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x22, 0x24, 0x0a, 0x08, 0x54, 0x54,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x73,
	0x22, 0x2a, 0x0a, 0x0a, 0x54, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0x48, 0x0a, 0x12,
	0x54, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x6f,
	0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x6f,
	0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x69, 0x0a, 0x13, 0x54, 0x54, 0x65, 0x6e, 0x61, 0x6e,
	0x74, 0x41, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x52, 0x0a,
	0x12, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x4e, 0x4b, 0x69, 0x6b,
	0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x54, 0x65, 0x6e, 0x61,
	0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x12, 0x54,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x22, 0x24, 0x0a, 0x08, 0x54, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x22, 0xed, 0x01, 0x0a, 0x0b, 0x54, 0x55, 0x73, 0x61,
	0x67, 0x65, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x4e, 0x4b,
	0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x73, 0x48, 0x00, 0x52, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x0a, 0x48, 0x6f, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d,
	0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x48,
	0x00, 0x52, 0x0a, 0x48, 0x6f, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x5e, 0x0a,
	0x17, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e,
	0x54, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x48, 0x00, 0x52, 0x17, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e,
	0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x42, 0x08, 0x0a,
	0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x71, 0x0a, 0x0f, 0x54, 0x4e, 0x6f, 0x64, 0x65,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0xfd, 0x02, 0x0a, 0x0b, 0x54,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x2d, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72,
	0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4b, 0x69, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x31, 0x0a,
	0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x54, 0x41,
	0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x3b, 0x0a, 0x0a, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f,
	0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x63, 0x6f, 0x70,
	0x65, 0x52, 0x0a, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x53, 0x74, 0x72, 0x61,
	0x74, 0x65, 0x67, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x4d, 0x65, 0x72, 0x67,
	0x65, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x6f,
	0x6b, 0x69, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x6f, 0x6f, 0x6b, 0x69,
	0x65, 0x22, 0x1d, 0x0a, 0x05, 0x45, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x10, 0x4e, 0x61,
	0x6d, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x10, 0x64,
	0x22, 0x48, 0x0a, 0x0e, 0x45, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65,
	0x67, 0x79, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x56, 0x45, 0x52, 0x57, 0x52, 0x49, 0x54, 0x45, 0x10,
	0x01, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x45, 0x52, 0x47, 0x45, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18,
	0x4d, 0x45, 0x52, 0x47, 0x45, 0x5f, 0x4f, 0x56, 0x45, 0x52, 0x57, 0x52, 0x49, 0x54, 0x45, 0x5f,
	0x52, 0x45, 0x50, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x03, 0x22, 0x77, 0x0a, 0x0e, 0x54, 0x41,
	0x64, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x3b, 0x0a, 0x0a,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c,
	0x65, 0x2e, 0x54, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x28, 0x0a, 0x0f, 0x45, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x41, 0x75, 0x74, 0x6f, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0f, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x75, 0x74, 0x6f, 0x53, 0x70,
	0x6c, 0x69, 0x74, 0x22, 0x56, 0x0a, 0x11, 0x54, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x41, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e,
	0x54, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x52, 0x0c, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x5e, 0x0a, 0x12, 0x54,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x12, 0x3e, 0x0a, 0x0c, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d,
	0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65,
	0x73, 0x48, 0x00, 0x52, 0x0c, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x42, 0x08, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x50, 0x0a, 0x11, 0x54,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x3b, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f,
	0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x22, 0xda, 0x02,
	0x0a, 0x10, 0x54, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x46, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49,
	0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x4e, 0x4b, 0x69, 0x6b,
	0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x41, 0x64, 0x64, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x48, 0x00, 0x52, 0x0d, 0x41, 0x64, 0x64,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x4f, 0x0a, 0x10, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f,
	0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x48, 0x00, 0x52, 0x10, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x4f, 0x0a, 0x10, 0x4d,
	0x6f, 0x64, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43,
	0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x48, 0x00, 0x52, 0x10, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x52, 0x0a, 0x11,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d,
	0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x48, 0x00, 0x52, 0x11, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x42, 0x08, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x99, 0x01, 0x0a, 0x11, 0x54,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x3a, 0x0a, 0x07, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f,
	0x6c, 0x65, 0x2e, 0x54, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x07, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x44, 0x72, 0x79, 0x52, 0x75, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x44, 0x72,
	0x79, 0x52, 0x75, 0x6e, 0x12, 0x30, 0x0a, 0x13, 0x46, 0x69, 0x6c, 0x6c, 0x41, 0x66, 0x66, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x13, 0x46, 0x69, 0x6c, 0x6c, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x22, 0x81, 0x03, 0x0a, 0x12, 0x54, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22,
	0x0a, 0x0c, 0x41, 0x64, 0x64, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x0c, 0x41, 0x64, 0x64, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x73, 0x12, 0x5c, 0x0a, 0x0f, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x4e, 0x4b,
	0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x54, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x0f, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73,
	0x1a, 0xb7, 0x01, 0x0a, 0x0f, 0x54, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x4f, 0x6c, 0x64, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x4e, 0x4b,
	0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x54, 0x41, 0x70, 0x70,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x09, 0x4f, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x37, 0x0a, 0x09, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x54, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x09, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0xa0, 0x04, 0x0a, 0x16, 0x54,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x73, 0x12,
	0x38, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e,
	0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x73, 0x52, 0x0a, 0x4e,
	0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x0a, 0x48, 0x6f, 0x73,
	0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54,
	0x48, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x0a, 0x48, 0x6f, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x3c, 0x0a, 0x0c, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d,
	0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x73, 0x52, 0x0c, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12,
	0x42, 0x0a, 0x0e, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d,
	0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x52, 0x0e, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x12, 0x5d, 0x0a, 0x17, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41, 0x6e, 0x64,
	0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f,
	0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41, 0x6e, 0x64,
	0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x17, 0x54, 0x65, 0x6e, 0x61, 0x6e,
	0x74, 0x41, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x12, 0x3d, 0x0a, 0x0b, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x63, 0x6f, 0x70, 0x65,
	0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d,
	0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53,
	0x63, 0x6f, 0x70, 0x65, 0x52, 0x0b, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x63, 0x6f, 0x70, 0x65,
	0x73, 0x12, 0x3c, 0x0a, 0x0c, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d,
	0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65,
	0x73, 0x52, 0x0c, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x49, 0x74, 0x65, 0x6d, 0x4b, 0x69, 0x6e, 0x64, 0x73, 0x18, 0x0a, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x09, 0x49, 0x74, 0x65, 0x6d, 0x4b, 0x69, 0x6e, 0x64, 0x73, 0x22, 0x89, 0x01,
	0x0a, 0x17, 0x54, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x4e, 0x4b, 0x69, 0x6b,
	0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3d, 0x0a, 0x0b, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65,
	0x2e, 0x54, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0b, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x6f, 0x0a, 0x1a, 0x54, 0x47, 0x65,
	0x74, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43,
	0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x52, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x49, 0x74, 0x65, 0x6d, 0x4b, 0x69, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x09, 0x49, 0x74, 0x65, 0x6d, 0x4b, 0x69, 0x6e, 0x64, 0x73, 0x22, 0x8d, 0x01, 0x0a, 0x1b, 0x54,
	0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x4e, 0x4b, 0x69,
	0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3d, 0x0a, 0x0b, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c,
	0x65, 0x2e, 0x54, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0b, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x6a, 0x0a, 0x15, 0x54, 0x47,
	0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f,
	0x6c, 0x65, 0x2e, 0x54, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x73, 0x52, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x74, 0x65, 0x6d,
	0x4b, 0x69, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x09, 0x49, 0x74, 0x65,
	0x6d, 0x4b, 0x69, 0x6e, 0x64, 0x73, 0x22, 0x7c, 0x0a, 0x16, 0x54, 0x47, 0x65, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c,
	0x65, 0x2e, 0x54, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x31, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x54, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x22, 0xf6, 0x03, 0x0a, 0x0e, 0x54, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x6e, 0x0a, 0x16, 0x55, 0x73, 0x61, 0x67, 0x65,
	0x53, 0x63, 0x6f, 0x70, 0x65, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x4e, 0x4b, 0x69, 0x6b, 0x69, 0x6d,
	0x72, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x54, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x63,
	0x6f, 0x70, 0x65, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x16, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x52, 0x65, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0xf3, 0x02, 0x0a, 0x17, 0x54, 0x55, 0x73, 0x61,
	0x67, 0x65, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x42, 0x0a, 0x1c, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x4b, 0x69,
	0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x1c, 0x41, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x63, 0x6f,
	0x70, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x73, 0x12, 0x3e, 0x0a, 0x1a, 0x41, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x63, 0x6f, 0x70, 0x65,
	0x4b, 0x69, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x1a, 0x41, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x63, 0x6f,
	0x70, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x73, 0x12, 0x42, 0x0a, 0x1c, 0x41, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x63, 0x6f,
	0x70, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x1c, 0x41,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x55, 0x73, 0x61, 0x67,
	0x65, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x73, 0x12, 0x46, 0x0a, 0x1e, 0x41,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x55, 0x73,
	0x61, 0x67, 0x65, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x1e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x4b, 0x69,
	0x6e, 0x64, 0x73, 0x12, 0x48, 0x0a, 0x1f, 0x44, 0x69, 0x73, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x64, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x63, 0x6f, 0x70,
	0x65, 0x4b, 0x69, 0x6e, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x1f, 0x44, 0x69,
	0x73, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x55, 0x73,
	0x61, 0x67, 0x65, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x73, 0x42, 0x44, 0x5a,
	0x42, 0x61, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x72,
	0x75, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x67, 0x6f, 0x2f, 0x63, 0x6d, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x6b, 0x69, 0x6b,
	0x69, 0x6d, 0x72,
}

var (
	file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescOnce sync.Once
	file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescData = file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDesc
)

func file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescGZIP() []byte {
	file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescOnce.Do(func() {
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescData)
	})
	return file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDescData
}

var file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_goTypes = []interface{}{
	(TConfigItem_EKind)(0),                         // 0: NKikimrConsole.TConfigItem.EKind
	(TConfigItem_EMergeStrategy)(0),                // 1: NKikimrConsole.TConfigItem.EMergeStrategy
	(*TConfigItemId)(nil),                          // 2: NKikimrConsole.TConfigItemId
	(*TItemIds)(nil),                               // 3: NKikimrConsole.TItemIds
	(*TNodeIds)(nil),                               // 4: NKikimrConsole.TNodeIds
	(*THosts)(nil),                                 // 5: NKikimrConsole.THosts
	(*TTenants)(nil),                               // 6: NKikimrConsole.TTenants
	(*TNodeTypes)(nil),                             // 7: NKikimrConsole.TNodeTypes
	(*TTenantAndNodeType)(nil),                     // 8: NKikimrConsole.TTenantAndNodeType
	(*TTenantAndNodeTypes)(nil),                    // 9: NKikimrConsole.TTenantAndNodeTypes
	(*TCookies)(nil),                               // 10: NKikimrConsole.TCookies
	(*TUsageScope)(nil),                            // 11: NKikimrConsole.TUsageScope
	(*TNodeAttributes)(nil),                        // 12: NKikimrConsole.TNodeAttributes
	(*TConfigItem)(nil),                            // 13: NKikimrConsole.TConfigItem
	(*TAddConfigItem)(nil),                         // 14: NKikimrConsole.TAddConfigItem
	(*TRemoveConfigItem)(nil),                      // 15: NKikimrConsole.TRemoveConfigItem
	(*TRemoveConfigItems)(nil),                     // 16: NKikimrConsole.TRemoveConfigItems
	(*TModifyConfigItem)(nil),                      // 17: NKikimrConsole.TModifyConfigItem
	(*TConfigureAction)(nil),                       // 18: NKikimrConsole.TConfigureAction
	(*TConfigureRequest)(nil),                      // 19: NKikimrConsole.TConfigureRequest
	(*TConfigureResponse)(nil),                     // 20: NKikimrConsole.TConfigureResponse
	(*TGetConfigItemsRequest)(nil),                 // 21: NKikimrConsole.TGetConfigItemsRequest
	(*TGetConfigItemsResponse)(nil),                // 22: NKikimrConsole.TGetConfigItemsResponse
	(*TGetNodeConfigItemsRequest)(nil),             // 23: NKikimrConsole.TGetNodeConfigItemsRequest
	(*TGetNodeConfigItemsResponse)(nil),            // 24: NKikimrConsole.TGetNodeConfigItemsResponse
	(*TGetNodeConfigRequest)(nil),                  // 25: NKikimrConsole.TGetNodeConfigRequest
	(*TGetNodeConfigResponse)(nil),                 // 26: NKikimrConsole.TGetNodeConfigResponse
	(*TConfigsConfig)(nil),                         // 27: NKikimrConsole.TConfigsConfig
	(*TConfigureResponse_TAffectedConfig)(nil),     // 28: NKikimrConsole.TConfigureResponse.TAffectedConfig
	(*TConfigsConfig_TUsageScopeRestrictions)(nil), // 29: NKikimrConsole.TConfigsConfig.TUsageScopeRestrictions
	(*TAppConfig)(nil),                             // 30: NKikimrConfig.TAppConfig
	(*TStatus)(nil),                                // 31: NKikimrConsole.TStatus
}
var file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_depIdxs = []int32{
	8,  // 0: NKikimrConsole.TTenantAndNodeTypes.TenantAndNodeTypes:type_name -> NKikimrConsole.TTenantAndNodeType
	4,  // 1: NKikimrConsole.TUsageScope.NodeFilter:type_name -> NKikimrConsole.TNodeIds
	5,  // 2: NKikimrConsole.TUsageScope.HostFilter:type_name -> NKikimrConsole.THosts
	8,  // 3: NKikimrConsole.TUsageScope.TenantAndNodeTypeFilter:type_name -> NKikimrConsole.TTenantAndNodeType
	2,  // 4: NKikimrConsole.TConfigItem.Id:type_name -> NKikimrConsole.TConfigItemId
	30, // 5: NKikimrConsole.TConfigItem.Config:type_name -> NKikimrConfig.TAppConfig
	11, // 6: NKikimrConsole.TConfigItem.UsageScope:type_name -> NKikimrConsole.TUsageScope
	13, // 7: NKikimrConsole.TAddConfigItem.ConfigItem:type_name -> NKikimrConsole.TConfigItem
	2,  // 8: NKikimrConsole.TRemoveConfigItem.ConfigItemId:type_name -> NKikimrConsole.TConfigItemId
	10, // 9: NKikimrConsole.TRemoveConfigItems.CookieFilter:type_name -> NKikimrConsole.TCookies
	13, // 10: NKikimrConsole.TModifyConfigItem.ConfigItem:type_name -> NKikimrConsole.TConfigItem
	14, // 11: NKikimrConsole.TConfigureAction.AddConfigItem:type_name -> NKikimrConsole.TAddConfigItem
	15, // 12: NKikimrConsole.TConfigureAction.RemoveConfigItem:type_name -> NKikimrConsole.TRemoveConfigItem
	17, // 13: NKikimrConsole.TConfigureAction.ModifyConfigItem:type_name -> NKikimrConsole.TModifyConfigItem
	16, // 14: NKikimrConsole.TConfigureAction.RemoveConfigItems:type_name -> NKikimrConsole.TRemoveConfigItems
	18, // 15: NKikimrConsole.TConfigureRequest.Actions:type_name -> NKikimrConsole.TConfigureAction
	31, // 16: NKikimrConsole.TConfigureResponse.Status:type_name -> NKikimrConsole.TStatus
	28, // 17: NKikimrConsole.TConfigureResponse.AffectedConfigs:type_name -> NKikimrConsole.TConfigureResponse.TAffectedConfig
	4,  // 18: NKikimrConsole.TGetConfigItemsRequest.NodeFilter:type_name -> NKikimrConsole.TNodeIds
	5,  // 19: NKikimrConsole.TGetConfigItemsRequest.HostFilter:type_name -> NKikimrConsole.THosts
	6,  // 20: NKikimrConsole.TGetConfigItemsRequest.TenantFilter:type_name -> NKikimrConsole.TTenants
	7,  // 21: NKikimrConsole.TGetConfigItemsRequest.NodeTypeFilter:type_name -> NKikimrConsole.TNodeTypes
	9,  // 22: NKikimrConsole.TGetConfigItemsRequest.TenantAndNodeTypeFilter:type_name -> NKikimrConsole.TTenantAndNodeTypes
	11, // 23: NKikimrConsole.TGetConfigItemsRequest.UsageScopes:type_name -> NKikimrConsole.TUsageScope
	10, // 24: NKikimrConsole.TGetConfigItemsRequest.CookieFilter:type_name -> NKikimrConsole.TCookies
	31, // 25: NKikimrConsole.TGetConfigItemsResponse.Status:type_name -> NKikimrConsole.TStatus
	13, // 26: NKikimrConsole.TGetConfigItemsResponse.ConfigItems:type_name -> NKikimrConsole.TConfigItem
	12, // 27: NKikimrConsole.TGetNodeConfigItemsRequest.Node:type_name -> NKikimrConsole.TNodeAttributes
	31, // 28: NKikimrConsole.TGetNodeConfigItemsResponse.Status:type_name -> NKikimrConsole.TStatus
	13, // 29: NKikimrConsole.TGetNodeConfigItemsResponse.ConfigItems:type_name -> NKikimrConsole.TConfigItem
	12, // 30: NKikimrConsole.TGetNodeConfigRequest.Node:type_name -> NKikimrConsole.TNodeAttributes
	31, // 31: NKikimrConsole.TGetNodeConfigResponse.Status:type_name -> NKikimrConsole.TStatus
	30, // 32: NKikimrConsole.TGetNodeConfigResponse.Config:type_name -> NKikimrConfig.TAppConfig
	29, // 33: NKikimrConsole.TConfigsConfig.UsageScopeRestrictions:type_name -> NKikimrConsole.TConfigsConfig.TUsageScopeRestrictions
	30, // 34: NKikimrConsole.TConfigureResponse.TAffectedConfig.OldConfig:type_name -> NKikimrConfig.TAppConfig
	30, // 35: NKikimrConsole.TConfigureResponse.TAffectedConfig.NewConfig:type_name -> NKikimrConfig.TAppConfig
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_init() }
func file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_init() {
	if File_cloud_blockstore_tools_common_go_cms_proto_console_config_proto != nil {
		return
	}
	file_cloud_blockstore_tools_common_go_cms_proto_config_proto_init()
	file_cloud_blockstore_tools_common_go_cms_proto_console_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TConfigItemId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TItemIds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TNodeIds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*THosts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TTenants); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TNodeTypes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TTenantAndNodeType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TTenantAndNodeTypes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TCookies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TUsageScope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TNodeAttributes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TConfigItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TAddConfigItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TRemoveConfigItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TRemoveConfigItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TModifyConfigItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TConfigureAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TConfigureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TConfigureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TGetConfigItemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TGetConfigItemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TGetNodeConfigItemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TGetNodeConfigItemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TGetNodeConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TGetNodeConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TConfigsConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TConfigureResponse_TAffectedConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TConfigsConfig_TUsageScopeRestrictions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*TUsageScope_NodeFilter)(nil),
		(*TUsageScope_HostFilter)(nil),
		(*TUsageScope_TenantAndNodeTypeFilter)(nil),
	}
	file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[14].OneofWrappers = []interface{}{
		(*TRemoveConfigItems_CookieFilter)(nil),
	}
	file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes[16].OneofWrappers = []interface{}{
		(*TConfigureAction_AddConfigItem)(nil),
		(*TConfigureAction_RemoveConfigItem)(nil),
		(*TConfigureAction_ModifyConfigItem)(nil),
		(*TConfigureAction_RemoveConfigItems)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_goTypes,
		DependencyIndexes: file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_depIdxs,
		EnumInfos:         file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_enumTypes,
		MessageInfos:      file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_msgTypes,
	}.Build()
	File_cloud_blockstore_tools_common_go_cms_proto_console_config_proto = out.File
	file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_rawDesc = nil
	file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_goTypes = nil
	file_cloud_blockstore_tools_common_go_cms_proto_console_config_proto_depIdxs = nil
}
