# Generated by devtools/yamaker.

LIBRARY()

LICENSE(BSD-3-Clause)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

PEERDIR(
    contrib/libs/dpdk/lib/librte_eal
    contrib/libs/dpdk/lib/librte_kvargs
    contrib/libs/dpdk/lib/librte_pci
    contrib/libs/dpdk/lib/librte_telemetry
)

ADDINCL(
    GLOBAL contrib/libs/dpdk/config
    GLOBAL contrib/libs/dpdk/drivers/bus/pci
    GLOBAL contrib/libs/dpdk/drivers/bus/pci/linux
    contrib/libs/dpdk/lib/librte_eal
    contrib/libs/dpdk/lib/librte_eal/common
    contrib/libs/dpdk/lib/librte_eal/include
    contrib/libs/dpdk/lib/librte_eal/linux/include
    contrib/libs/dpdk/lib/librte_kvargs
    contrib/libs/dpdk/lib/librte_pci
)

NO_COMPILER_WARNINGS()

NO_RUNTIME()

CFLAGS(
    -DALLOW_EXPERIMENTAL_API
    -DALLOW_INTERNAL_API
)

SRCDIR(contrib/libs/dpdk/drivers)

SRCS(
    GLOBAL bus/pci/linux/pci_vfio.c
    GLOBAL bus/pci/pci_common.c
    GLOBAL bus/pci/pci_common_uio.c
    bus/pci/linux/pci.c
    bus/pci/linux/pci_uio.c
    bus/pci/pci_params.c
    rte_bus_pci.pmd.c
)

IF (ARCH_ARM64)
    ADDINCL(contrib/libs/dpdk/lib/librte_eal/arm/include)
ELSEIF (ARCH_X86_64)
    ADDINCL(contrib/libs/dpdk/lib/librte_eal/x86/include)
ENDIF()

END()
