/*
 * Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its contributors
 *    may be used to endorse or promote products derived from this software without
 *    specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * AOCL-LibMem Profiler - Zero Library Dependencies Version
 * Uses only raw Linux kernel syscalls - no libbpf, no libbcc, no LLVM
 */

#include <iostream>
#include <string>
#include <vector>
#include <map>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <chrono>
#include <algorithm>
#include <cstring>
#include <cstdlib>
#include <csignal>
#include <cerrno>
#include <cctype>

// POSIX/Linux system headers (standard, no library links)
#include <unistd.h>
#include <fcntl.h>
#include <getopt.h>
#include <limits.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/wait.h>
#include <sys/ioctl.h>
#include <dlfcn.h>
#include <dirent.h>
#include <elf.h>
#include <linux/bpf.h>
#include <linux/perf_event.h>

// Portability: STT_GNU_IFUNC may not be defined in older elf.h versions
#ifndef STT_GNU_IFUNC
#define STT_GNU_IFUNC 10  /* GNU extension: indirect function (IFUNC) */
#endif

// Force use of older GLIBC symbol versions for compatibility with older systems
// This significantly reduces GLIBC version requirements for better portability
// Static linking libstdc++ eliminates all GLIBCXX dependencies entirely
//
// GLIBC Compatibility Summary:
// - Main dl* functions: GLIBC 2.2.5 (dlopen, dlsym, dlclose, dlerror)
// - pthread functions: GLIBC 2.2.5-2.3.4 (from static libstdc++)
// - Remaining symbols from static libstdc++ may still require GLIBC 2.34+ on newer build systems
// - To achieve maximum compatibility, compile on an older system (e.g., Debian 10/Ubuntu 18.04)
#ifdef __GLIBC__
    #if __GLIBC__ > 2 || (__GLIBC__ == 2 && __GLIBC_MINOR__ >= 34)
        // On newer systems, force use of older symbol versions for backward compatibility
        __asm__(".symver dlopen,dlopen@GLIBC_2.2.5");
        __asm__(".symver dlclose,dlclose@GLIBC_2.2.5");
        __asm__(".symver dlsym,dlsym@GLIBC_2.2.5");
        __asm__(".symver dlerror,dlerror@GLIBC_2.2.5");
        __asm__(".symver pthread_once,pthread_once@GLIBC_2.2.5");
        __asm__(".symver __libc_start_main,__libc_start_main@GLIBC_2.2.5");
    #endif
    // __pthread_key_create appeared in GLIBC 2.3.4
    #if __GLIBC__ > 2 || (__GLIBC__ == 2 && __GLIBC_MINOR__ >= 34)
        __asm__(".symver __pthread_key_create,__pthread_key_create@GLIBC_2.3.4");
    #endif
#endif

// Embedded BPF program (generated by CMake: xxd -i profiler.bpf.o)
#include "profiler.bpf.h"

// Global flag for signal handling
static volatile sig_atomic_t g_should_exit = 0;
static std::ofstream g_output_file;
static std::ostream* g_output_stream = &std::cout;
static std::chrono::system_clock::time_point g_start_time;
static std::chrono::system_clock::time_point g_end_time;

// Track created uprobe event names and perf event fds for cleanup
static std::vector<std::string> g_probe_names;
static std::vector<int> g_perf_fds;

// Remove all tracefs uprobe events created by this process.
// Writes "-:uprobes/<probe_name>" for each tracked probe to
// /sys/kernel/debug/tracing/uprobe_events.
static void cleanup_uprobes()
{
    if (g_probe_names.empty())
        return;

    int fd = open("/sys/kernel/debug/tracing/uprobe_events",
                  O_WRONLY | O_APPEND);
    if (fd < 0)
        return;

    for (const auto &name : g_probe_names) {
        std::string cmd = "-:uprobes/" + name + "\n";
        /* best-effort: ignore write errors (probe may already be gone) */
        if (write(fd, cmd.c_str(), cmd.length()) < 0) {
            /* silence unused-result warning */
        }
    }
    close(fd);
    g_probe_names.clear();
}

// Old-style BPF map definition structure (matches profiler.bpf.c)
struct bpf_map_def {
    unsigned int type;
    unsigned int key_size;
    unsigned int value_size;
    unsigned int max_entries;
    unsigned int map_flags;
};

// BPF syscall wrapper
static inline int bpf_syscall(int cmd, union bpf_attr *attr, unsigned int size) {
    return syscall(__NR_bpf, cmd, attr, size);
}

// perf_event_open syscall wrapper
static inline int perf_event_open(struct perf_event_attr *attr, pid_t pid,
                                 int cpu, int group_fd, unsigned long flags) {
    return syscall(__NR_perf_event_open, attr, pid, cpu, group_fd, flags);
}

// BPF map creation
static int bpf_create_map(enum bpf_map_type map_type, unsigned int key_size,
                         unsigned int value_size, unsigned int max_entries) {
    union bpf_attr attr = {};
    attr.map_type = map_type;
    attr.key_size = key_size;
    attr.value_size = value_size;
    attr.max_entries = max_entries;

    int fd = bpf_syscall(BPF_MAP_CREATE, &attr, sizeof(attr));
    if (fd < 0) {
        std::cerr << "BPF_MAP_CREATE failed: " << strerror(errno) << std::endl;
    }
    return fd;
}

// BPF program loading
static int bpf_load_program(enum bpf_prog_type type, const struct bpf_insn *insns,
                           size_t insns_cnt, const char *license, char *log_buf,
                           size_t log_buf_size) {
    union bpf_attr attr = {};
    attr.prog_type = type;
    attr.insns = reinterpret_cast<uint64_t>(insns);
    attr.insn_cnt = insns_cnt;
    attr.license = reinterpret_cast<uint64_t>(license);
    attr.log_buf = reinterpret_cast<uint64_t>(log_buf);
    attr.log_size = log_buf_size;
    attr.log_level = log_buf_size > 0 ? 1 : 0;

    int fd = bpf_syscall(BPF_PROG_LOAD, &attr, sizeof(attr));
    if (fd < 0 && log_buf && log_buf_size > 0) {
        std::cerr << "BPF program load failed:\n" << log_buf << std::endl;
    }
    return fd;
}

// Get number of possible CPUs for per-CPU map handling
static int get_num_cpus() {
    static int num_cpus = 0;
    if (num_cpus > 0) return num_cpus;

    // Read from /sys/devices/system/cpu/possible
    std::ifstream cpus("/sys/devices/system/cpu/possible");
    if (cpus.is_open()) {
        std::string line;
        std::getline(cpus, line);
        // Format: "0-N" or "0,2-N" etc.
        size_t dash = line.find_last_of('-');
        if (dash != std::string::npos) {
            num_cpus = std::atoi(line.substr(dash + 1).c_str()) + 1;
        }
    }

    if (num_cpus == 0) num_cpus = 1;  // Fallback
    return num_cpus;
}

// BPF map lookup (handles per-CPU maps)
static int bpf_map_lookup_elem(int fd, const void *key, void *value) {
    union bpf_attr attr = {};
    attr.map_fd = fd;
    attr.key = reinterpret_cast<uint64_t>(key);
    attr.value = reinterpret_cast<uint64_t>(value);

    return bpf_syscall(BPF_MAP_LOOKUP_ELEM, &attr, sizeof(attr));
}

// BPF map update element
static int bpf_map_update_elem(int fd, const void *key, const void *value, uint64_t flags) {
    union bpf_attr attr = {};
    attr.map_fd = fd;
    attr.key = reinterpret_cast<uint64_t>(key);
    attr.value = reinterpret_cast<uint64_t>(value);
    attr.flags = flags;

    return bpf_syscall(BPF_MAP_UPDATE_ELEM, &attr, sizeof(attr));
}

// BPF per-CPU map lookup - sums values across all CPUs
static uint64_t bpf_map_lookup_elem_percpu_sum(int fd, const void *key) {
    int num_cpus = get_num_cpus();
    std::vector<uint64_t> values(num_cpus, 0);

    if (bpf_map_lookup_elem(fd, key, values.data()) < 0) {
        return 0;
    }

    uint64_t sum = 0;
    for (int i = 0; i < num_cpus; i++) {
        sum += values[i];
    }
    return sum;
}

// Parse alignment value string and return alignment in bytes.
// Accepts numeric values (bytes) or human-readable forms: B, KB, MB, GB.
// Returns 0 on error, sets error_msg.
static uint32_t parse_alignment_value(const std::string& input, std::string& error_msg) {
    std::string s = input;
    // Convert to uppercase
    for (auto& c : s) c = static_cast<char>(toupper(static_cast<unsigned char>(c)));

    // Strip trailing whitespace
    while (!s.empty() && isspace(static_cast<unsigned char>(s.back()))) s.pop_back();
    while (!s.empty() && isspace(static_cast<unsigned char>(s.front()))) s.erase(s.begin());

    uint64_t multiplier = 1;
    if (s.size() >= 2 && s.substr(s.size() - 2) == "GB") {
        multiplier = 1024ULL * 1024 * 1024;
        s = s.substr(0, s.size() - 2);
    } else if (s.size() >= 2 && s.substr(s.size() - 2) == "MB") {
        multiplier = 1024ULL * 1024;
        s = s.substr(0, s.size() - 2);
    } else if (s.size() >= 2 && s.substr(s.size() - 2) == "KB") {
        multiplier = 1024;
        s = s.substr(0, s.size() - 2);
    } else if (s.size() >= 1 && s.back() == 'B') {
        multiplier = 1;
        s = s.substr(0, s.size() - 1);
    }

    // Strip whitespace between number and suffix
    while (!s.empty() && isspace(static_cast<unsigned char>(s.back()))) s.pop_back();

    char* end = nullptr;
    long val = strtol(s.c_str(), &end, 10);
    if (end == s.c_str() || *end != '\0' || val <= 0) {
        error_msg = "Invalid alignment value: '" + input + "'. "
                    "Expected a number optionally followed by B, KB, MB, or GB.";
        return 0;
    }

    uint64_t alignment_bytes = static_cast<uint64_t>(val) * multiplier;

    // Check power of two
    if ((alignment_bytes & (alignment_bytes - 1)) != 0) {
        error_msg = "Alignment must be a power of two, got " + std::to_string(alignment_bytes) + " bytes.";
        return 0;
    }

    // Must fit in uint32_t for BPF map (mask = alignment - 1)
    if (alignment_bytes > 0x80000000ULL) {
        error_msg = "Alignment too large (max 2GB for BPF mask).";
        return 0;
    }

    return static_cast<uint32_t>(alignment_bytes);
}

// Return a human-readable label for alignment in bytes (e.g., "64B", "4KB").
static std::string format_alignment_label(uint32_t alignment_bytes) {
    if (alignment_bytes >= 1024 * 1024 * 1024 && alignment_bytes % (1024 * 1024 * 1024) == 0)
        return std::to_string(alignment_bytes / (1024 * 1024 * 1024)) + "GB";
    if (alignment_bytes >= 1024 * 1024 && alignment_bytes % (1024 * 1024) == 0)
        return std::to_string(alignment_bytes / (1024 * 1024)) + "MB";
    if (alignment_bytes >= 1024 && alignment_bytes % 1024 == 0)
        return std::to_string(alignment_bytes / 1024) + "KB";
    return std::to_string(alignment_bytes) + "B";
}

// Configuration structure
struct Config {
    int interval = 5;
    int pid = -1;
    std::vector<std::string> functions;
    int verbose = 0;
    std::vector<std::string> exec_args;
    int time_limit = 0;
    bool track_count_functions = false;
    std::string output_file;
    uint32_t alignment_bytes = 0;    // 0 = disabled, or alignment in bytes (must be power of 2)
    std::string alignment_label;     // Human-readable label (e.g., "64B", "4KB")
};

// Function information structure
struct FunctionInfo {
    std::string libname;
    std::string name;
    std::string symbol;
    int argSZ;
    int argSRC;
    int argDST;
    bool is_dist_function;
    uint64_t resolved_offset;
    std::string resolved_module;
    std::vector<std::string> aliases;  // List of alias function names (e.g., memcpy has alias "memmove")

    FunctionInfo(const std::string& lib, const std::string& n, const std::string& sym,
                 int sz = 3, int src = 2, int dst = 1, bool dist = true,
                 const std::vector<std::string>& alias_list = {})
        : libname(lib), name(n), symbol(sym), argSZ(sz), argSRC(src), argDST(dst),
          is_dist_function(dist), resolved_offset(0), aliases(alias_list) {}

    // Display name: shows merged functions with "+" when they share the same address
    std::string display_name() const {
        if (aliases.empty()) {
            return name;
        }
        std::string result = name;
        for (const auto& alias : aliases) {
            result += " + " + alias;
        }
        return result;
    }
};

// Loaded BPF program and map information
struct BPFProgram {
    int prog_fd;
    int perf_fd;
    std::string name;

    BPFProgram() : prog_fd(-1), perf_fd(-1) {}
};

struct BPFMap {
    int fd;
    std::string name;
    unsigned int max_entries;

    BPFMap() : fd(-1), max_entries(0) {}
};

// Global BPF objects
static std::map<std::string, BPFMap> g_maps;
static std::vector<BPFProgram> g_programs;

// Forward declarations
static void log_message(int level, int required_level, const std::string& msg);
static void print_function_alignment_stats(const std::string& func_name, uint64_t total_calls,
                                          int argSRC, int argDST, const std::string& alignment_label);
static void print_function_stats(const std::vector<FunctionInfo>& dist_funcs,
                                 const std::vector<FunctionInfo>& count_funcs,
                                 uint32_t alignment_bytes, const std::string& alignment_label,
                                 bool include_distribution);

// Signal handler
void signal_handler(int /*signum*/) {
    g_should_exit = 1;
}

// Log function
static void log_message(int level, int required_level, const std::string& msg) {
    if (level >= required_level) {
        auto now = std::chrono::system_clock::now();
        auto now_c = std::chrono::system_clock::to_time_t(now);
        *g_output_stream << std::put_time(std::localtime(&now_c), "%Y-%m-%d %H:%M:%S")
                        << " - " << msg << std::endl;
    }
}

// Minimal ELF64 loader for old-style BPF maps
class BPFLoader {
private:
    const unsigned char *elf_data;
    size_t elf_size;
    const Elf64_Ehdr *ehdr;
    const Elf64_Shdr *sections;
    const char *strtab;

    const char* get_string(size_t offset) {
        return strtab + offset;
    }

    const Elf64_Shdr* find_section(const char* name) {
        for (int i = 0; i < ehdr->e_shnum; i++) {
            const char *sec_name = get_string(sections[i].sh_name);
            if (strcmp(sec_name, name) == 0) {
                return &sections[i];
            }
        }
        return nullptr;
    }

public:
    BPFLoader(const unsigned char *data, size_t size)
        : elf_data(data), elf_size(size), ehdr(nullptr), sections(nullptr), strtab(nullptr) {

        if (size < sizeof(Elf64_Ehdr)) {
            std::cerr << "BPF loader error: Invalid ELF size" << std::endl;
            return;
        }

        ehdr = reinterpret_cast<const Elf64_Ehdr*>(elf_data);

        // Verify ELF magic
        if (memcmp(ehdr->e_ident, ELFMAG, SELFMAG) != 0) {
            std::cerr << "BPF loader error: Invalid ELF magic" << std::endl;
            ehdr = nullptr;
            return;
        }

        sections = reinterpret_cast<const Elf64_Shdr*>(elf_data + ehdr->e_shoff);

        // Find string table
        const Elf64_Shdr *shstrtab = &sections[ehdr->e_shstrndx];
        strtab = reinterpret_cast<const char*>(elf_data + shstrtab->sh_offset);
    }

    bool is_valid() const {
        return ehdr != nullptr;
    }

    bool load_maps() {
        const Elf64_Shdr *maps_sec = find_section("maps");
        if (!maps_sec) {
            std::cerr << "Maps section not found" << std::endl;
            return false;
        }

        const bpf_map_def *maps = reinterpret_cast<const bpf_map_def*>(
            elf_data + maps_sec->sh_offset);
        size_t num_maps = maps_sec->sh_size / sizeof(bpf_map_def);

        // Find symbol table to get map names
        const Elf64_Shdr *symtab_sec = find_section(".symtab");
        if (!symtab_sec) {
            std::cerr << "Symbol table not found" << std::endl;
            return false;
        }

        const Elf64_Sym *symbols = reinterpret_cast<const Elf64_Sym*>(
            elf_data + symtab_sec->sh_offset);
        size_t num_symbols = symtab_sec->sh_size / sizeof(Elf64_Sym);

        // Find symtab string table
        const Elf64_Shdr *symstr_sec = &sections[symtab_sec->sh_link];
        const char *symstrtab = reinterpret_cast<const char*>(elf_data + symstr_sec->sh_offset);

        // Find maps section index
        int maps_sec_idx = maps_sec - sections;

        // Create maps and associate names from symbols
        for (size_t i = 0; i < num_symbols; i++) {
            if (symbols[i].st_shndx == maps_sec_idx &&
                ELF64_ST_TYPE(symbols[i].st_info) == STT_OBJECT) {

                const char *map_name = symstrtab + symbols[i].st_name;
                size_t map_idx = symbols[i].st_value / sizeof(bpf_map_def);

                if (map_idx < num_maps) {
                    const bpf_map_def *def = &maps[map_idx];
                    int map_fd = bpf_create_map(
                        static_cast<bpf_map_type>(def->type),
                        def->key_size,
                        def->value_size,
                        def->max_entries
                    );

                    if (map_fd < 0) {
                        std::cerr << "Failed to create map: " << map_name << std::endl;
                        return false;
                    }

                    BPFMap &bpf_map = g_maps[map_name];
                    bpf_map.fd = map_fd;
                    bpf_map.name = map_name;
                    bpf_map.max_entries = def->max_entries;
                }
            }
        }

        return true;
    }

    bool load_programs(int verbose) {
        // Find license section
        const Elf64_Shdr *license_sec = find_section("license");
        const char *license = "GPL";
        if (license_sec) {
            license = reinterpret_cast<const char*>(elf_data + license_sec->sh_offset);
        }

        // Load each uprobe program section
        for (int i = 0; i < ehdr->e_shnum; i++) {
            const Elf64_Shdr *sec = &sections[i];
            const char *sec_name = get_string(sec->sh_name);

            // Look for uprobe sections
            if (strncmp(sec_name, "uprobe/", 7) == 0) {
                const char *prog_name = sec_name + 7;

                const bpf_insn *insns = reinterpret_cast<const bpf_insn*>(
                    elf_data + sec->sh_offset);
                size_t insns_cnt = sec->sh_size / sizeof(bpf_insn);

                // Apply relocations for map references
                std::vector<bpf_insn> prog_insns(insns, insns + insns_cnt);

                // Find relocation section for this program
                for (int j = 0; j < ehdr->e_shnum; j++) {
                    const Elf64_Shdr *rel_sec = &sections[j];
                    if (rel_sec->sh_type == SHT_REL && rel_sec->sh_info == static_cast<Elf64_Word>(i)) {
                        const Elf64_Rel *rels = reinterpret_cast<const Elf64_Rel*>(
                            elf_data + rel_sec->sh_offset);
                        size_t num_rels = rel_sec->sh_size / sizeof(Elf64_Rel);

                        const Elf64_Shdr *symtab_sec = &sections[rel_sec->sh_link];
                        const Elf64_Sym *symbols = reinterpret_cast<const Elf64_Sym*>(
                            elf_data + symtab_sec->sh_offset);

                        const Elf64_Shdr *symstr_sec = &sections[symtab_sec->sh_link];
                        const char *symstrtab = reinterpret_cast<const char*>(
                            elf_data + symstr_sec->sh_offset);

                        for (size_t k = 0; k < num_rels; k++) {
                            size_t sym_idx = ELF64_R_SYM(rels[k].r_info);
                            const Elf64_Sym *sym = &symbols[sym_idx];
                            const char *sym_name = symstrtab + sym->st_name;

                            // Find the corresponding map
                            auto it = g_maps.find(sym_name);
                            if (it != g_maps.end()) {
                                size_t insn_idx = rels[k].r_offset / sizeof(bpf_insn);
                                if (insn_idx < prog_insns.size()) {
                                    prog_insns[insn_idx].src_reg = BPF_PSEUDO_MAP_FD;
                                    prog_insns[insn_idx].imm = it->second.fd;
                                }
                            }
                        }
                    }
                }

                char log_buf[65536];
                memset(log_buf, 0, sizeof(log_buf));

                int prog_fd = bpf_load_program(
                    BPF_PROG_TYPE_KPROBE,
                    prog_insns.data(),
                    prog_insns.size(),
                    license,
                    verbose > 1 ? log_buf : nullptr,
                    verbose > 1 ? sizeof(log_buf) : 0
                );

                if (prog_fd < 0) {
                    std::cerr << "Failed to load program: " << prog_name << std::endl;
                    return false;
                }

                BPFProgram bpf_prog;
                bpf_prog.prog_fd = prog_fd;
                bpf_prog.name = prog_name;
                g_programs.push_back(bpf_prog);

                if (verbose >= 2) {
                    log_message(verbose, 2, std::string("Loaded program: ") + prog_name);
                }
            }
        }

        return true;
    }
};

// Uprobe attachment via tracefs
static int attach_uprobe(const std::string& binary_path, uint64_t offset,
                        int prog_fd, int pid, int verbose) {
    // Write to uprobe_events
    std::string probe_name = "prof_libmem_" + std::to_string(getpid()) + "_" +
                            std::to_string(offset);

    std::string tracefs_path = "/sys/kernel/debug/tracing";
    std::string uprobe_events = tracefs_path + "/uprobe_events";

    // Use raw file I/O for tracefs (ofstream doesn't work reliably with special files)
    int events_fd = open(uprobe_events.c_str(), O_WRONLY | O_APPEND);
    if (events_fd < 0) {
        std::cerr << "Failed to open " << uprobe_events << ": " << strerror(errno) << std::endl;
        return -1;
    }

    // Try to remove probe if it exists (ignore errors)
    std::string remove_cmd = "-:uprobes/" + probe_name + "\n";
    if (write(events_fd, remove_cmd.c_str(), remove_cmd.length()) < 0) {
        // Ignore errors - probe may not exist
    }

    // Add probe
    std::ostringstream probe_def;
    probe_def << "p:uprobes/" << probe_name << " " << binary_path << ":0x"
              << std::hex << offset << "\n";
    std::string probe_str = probe_def.str();

    ssize_t written = write(events_fd, probe_str.c_str(), probe_str.length());
    int write_errno = errno;  // Save errno before close() can overwrite it
    close(events_fd);

    if (written < 0) {
        // If probe already exists (EEXIST or "File exists"), we can reuse it
        // This happens when multiple functions resolve to the same address (e.g., memmove=memcpy)
        if (write_errno == EEXIST || strstr(strerror(write_errno), "File exists") != NULL) {
            log_message(verbose, 2, "Uprobe already exists at offset 0x" +
                       std::to_string(offset) + ", reusing existing event");
            // Fall through to read event ID and attach BPF program
        } else {
            log_message(verbose, 1, "Failed to write uprobe definition: " + std::string(strerror(write_errno)));
            errno = write_errno;
            return -1;
        }
    }

    // Read event ID
    std::string id_path = tracefs_path + "/events/uprobes/" + probe_name + "/id";
    std::ifstream id_file(id_path);
    if (!id_file.is_open()) {
        log_message(verbose, 1, "Failed to read uprobe event ID from: " + id_path);
        return -1;
    }

    int event_id;
    id_file >> event_id;
    id_file.close();

    // Open perf event
    struct perf_event_attr attr = {};
    attr.type = PERF_TYPE_TRACEPOINT;
    attr.size = sizeof(attr);
    attr.config = event_id;
    attr.sample_period = 1;
    attr.wakeup_events = 1;
    attr.inherit = 1;  // Inherit to child threads/processes (multi-thread support)

    int perf_fd = perf_event_open(&attr, pid, -1, -1, PERF_FLAG_FD_CLOEXEC);
    if (perf_fd < 0) {
        log_message(verbose, 1, "perf_event_open failed for PID " + std::to_string(pid) +
                   ": " + strerror(errno));
        return -1;
    }

    // Attach BPF program
    if (ioctl(perf_fd, PERF_EVENT_IOC_SET_BPF, prog_fd) < 0) {
        log_message(verbose, 1, "PERF_EVENT_IOC_SET_BPF failed: " + std::string(strerror(errno)));
        close(perf_fd);
        return -1;
    }

    // Enable perf event
    if (ioctl(perf_fd, PERF_EVENT_IOC_ENABLE, 0) < 0) {
        log_message(verbose, 1, "PERF_EVENT_IOC_ENABLE failed: " + std::string(strerror(errno)));
        close(perf_fd);
        return -1;
    }

    // Track this probe and perf fd for cleanup on exit
    g_probe_names.push_back(probe_name);
    g_perf_fds.push_back(perf_fd);

    return perf_fd;
}

// Minimal x86-64 instruction length estimator for common opcodes
// Returns estimated length of first instruction at given offset in the file
static int estimate_x86_64_instruction_length(int fd, uint64_t offset) {
    unsigned char bytes[16] = {0};
    ssize_t read_size = pread(fd, bytes, 16, offset);

    if (read_size < 4) return 4;  // Conservative fallback

    // ENDBR64: f3 0f 1e fa (4 bytes)
    if (bytes[0] == 0xF3 && bytes[1] == 0x0F &&
        bytes[2] == 0x1E && bytes[3] == 0xFA) {
        return 4;
    }

    // VEX 2-byte prefix: c5 <vex> <opcode> [ModRM] [SIB] [disp] [imm]
    if (bytes[0] == 0xC5 && read_size >= 4) {
        // VEX.vvvv and VEX.L are in bytes[1]
        // Opcode is in bytes[2]
        // ModRM is in bytes[3] (if instruction uses ModRM)

        // Most VEX instructions have ModRM byte
        // For 2-byte VEX: typical length is 3-5 bytes
        // Conservative: return 4 as it covers vmovd and most common VEX ops
        return 4;
    }

    // VEX 3-byte prefix: c4 <vex1> <vex2> <opcode> [ModRM] [SIB] [disp] [imm]
    if (bytes[0] == 0xC4 && read_size >= 5) {
        // 3-byte VEX typically 5-7 bytes
        return 5;
    }

    // REX prefix: 40-4f
    if ((bytes[0] >= 0x40 && bytes[0] <= 0x4F) && read_size >= 3) {
        // REX + opcode + ModRM minimum
        return 3;
    }

    // Default conservative estimate
    return 4;
}

// Get symbol offset directly from ELF file (fallback for IFUNC issues)
static uint64_t get_elf_symbol_offset(const std::string& elf_path,
                                     const std::string& symbol_name,
                                     uint64_t hint_runtime_offset,
                                     int verbose) {
    int fd = open(elf_path.c_str(), O_RDONLY);
    if (fd < 0) {
        log_message(verbose, 2, "Failed to open ELF file: " + elf_path);
        return 0;
    }

    // Read ELF header
    Elf64_Ehdr ehdr;
    if (read(fd, &ehdr, sizeof(ehdr)) != sizeof(ehdr)) {
        close(fd);
        return 0;
    }

    // Find .dynsym section
    lseek(fd, ehdr.e_shoff, SEEK_SET);
    std::vector<Elf64_Shdr> shdrs(ehdr.e_shnum);
    if (read(fd, shdrs.data(), ehdr.e_shnum * sizeof(Elf64_Shdr)) !=
        static_cast<ssize_t>(ehdr.e_shnum * sizeof(Elf64_Shdr))) {
        close(fd);
        return 0;
    }

    // Find string table
    Elf64_Shdr& shstrtab = shdrs[ehdr.e_shstrndx];
    std::vector<char> shstrtab_data(shstrtab.sh_size);
    if (pread(fd, shstrtab_data.data(), shstrtab.sh_size, shstrtab.sh_offset) < 0) {
        close(fd);
        return 0;
    }

    // Find .dynsym and .dynstr
    Elf64_Shdr *dynsym = nullptr, *dynstr = nullptr;
    for (auto& sh : shdrs) {
        const char* name = shstrtab_data.data() + sh.sh_name;
        if (strcmp(name, ".dynsym") == 0) dynsym = &sh;
        if (strcmp(name, ".dynstr") == 0) dynstr = &sh;
    }

    if (!dynsym || !dynstr) {
        close(fd);
        return 0;
    }

    // Read symbol string table
    std::vector<char> strtab(dynstr->sh_size);
    if (pread(fd, strtab.data(), dynstr->sh_size, dynstr->sh_offset) < 0) {
        close(fd);
        return 0;
    }

    // Search symbols
    size_t num_syms = dynsym->sh_size / sizeof(Elf64_Sym);
    for (size_t i = 0; i < num_syms; i++) {
        Elf64_Sym sym;
        if (pread(fd, &sym, sizeof(sym), dynsym->sh_offset + i * sizeof(Elf64_Sym)) !=
            static_cast<ssize_t>(sizeof(Elf64_Sym))) {
            continue;
        }

        const char* sym_name = strtab.data() + sym.st_name;
        if (strcmp(sym_name, symbol_name.c_str()) == 0 && sym.st_value != 0) {
            // Skip IFUNC symbols: st_value points to the resolver function,
            // not the implementation. Attaching to the resolver captures
            // dynamic linker calls with wrong argument registers, producing
            // garbage size readings (e.g., 64TB bucket from ld.so internals).
            //
            // However, if a runtime-resolved offset is provided (hint_runtime_offset > 0),
            // check if it starts with ENDBR64 (CET landing pad, opcode: F3 0F 1E FA).
            // Older kernels (e.g., 4.19 on Debian 10) reject uprobes at ENDBR64 with
            // errno 524 (ENOTSUPP). Skip the ENDBR64 (return offset+4) since it's a
            // pure NOP - registers are identical, so function arguments are unaffected.
            if (ELF64_ST_TYPE(sym.st_info) == STT_GNU_IFUNC) {
                if (hint_runtime_offset > 0) {
                    // Estimate the first instruction's length at hint offset
                    int insn_len = estimate_x86_64_instruction_length(fd, hint_runtime_offset);

                    // Read first few bytes for logging
                    unsigned char first_bytes[8] = {0};
                    ssize_t bytes_read = pread(fd, first_bytes, 8, hint_runtime_offset);

                    if (bytes_read >= 4) {
                        // Log the bytes we read for debugging
                        std::ostringstream hex_bytes;
                        hex_bytes << std::hex << std::setfill('0');
                        int bytes_to_log = bytes_read < 8 ? bytes_read : 8;
                        for (int b = 0; b < bytes_to_log; b++) {
                            hex_bytes << std::setw(2) << static_cast<int>(first_bytes[b]) << " ";
                        }
                        log_message(verbose, 1, "ELF fallback: IFUNC '" + symbol_name +
                                   "' at offset 0x" + std::to_string(hint_runtime_offset) +
                                   " starts with bytes: " + hex_bytes.str() +
                                   "(estimated instruction length: " + std::to_string(insn_len) + " bytes)");

                        // Skip the first instruction to avoid uprobe rejection on older kernels
                        // This works because function prologue instructions don't modify the
                        // argument registers (rdi, rsi, rdx), so BPF can still read correct values
                        uint64_t skip_offset = hint_runtime_offset + insn_len;
                        log_message(verbose, 1, "ELF fallback: Skipping first instruction, using offset 0x" +
                                   std::to_string(skip_offset) + " (hint + " + std::to_string(insn_len) + ")");
                        close(fd);
                        return skip_offset;
                    }
                }

                log_message(verbose, 1, "ELF fallback: skipping IFUNC symbol '" +
                           symbol_name + "' (resolver address != implementation)");
                close(fd);
                return 0;
            }

            // Convert virtual address to file offset using program headers
            for (int j = 0; j < ehdr.e_phnum; j++) {
                Elf64_Phdr phdr;
                if (pread(fd, &phdr, sizeof(phdr), ehdr.e_phoff + j * sizeof(Elf64_Phdr)) !=
                    static_cast<ssize_t>(sizeof(phdr))) {
                    continue;
                }

                if (phdr.p_type == PT_LOAD &&
                    sym.st_value >= phdr.p_vaddr &&
                    sym.st_value < phdr.p_vaddr + phdr.p_memsz) {
                    uint64_t file_offset = (sym.st_value - phdr.p_vaddr) + phdr.p_offset;
                    log_message(verbose, 2, "ELF fallback: " + symbol_name +
                               " at file offset 0x" + std::to_string(file_offset));
                    close(fd);
                    return file_offset;
                }
            }
        }
    }

    close(fd);
    return 0;
}

// IFUNC resolution using dlopen/dlsym with ELF fallback
static bool resolve_ifunc(FunctionInfo& func, int verbose) {
    log_message(verbose, 2, "Resolving IFUNC for: " + func.name);

    void* handle = dlopen(func.libname.c_str(), RTLD_LAZY);
    if (!handle) {
        log_message(verbose, 2, "dlopen failed: " + std::string(dlerror()));
        func.resolved_offset = 0;
        func.resolved_module = func.libname;
        return true;  // Use direct symbol
    }

    void* sym_ptr = dlsym(handle, func.symbol.c_str());
    if (!sym_ptr) {
        log_message(verbose, 2, "dlsym failed: " + std::string(dlerror()));
        dlclose(handle);
        func.resolved_offset = 0;
        func.resolved_module = func.libname;
        return true;
    }

    // Read /proc/self/maps to find module base
    std::ifstream maps("/proc/self/maps");
    if (!maps.is_open()) {
        dlclose(handle);
        func.resolved_offset = 0;
        func.resolved_module = func.libname;
        return true;
    }

    uint64_t sym_addr = reinterpret_cast<uint64_t>(sym_ptr);
    std::string line;
    while (std::getline(maps, line)) {
        uint64_t start, end, file_offset;
        char perms[5];
        // Parse /proc/self/maps format: start-end perms file_offset dev inode pathname
        if (sscanf(line.c_str(), "%lx-%lx %s %lx", &start, &end, perms, &file_offset) == 4) {
            // Check if symbol address falls within this mapping
            if (sym_addr >= start && sym_addr < end) {
                // Extract the actual pathname from the maps line
                size_t path_start = line.find_first_of('/', 0);
                if (path_start != std::string::npos) {
                    size_t path_end = line.find_first_of(" \t\n\r", path_start);
                    std::string actual_path = line.substr(path_start, path_end - path_start);

                    // Verify it's the right library (contains libc)
                    if (actual_path.find("libc") != std::string::npos) {
                        // Correct ELF file offset calculation:
                        // file_offset_in_ELF = (virtual_addr - mapping_start) + mapping_file_offset
                        func.resolved_offset = (sym_addr - start) + file_offset;
                        func.resolved_module = actual_path;  // Use actual path from maps, not func.libname
                        log_message(verbose, 2, "Resolved " + func.name + " to file offset 0x" +
                                   std::to_string(func.resolved_offset) + " in " + actual_path +
                                   " (virt=0x" + std::to_string(sym_addr) +
                                   ", map_start=0x" + std::to_string(start) +
                                   ", map_offset=0x" + std::to_string(file_offset) + ")");
                        break;
                    }
                }
            }
        }
    }

    maps.close();
    dlclose(handle);

    if (func.resolved_offset == 0) {
        func.resolved_module = func.libname;
    }

    return true;
}

// Enumerate all thread TIDs for a given process (from /proc/<pid>/task/)
// Returns a vector of TIDs. For exec mode, returns just {pid} since
// attr.inherit covers threads created after perf_event_open.
static std::vector<pid_t> get_thread_tids(pid_t pid, bool exec_mode, int verbose) {
    std::vector<pid_t> tids;

    // In exec mode, child hasn't started yet; attr.inherit will cover new threads
    if (exec_mode) {
        tids.push_back(pid);
        return tids;
    }

    // Attach mode: enumerate existing threads from /proc/<pid>/task/
    std::string task_dir = "/proc/" + std::to_string(pid) + "/task";
    DIR* dir = opendir(task_dir.c_str());
    if (!dir) {
        log_message(verbose, 1, "Cannot open " + task_dir + ": " + strerror(errno) +
                   " (falling back to main thread only)");
        tids.push_back(pid);
        return tids;
    }

    struct dirent* entry;
    while ((entry = readdir(dir)) != nullptr) {
        if (entry->d_name[0] == '.') continue;
        pid_t tid = static_cast<pid_t>(atoi(entry->d_name));
        if (tid > 0) {
            tids.push_back(tid);
        }
    }
    closedir(dir);

    if (tids.empty()) {
        tids.push_back(pid);
    }

    if (tids.size() > 1) {
        log_message(verbose, 1, "Process " + std::to_string(pid) +
                   " has " + std::to_string(tids.size()) + " threads - attaching to all");
    }

    return tids;
}

// Detect libc path. When target_pid > 0, reads the target's maps
// to find the correct libc (important for containers/mount namespaces).
static std::string detect_libc_path(int verbose, pid_t target_pid = -1) {
    std::string maps_path = (target_pid > 0)
        ? "/proc/" + std::to_string(target_pid) + "/maps"
        : "/proc/self/maps";
    std::ifstream maps(maps_path);
    if (maps.is_open()) {
        std::string line;
        while (std::getline(maps, line)) {
            if (line.find("libc") != std::string::npos &&
                (line.find("libc.so") != std::string::npos || line.find("libc-") != std::string::npos)) {
                size_t path_start = line.find_first_of('/', 0);
                if (path_start != std::string::npos) {
                    size_t path_end = line.find_first_of(" \t\n\r", path_start);
                    std::string libc_path = line.substr(path_start, path_end - path_start);

                    // Resolve symlink
                    char resolved[PATH_MAX];
                    if (realpath(libc_path.c_str(), resolved)) {
                        log_message(verbose, 1, "Found libc: " + std::string(resolved));
                        return std::string(resolved);
                    }
                }
            }
        }
    }

    // Fallback to common paths
    const char* common_paths[] = {
        "/lib/x86_64-linux-gnu/libc.so.6",
        "/lib64/libc.so.6",
        "/usr/lib/x86_64-linux-gnu/libc.so.6",
        nullptr
    };

    for (int i = 0; common_paths[i]; i++) {
        char resolved[PATH_MAX];
        if (realpath(common_paths[i], resolved)) {
            log_message(verbose, 1, "Using fallback libc: " + std::string(resolved));
            return std::string(resolved);
        }
    }

    return "/lib/x86_64-linux-gnu/libc.so.6";
}

// Helper function to print alignment stats for a specific function
static void print_function_alignment_stats(const std::string& func_name,
                                          uint64_t total_calls,
                                          int argSRC, int argDST,
                                          const std::string& alignment_label) {
    if (total_calls == 0) return;

    uint32_t key = 0;
    uint64_t src_aligned = 0, dst_aligned = 0, both_aligned = 0;

    bool has_src = argSRC > 0;
    bool has_dst = argDST > 0;

    if (!has_src && !has_dst) return;

    // Print section header with alignment boundary
    *g_output_stream << "\n  Memory Alignment Statistics (" << alignment_label << " boundary):\n";
    *g_output_stream << "  " << std::left << std::setw(25) << "Alignment Type"
                    << std::setw(10) << "Count" << std::setw(10) << "Percentage"
                    << "Distribution\n";
    *g_output_stream << "  " << std::string(65, '-') << "\n";

    // Lambda to print alignment row
    auto print_align_row = [&](const std::string& label, uint64_t count) {
        double percent = (count * 100.0) / total_calls;
        int bar_len = static_cast<int>(percent / 5);  // Scale to ~20 chars
        std::string bar(bar_len, '*');

        *g_output_stream << "  " << std::left << std::setw(22) << label << ": "
                        << std::left << std::setw(10) << count << " "
                        << std::right << std::setw(6) << std::fixed << std::setprecision(2)
                        << percent << "%    |" << bar << "\n";
    };

    // Get alignment counts (per-CPU sum) and print rows
    if (has_src) {
        auto src_it = g_maps.find("aligned_src_" + func_name);
        if (src_it != g_maps.end()) {
            src_aligned = bpf_map_lookup_elem_percpu_sum(src_it->second.fd, &key);
            print_align_row("Src " + alignment_label + "-aligned", src_aligned);
        }
    }

    if (has_dst) {
        auto dst_it = g_maps.find("aligned_dst_" + func_name);
        if (dst_it != g_maps.end()) {
            dst_aligned = bpf_map_lookup_elem_percpu_sum(dst_it->second.fd, &key);
            print_align_row("Dst " + alignment_label + "-aligned", dst_aligned);
        }
    }

    if (has_src && has_dst) {
        auto both_it = g_maps.find("aligned_both_" + func_name);
        if (both_it != g_maps.end()) {
            both_aligned = bpf_map_lookup_elem_percpu_sum(both_it->second.fd, &key);
            print_align_row("Both " + alignment_label + "-aligned", both_aligned);

            // Calculate neither aligned
            uint64_t neither_aligned = total_calls - (src_aligned + dst_aligned - both_aligned);
            print_align_row("Neither aligned", neither_aligned);
        }
    }
}

// Print statistics
static void print_function_stats(const std::vector<FunctionInfo>& dist_funcs,
                                const std::vector<FunctionInfo>& count_funcs,
                                uint32_t alignment_bytes, const std::string& alignment_label,
                                bool include_distribution) {
    g_end_time = std::chrono::system_clock::now();
    auto end_c = std::chrono::system_clock::to_time_t(g_end_time);
    auto start_c = std::chrono::system_clock::to_time_t(g_start_time);

    // Calculate runtime
    auto duration = std::chrono::duration_cast<std::chrono::seconds>(g_end_time - g_start_time);
    int total_seconds = duration.count();
    int hours = total_seconds / 3600;
    int minutes = (total_seconds % 3600) / 60;
    int seconds = total_seconds % 60;

    // Print header (only for final summary)
    if (include_distribution) {
        *g_output_stream << std::string(71, '=') << "\n";
        *g_output_stream << "AOCL-LibMem Profiler - Summary\n";
        *g_output_stream << std::string(71, '=') << "\n";
        *g_output_stream << "Started at: " << std::put_time(std::localtime(&start_c), "%Y-%m-%d %H:%M:%S") << "\n";
        *g_output_stream << "Ended at:   " << std::put_time(std::localtime(&end_c), "%Y-%m-%d %H:%M:%S") << "\n";
        *g_output_stream << "Total runtime: " << hours << "h " << minutes << "m " << seconds << "s\n";
        *g_output_stream << std::string(71, '=') << "\n\n";
    }

    *g_output_stream << "\n--- Function Statistics at "
                    << std::put_time(std::localtime(&end_c), "%Y-%m-%d %H:%M:%S")
                    << " ---\n";

    // Collect all function call counts for summary
    std::map<std::string, uint64_t> function_counts;

    // Print histograms for distribution functions
    for (const auto& func : dist_funcs) {
        auto it = g_maps.find("dist_" + func.name);
        if (it == g_maps.end()) continue;

        uint32_t key = 0;
        uint64_t count = bpf_map_lookup_elem_percpu_sum(it->second.fd, &key);
        if (count == 0) {
            continue;
        }

        function_counts[func.name] = count;

        *g_output_stream << "\n" << std::string(30, '=') << " " << func.display_name()
                        << " (" << count << " calls) "
                        << std::string(30, '=') << "\n";

        // Print histogram
        auto hist_it = g_maps.find("lenHist_" + func.name);
        if (hist_it != g_maps.end()) {
            std::map<int, uint64_t> hist_values;
            uint64_t max_val = 0;

            for (uint32_t bucket = 0; bucket < 64; bucket++) {
                uint64_t val = bpf_map_lookup_elem_percpu_sum(hist_it->second.fd, &bucket);
                if (val > 0) {
                    hist_values[bucket] = val;
                    if (val > max_val) max_val = val;
                }
            }

            if (!hist_values.empty()) {
                *g_output_stream << "          size:          : count     distribution\n";
                for (const auto& [bucket, val] : hist_values) {
                    uint64_t low = (bucket == 0) ? 0 : (1ULL << (bucket - 1));
                    uint64_t high = (1ULL << bucket) - 1;

                    int bar_len = max_val > 0 ? (val * 40 / max_val) : 0;
                    std::string bar(bar_len, '*');
                    std::string padding(40 - bar_len, ' ');

                    *g_output_stream << std::right << std::setw(9) << low << " -> "
                                    << std::left << std::setw(12) << high << ": "
                                    << std::left << std::setw(8) << val << " |"
                                    << bar << padding << "|\n";
                }
            }
        }

        // Print alignment stats for this function if enabled
        if (alignment_bytes > 0) {
            print_function_alignment_stats(func.name, count, func.argSRC, func.argDST, alignment_label);
        }
    }

    // Print counts for count-only functions
    for (const auto& func : count_funcs) {
        auto it = g_maps.find("callCount_" + func.name);
        if (it == g_maps.end()) continue;

        uint32_t key = 0;
        uint64_t count = bpf_map_lookup_elem_percpu_sum(it->second.fd, &key);
        if (count == 0) {
            continue;
        }

        function_counts[func.name] = count;

        *g_output_stream << "\n" << std::string(30, '=') << " " << func.display_name()
                        << " (" << count << " calls) "
                        << std::string(30, '=') << "\n";

        // Print alignment stats for this function if enabled
        if (alignment_bytes > 0) {
            print_function_alignment_stats(func.name, count, func.argSRC, func.argDST, alignment_label);
        }
    }

    *g_output_stream << std::string(60, '-') << "\n";

    // Print overall function call distribution
    if (!function_counts.empty()) {
        // Build list using display_name() to show aliases inline
        struct FuncEntry {
            std::string display_name;
            uint64_t count;
        };
        std::vector<FuncEntry> all_entries;
        uint64_t total_calls = 0;

        // Collect primary function entries with their display names (includes alias annotation)
        for (const auto& func : dist_funcs) {
            auto it = function_counts.find(func.name);
            if (it != function_counts.end() && it->second > 0) {
                all_entries.push_back({func.display_name(), it->second});
                total_calls += it->second;
            }
        }

        for (const auto& func : count_funcs) {
            auto it = function_counts.find(func.name);
            if (it != function_counts.end() && it->second > 0) {
                all_entries.push_back({func.display_name(), it->second});
                total_calls += it->second;
            }
        }

        // Sort by count (descending), then by name
        std::sort(all_entries.begin(), all_entries.end(),
                 [](const auto& a, const auto& b) {
                     if (a.count != b.count) return a.count > b.count;
                     return a.display_name < b.display_name;
                 });

        if (total_calls > 0) {
            *g_output_stream << "\n--- Function Call Distribution ---\n";
            *g_output_stream << std::left << std::setw(13) << "Function"
                            << std::right << std::setw(9) << "Calls"
                            << std::setw(9) << "Percent"
                            << "  Distribution\n";
            *g_output_stream << std::string(47, '-') << "\n";

            for (const auto& entry : all_entries) {
                double percent = (entry.count * 100.0) / total_calls;
                int bar_len = static_cast<int>(percent / 5);  // Scale to ~20 chars max
                std::string bar(bar_len, '*');

                *g_output_stream << std::left << std::setw(22) << entry.display_name
                                << std::right << std::setw(9) << entry.count
                                << std::setw(8) << std::fixed << std::setprecision(2) << percent << "%"
                                << "  |" << bar << "\n";
            }

            *g_output_stream << "\nTotal function calls (sum): " << total_calls << "\n";
            *g_output_stream << std::string(60, '-') << "\n";
        }
    }
}

// Print usage
static void print_usage(const char* prog_name) {
    std::cout << "Usage: " << prog_name << " [OPTIONS] [-e CMD [ARGS...]]\n\n";
    std::cout << "Trace calls to libc memory/string functions\n\n";
    std::cout << "Options:\n";
    std::cout << "  -i, --interval SECONDS      Reporting interval (default: 5)\n";
    std::cout << "  -p, --pid PID              Trace only this PID\n";
    std::cout << "  -f, --function FUNC        Trace only specified functions\n";
    std::cout << "  -v, --verbose              Increase verbosity\n";
    std::cout << "  -t, --time SECONDS         Total time to run\n";
    std::cout << "  -c, --track-count          Track count-only functions\n";
    std::cout << "  -o, --output FILE          Output file\n";
    std::cout << "  -a, --check-alignment [ALIGNMENT]\n";
    std::cout << "                             Check memory alignment at specified boundary.\n";
    std::cout << "                             Default: 64B if no value given.\n";
    std::cout << "                             Accepts: 16, 32, 64, 4096 (bytes) or\n";
    std::cout << "                             16B, 32B, 64B, 1KB, 4KB, 2MB, 1GB.\n";
    std::cout << "                             Only the single specified alignment is checked.\n";
    std::cout << "  -h, --help                 Show this help\n";
    std::cout << "\n";
    std::cout << "  -e, --exec CMD [ARGS...]   Execute and trace command (must be last option)\n";
    std::cout << "\n";
    std::cout << "Note: The -e option must be the last option specified. All arguments\n";
    std::cout << "      after -e are treated as the executable and its arguments.\n";
    std::cout << "\n";
    std::cout << "Examples:\n";
    std::cout << "  " << prog_name << " -v -i 2 -e ls -la /tmp\n";
    std::cout << "  " << prog_name << " -a -e ./my_program           # Check 64-byte alignment (default)\n";
    std::cout << "  " << prog_name << " -a 4KB -e ./my_program      # Check 4KB alignment\n";
    std::cout << "  " << prog_name << " -p 1234\n";
}

// Main function
int main(int argc, char** argv) {
    Config config;

    static struct option long_options[] = {
        {"interval", required_argument, 0, 'i'},
        {"pid", required_argument, 0, 'p'},
        {"function", required_argument, 0, 'f'},
        {"verbose", no_argument, 0, 'v'},
        {"exec", no_argument, 0, 'e'},
        {"time", required_argument, 0, 't'},
        {"track-count", no_argument, 0, 'c'},
        {"output", required_argument, 0, 'o'},
        {"check-alignment", optional_argument, 0, 'a'},
        {"help", no_argument, 0, 'h'},
        {0, 0, 0, 0}
    };

    int opt;
    bool exec_mode = false;

    while ((opt = getopt_long(argc, argv, "i:p:f:vet:co:a::h", long_options, nullptr)) != -1) {
        switch (opt) {
            case 'i': config.interval = std::atoi(optarg); break;
            case 'p': config.pid = std::atoi(optarg); break;
            case 'f': config.functions.push_back(optarg); break;
            case 'v': config.verbose++; break;
            case 'e':
                exec_mode = true;
                // -e is the last option; everything after it is the command and its arguments
                for (int i = optind; i < argc; i++) {
                    config.exec_args.push_back(argv[i]);
                }
                if (config.exec_args.empty()) {
                    std::cerr << "Error: --exec requires a command\n";
                    return 1;
                }
                // Stop processing options since -e is the last option
                goto done_parsing_options;
            case 't': config.time_limit = std::atoi(optarg); break;
            case 'c': config.track_count_functions = true; break;
            case 'o': config.output_file = optarg; break;
            case 'a':
                {
                    std::string err_msg;
                    const char* align_arg = optarg;
                    // With optional_argument, -a 1024 (space-separated) leaves optarg
                    // NULL and 1024 as a separate argv entry. Consume it manually.
                    if (!align_arg && optind < argc && argv[optind] != nullptr &&
                        argv[optind][0] != '-' && argv[optind][0] != '\0') {
                        align_arg = argv[optind];
                        optind++;  // consume the argument
                    }
                    if (align_arg) {
                        config.alignment_bytes = parse_alignment_value(align_arg, err_msg);
                        if (config.alignment_bytes == 0) {
                            std::cerr << "ERROR: " << err_msg << "\n";
                            return 1;
                        }
                    } else {
                        config.alignment_bytes = 64;  // Default: 64-byte alignment
                    }
                    config.alignment_label = format_alignment_label(config.alignment_bytes);
                    std::cout << "Alignment check configured: " << config.alignment_label
                              << " (" << config.alignment_bytes << " bytes, mask=0x"
                              << std::hex << (config.alignment_bytes - 1) << std::dec << ")\n";
                }
                break;
            case 'h': print_usage(argv[0]); return 0;
            default: print_usage(argv[0]); return 1;
        }
    }
    done_parsing_options:

    // Register uprobe cleanup for normal exit and atexit paths
    std::atexit(cleanup_uprobes);

    if (!config.output_file.empty()) {
        g_output_file.open(config.output_file);
        if (g_output_file.is_open()) {
            g_output_stream = &g_output_file;
            std::cout << "Output logged to: " << config.output_file << "\n";
        }
    }

    if (geteuid() != 0) {
        std::cerr << "Error: Must run as root\n";
        return 1;
    }

    // Use target's /proc/<pid>/maps when attaching to an existing process (-p),
    // so we find the correct libc even in container/mount-namespace scenarios.
    std::string libc_path = detect_libc_path(config.verbose,
                                             (!exec_mode && config.pid > 0) ? config.pid : -1);
    log_message(config.verbose, 0, "Using libc: " + libc_path);

    // Define functions
    std::vector<FunctionInfo> TARGET_DIST_FUNCTIONS = {
        {libc_path, "memcpy", "memcpy", 3, 2, 1, true},
        {libc_path, "memmove", "memmove", 3, 2, 1, true},
        {libc_path, "mempcpy", "mempcpy", 3, 2, 1, true},
        {libc_path, "memcmp", "memcmp", 3, 2, 1, true},
        {libc_path, "memset", "memset", 3, 1, 0, true},
        {libc_path, "memchr", "memchr", 3, 1, 0, true},
        {libc_path, "strncpy", "strncpy", 3, 2, 1, true},
        {libc_path, "strncmp", "strncmp", 3, 2, 1, true},
        {libc_path, "strncat", "strncat", 3, 2, 1, true},
        {libc_path, "strnlen", "strnlen", 2, 1, 0, true}
    };

    std::vector<FunctionInfo> TARGET_CNT_FUNCTIONS = {
        {libc_path, "strcpy", "strcpy", 0, 2, 1, false},
        {libc_path, "strcmp", "strcmp", 0, 1, 2, false},
        {libc_path, "strcat", "strcat", 0, 2, 1, false},
        {libc_path, "strlen", "strlen", 0, 1, 0, false},
        {libc_path, "strchr", "strchr", 0, 1, 0, false},
        {libc_path, "strstr", "strstr", 0, 1, 2, false},
        {libc_path, "strspn", "strspn", 0, 1, 2, false}
    };

    std::vector<FunctionInfo> dist_funcs, count_funcs;
    if (!config.functions.empty()) {
        for (const auto& f : TARGET_DIST_FUNCTIONS) {
            // Check if function name or any of its aliases match the requested functions
            bool matched = std::find(config.functions.begin(), config.functions.end(), f.name) != config.functions.end();
            if (!matched) {
                for (const auto& alias : f.aliases) {
                    if (std::find(config.functions.begin(), config.functions.end(), alias) != config.functions.end()) {
                        matched = true;
                        break;
                    }
                }
            }
            if (matched) {
                dist_funcs.push_back(f);
            }
        }
        for (const auto& f : TARGET_CNT_FUNCTIONS) {
            // Check if function name or any of its aliases match the requested functions
            bool matched = std::find(config.functions.begin(), config.functions.end(), f.name) != config.functions.end();
            if (!matched) {
                for (const auto& alias : f.aliases) {
                    if (std::find(config.functions.begin(), config.functions.end(), alias) != config.functions.end()) {
                        matched = true;
                        break;
                    }
                }
            }
            if (matched) {
                count_funcs.push_back(f);
                config.track_count_functions = true;
            }
        }
    } else {
        dist_funcs = TARGET_DIST_FUNCTIONS;
        if (config.track_count_functions) {
            count_funcs = TARGET_CNT_FUNCTIONS;
        }
    }

    // Resolve IFUNCs for primary functions and their aliases
    for (auto& func : dist_funcs) {
        resolve_ifunc(func, config.verbose);
    }
    for (auto& func : count_funcs) {
        resolve_ifunc(func, config.verbose);
    }

    // Detect functions that resolve to the same address and merge them.
    // When two functions share the same implementation (e.g., memcpy and memmove
    // on some glibc versions), they are merged into a single entry shown as
    // "memcpy + memmove" to avoid double-counting. Only one BPF probe is attached.
    // On systems where they have different implementations, they remain separate.
    {
        // Build map of (module, offset) -> index in dist_funcs
        std::map<std::pair<std::string, uint64_t>, size_t> addr_to_idx;
        std::vector<size_t> to_remove;

        for (size_t i = 0; i < dist_funcs.size(); i++) {
            if (dist_funcs[i].resolved_offset == 0) continue;
            auto key = std::make_pair(dist_funcs[i].resolved_module, dist_funcs[i].resolved_offset);
            auto it = addr_to_idx.find(key);
            if (it != addr_to_idx.end()) {
                size_t primary_idx = it->second;
                dist_funcs[primary_idx].aliases.push_back(dist_funcs[i].name);
                log_message(config.verbose, 0, dist_funcs[i].name + " shares implementation with " +
                           dist_funcs[primary_idx].name + " at offset 0x" +
                           std::to_string(dist_funcs[i].resolved_offset) + " (merging)");
                to_remove.push_back(i);
            } else {
                addr_to_idx[key] = i;
            }
        }
        // Remove merged functions in reverse order to preserve indices
        for (auto it = to_remove.rbegin(); it != to_remove.rend(); ++it) {
            dist_funcs.erase(dist_funcs.begin() + static_cast<long>(*it));
        }

        // Same for count-only functions
        addr_to_idx.clear();
        to_remove.clear();
        for (size_t i = 0; i < count_funcs.size(); i++) {
            if (count_funcs[i].resolved_offset == 0) continue;
            auto key = std::make_pair(count_funcs[i].resolved_module, count_funcs[i].resolved_offset);
            auto it = addr_to_idx.find(key);
            if (it != addr_to_idx.end()) {
                size_t primary_idx = it->second;
                count_funcs[primary_idx].aliases.push_back(count_funcs[i].name);
                log_message(config.verbose, 0, count_funcs[i].name + " shares implementation with " +
                           count_funcs[primary_idx].name + " (merging)");
                to_remove.push_back(i);
            } else {
                addr_to_idx[key] = i;
            }
        }
        for (auto it = to_remove.rbegin(); it != to_remove.rend(); ++it) {
            count_funcs.erase(count_funcs.begin() + static_cast<long>(*it));
        }
    }

    // Build a map of which BPF programs need to be attached at which offsets
    // Key: (module_path, offset), Value: (function_name, list of offsets for that function's probe)
    std::map<std::string, std::vector<std::pair<std::string, uint64_t>>> attach_points;

    // Helper lambda to add attach points for a function and its aliases
    auto add_attach_points = [&](const FunctionInfo& func) {
        if (func.resolved_offset > 0) {
            attach_points[func.name].push_back({func.resolved_module, func.resolved_offset});
            log_message(config.verbose, 2, "Primary attach point for " + func.name +
                       ": " + func.resolved_module + " @ 0x" + std::to_string(func.resolved_offset));
        }

        // For each alias, resolve its symbol and add as additional attach point
        for (const auto& alias : func.aliases) {
            FunctionInfo alias_func{func.libname, alias, alias,
                                   func.argSZ, func.argSRC, func.argDST, func.is_dist_function};
            resolve_ifunc(alias_func, config.verbose);

            if (alias_func.resolved_offset > 0) {
                // Only add if it's a different offset (avoid duplicate attachments)
                bool is_duplicate = false;
                for (const auto& [mod, off] : attach_points[func.name]) {
                    if (mod == alias_func.resolved_module && off == alias_func.resolved_offset) {
                        is_duplicate = true;
                        log_message(config.verbose, 1, "Alias " + alias + " resolves to same address as " +
                                   func.name + " (skipping duplicate attachment)");
                        break;
                    }
                }

                if (!is_duplicate) {
                    attach_points[func.name].push_back({alias_func.resolved_module, alias_func.resolved_offset});
                    log_message(config.verbose, 1, "Alias " + alias + " has different implementation at " +
                               alias_func.resolved_module + " @ 0x" + std::to_string(alias_func.resolved_offset) +
                               " (will attach " + func.name + " probe here too)");
                }
            }
        }
    };

    for (const auto& func : dist_funcs) {
        add_attach_points(func);
    }
    for (const auto& func : count_funcs) {
        add_attach_points(func);
    }

    // Launch child process if needed
    pid_t child_pid = -1;
    if (exec_mode) {
        child_pid = fork();
        if (child_pid == 0) {
            raise(SIGSTOP);
            std::vector<char*> exec_argv;
            for (const auto& arg : config.exec_args) {
                exec_argv.push_back(const_cast<char*>(arg.c_str()));
            }
            exec_argv.push_back(nullptr);
            execvp(exec_argv[0], exec_argv.data());
            std::cerr << "exec failed: " << strerror(errno) << "\n";
            exit(1);
        } else if (child_pid < 0) {
            std::cerr << "fork failed\n";
            return 1;
        }
        config.pid = child_pid;
        log_message(config.verbose, 0, "Launched PID: " + std::to_string(child_pid));
    }

    // Load BPF program
    BPFLoader loader(profiler_bpf_o, profiler_bpf_o_len);

    if (!loader.is_valid()) {
        std::cerr << "Failed to initialize BPF loader\n";
        return 1;
    }

    if (!loader.load_maps()) {
        std::cerr << "Failed to load BPF maps\n";
        return 1;
    }

    if (!loader.load_programs(config.verbose)) {
        std::cerr << "Failed to load BPF programs\n";
        return 1;
    }

    log_message(config.verbose, 0, "Loaded " + std::to_string(g_maps.size()) +
               " maps and " + std::to_string(g_programs.size()) + " programs");

    // Set alignment mask in BPF map (must be done before probes start firing)
    {
        auto mask_it = g_maps.find("alignment_mask");
        if (mask_it != g_maps.end()) {
            uint32_t key = 0;
            uint32_t mask_value = (config.alignment_bytes > 0) ? (config.alignment_bytes - 1) : 0;
            if (bpf_map_update_elem(mask_it->second.fd, &key, &mask_value, 0) < 0) {
                std::cerr << "WARNING: Failed to set alignment mask in BPF map: "
                          << strerror(errno) << std::endl;
            } else {
                {
                    std::ostringstream hex_mask;
                    hex_mask << "Set BPF alignment_mask = 0x"
                             << std::hex << mask_value
                             << (config.alignment_bytes > 0
                                 ? " (" + config.alignment_label + " alignment)"
                                 : " (alignment checking disabled)");
                    log_message(config.verbose, 1, hex_mask.str());
                }
            }
        } else {
            if (config.alignment_bytes > 0) {
                std::cerr << "WARNING: alignment_mask BPF map not found, alignment checking unavailable\n";
            }
        }
    }

    // Get list of TIDs to attach to.
    // - exec mode: just {child_pid}; attr.inherit covers threads created later
    // - attach mode: enumerate /proc/<pid>/task/* for existing threads;
    //   attr.inherit covers threads they create after attachment
    std::vector<pid_t> tids = get_thread_tids(config.pid, exec_mode, config.verbose);

    // Attach uprobes using the attach_points map
    int attached = 0;
    for (const auto& [func_name, offsets] : attach_points) {
        // Find corresponding BPF program
        std::string prog_name = "count_" + func_name;
        int prog_fd = -1;
        for (const auto& prog : g_programs) {
            if (prog.name == prog_name) {
                prog_fd = prog.prog_fd;
                break;
            }
        }

        if (prog_fd < 0) {
            log_message(config.verbose, 1, "Program not found: " + prog_name);
            continue;
        }

        // Attach at all offsets for this function (primary + aliases)
        for (const auto& [module, offset] : offsets) {
            if (offset == 0) continue;

            // Attach to each TID (single TID in exec mode, all threads in attach mode)
            for (pid_t tid : tids) {
                // Try to attach with runtime-resolved offset first
                int perf_fd = attach_uprobe(module, offset, prog_fd,
                                            tid, config.verbose);

                // If attachment fails with error 524 (ENOTSUPP - not supported), try ELF fallback
                if (perf_fd < 0 && errno == 524) {
                    log_message(config.verbose, 1, "Trying ELF fallback for " + func_name + " @ 0x" +
                               std::to_string(offset) + " (runtime offset failed)");
                    uint64_t elf_offset = get_elf_symbol_offset(module, func_name, offset, config.verbose);

                    if (elf_offset > 0) {
                        perf_fd = attach_uprobe(module, elf_offset, prog_fd,
                                               tid, config.verbose);
                        if (perf_fd >= 0) {
                            log_message(config.verbose, 1, "ELF fallback succeeded for " + func_name);
                        }
                    }
                }

                if (perf_fd >= 0) {
                    attached++;
                    log_message(config.verbose, 2, "Attached " + func_name + " probe at " +
                               module + " @ 0x" + std::to_string(offset) +
                               " (TID " + std::to_string(tid) + ")");
                }
            }
        }
    }

    log_message(config.verbose, 0, "Attached " + std::to_string(attached) + " probes");

    if (attached == 0) {
        std::cerr << "No probes attached\n";
        return 1;
    }

    // Resume child
    if (exec_mode && child_pid > 0) {
        kill(child_pid, SIGCONT);
    }

    // Set up signal handlers
    signal(SIGINT, signal_handler);
    signal(SIGTERM, signal_handler);

    // Set global start time and main loop
    g_start_time = std::chrono::system_clock::now();
    log_message(config.verbose, 0, "Tracing started");
    auto start_time = std::chrono::steady_clock::now();

    while (!g_should_exit) {
        sleep(config.interval);

        if (exec_mode && child_pid > 0) {
            int status;
            if (waitpid(child_pid, &status, WNOHANG) != 0) {
                log_message(config.verbose, 0, "Process exited");
                break;
            }
        }

        if (config.time_limit > 0) {
            auto elapsed = std::chrono::duration_cast<std::chrono::seconds>(
                std::chrono::steady_clock::now() - start_time).count();
            if (elapsed >= config.time_limit) {
                break;
            }
        }

        if (config.verbose > 0) {
            print_function_stats(dist_funcs, count_funcs, config.alignment_bytes, config.alignment_label, false);
        }
    }

    *g_output_stream << "\nFinal summary:\n";
    print_function_stats(dist_funcs, count_funcs, config.alignment_bytes, config.alignment_label, true);

    // Cleanup: disable and close perf event fds, remove tracefs uprobe events,
    // then close BPF program fds
    for (int pfd : g_perf_fds) {
        ioctl(pfd, PERF_EVENT_IOC_DISABLE, 0);
        close(pfd);
    }
    g_perf_fds.clear();

    cleanup_uprobes();

    for (auto& prog : g_programs) {
        if (prog.prog_fd >= 0) close(prog.prog_fd);
    }
    for (auto& [name, map] : g_maps) {
        if (map.fd >= 0) close(map.fd);
    }

    if (g_output_file.is_open()) {
        g_output_file.close();
    }

    return 0;
}
