name: Add members ssh keys for VM
description: Add team members public ssh keys to github@ user
inputs:
  org:
    required: true
    description: "org name"
  team:
    required: true
    description: "team slug name"
  token:
    required: true
    description: "GITHUB_TOKEN"

runs:
  using: composite
  steps:
    - name: init
      shell: bash
      run: |
        echo "LOGINS_FILE=$(mktemp)" >> $GITHUB_ENV
        echo "KEYS_FILE=$(mktemp)" >> $GITHUB_ENV
    - name: collect members
      shell: bash
      if: ${{ github.repository == 'ydb-platform/nbs'}}
      run: |
        echo "https://api.github.com/orgs/${org}/teams/${team}/members?per_page=100&page=1"
        curl -s -L -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer $token" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             "https://api.github.com/orgs/${org}/teams/${team}/members?per_page=100&page=1"
        curl -s -L -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer $token" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             "https://api.github.com/orgs/${org}/teams/${team}/members?per_page=100&page=1" | jq -r .[].login | tee -a $LOGINS_FILE
      env:
        org: ${{ inputs.org }}
        team: ${{ inputs.team }}
        token: ${{ inputs.token }}
    - name: collect members
      shell: bash
      if: ${{ github.repository != 'ydb-platform/nbs' }}
      run: |
        echo "https://api.github.com/orgs/${org}/members?per_page=100&page=1"
        curl -s -L -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer $token" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             "https://api.github.com/orgs/${org}/members?per_page=100&page=1"
        curl -s -L -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer $token" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             "https://api.github.com/orgs/${org}/members?per_page=100&page=1" | jq -r .[].login | tee -a $LOGINS_FILE
      env:
        org: ${{ inputs.org }}
        team: ${{ inputs.team }}
        token: ${{ inputs.token }}
    - name: collect members public ssh keys
      shell: bash
      run: |
        cat $LOGINS_FILE | while read -r login; do
          curl  -s -L -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $token" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/users/${login}/keys | jq -r .[].key | while read -r key; do
                  echo $key $login;
                done;
        done | tee -a $KEYS_FILE
      env:
        token: ${{ inputs.token }}
    - name: add ssh keys to user authorized_keys file
      shell: bash
      run: |
        cat $KEYS_FILE >> /home/github/.ssh/authorized_keys

