{{- $namespace := .Release.Namespace -}}
{{- if .Values.prometheusConfig.enabled -}}
  {{- $name := default (printf "%s-additional-scrape-configs" (include "ydb-prometheus.fullname" .)) .Values.prometheusConfig.additionalScrapeConfigs.name -}}
  {{- $data := list -}}
  {{- $counters := .Values.ydb.counters -}}

  {{- range $cluster := .Values.ydb.clusters }}
    {{- if eq $cluster.type "external" }}
      {{- $jobs := include "ydb-prometheus.externalCluster.jobs" (tuple $cluster.storage $counters "static") | fromYamlArray -}}
      {{- $data = concat $data $jobs -}}
      {{- range $database := $cluster.databases -}}
        {{- $jobs := include "ydb-prometheus.externalCluster.jobs" (tuple $database $counters "dynamic") | fromYamlArray -}}
        {{- $data = concat $data $jobs -}}
      {{- end -}}
    {{- end }}
  {{- end }}

  {{- if $data -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name | trunc 63 | trimSuffix "-" }}
  namespace: {{ $namespace }}
  labels:
{{- include "ydb-prometheus.labels" $ | nindent 4 }}
data:
  {{ .Values.prometheusConfig.additionalScrapeConfigs.key }}: {{ $data | toYaml | b64enc | quote }}
  {{- end -}}
{{- end -}}