RECURSE(
    bad-guest
    build-fresh-blob
    chaos-monkey
    eternal_tests
    fake-conductor
    fake-nbs
    fake-vhost-server
    generate-agents
    infra-client
    loadtest
    nbd-test
    notify-mock
    pd-metadata-bench
    plugintest
    rdma-test
    fake-root-kms
    stable-plugin
    verify-test
)
