LIBRARY()

SRCS(
    astest.h
    defs.h
    dataset.cpp
    dataset.h
    helpers.cpp
    helpers.h
    helpers_impl.h
    http_client.cpp
    http_client.h
    prepare.cpp
    prepare.h
    setup.h
    test_bad_blobid.cpp
    test_bad_blobid.h
    test_brokendevice.cpp
    test_brokendevice.h
    test_dbstat.cpp
    test_dbstat.h
    test_defrag.cpp
    test_defrag.h
    test_faketablet.cpp
    test_faketablet.h
    test_gc.cpp
    test_gc.h
    test_huge.cpp
    test_huge.h
    test_load.cpp
    test_load.h
    test_localrecovery.cpp
    test_localrecovery.h
    test_many.cpp
    test_many.h
    test_outofspace.cpp
    test_outofspace.h
    test_repl.cpp
    test_repl.h
    test_simplebs.cpp
    test_simplebs.h
    test_synclog.cpp
    test_synclog.h
    vdisk_mock.cpp
    vdisk_mock.h
)

PEERDIR(
    contrib/ydb/library/actors/protos
    library/cpp/http/io
    library/cpp/openssl/io
    library/cpp/string_utils/url
    library/cpp/testing/unittest
    contrib/ydb/core/base
    contrib/ydb/core/blobstorage
    contrib/ydb/core/blobstorage/backpressure
    contrib/ydb/core/blobstorage/base
    contrib/ydb/core/blobstorage/crypto
    contrib/ydb/core/blobstorage/pdisk
    contrib/ydb/core/blobstorage/vdisk
    contrib/ydb/core/blobstorage/vdisk/common
    contrib/ydb/core/blobstorage/vdisk/huge
    contrib/ydb/core/blobstorage/vdisk/hulldb/base
    contrib/ydb/core/blobstorage/vdisk/repl
    contrib/ydb/core/blobstorage/vdisk/skeleton
    contrib/ydb/core/blobstorage/vdisk/synclog
    contrib/ydb/core/erasure
    contrib/ydb/library/pdisk_io
)

END()
