name: "PR Build & Test Matrix Plan"
description: "Decide which build/test workflows to run and compute CSV targets & matrix_include"

inputs:
  scheduling_type:
    description: "Scheduling type: on_demand, pooled, hybrid"
    required: true

outputs:
  matrix_include:
    description: "JSON for strategy.matrix (include)"
    value: ${{ steps.plan.outputs.matrix_include }}

runs:
  using: "composite"
  steps:
    - name: install dependencies
      shell: bash
      run: |
        pip install -r .github/scripts/requirements.txt
    - id: plan
      shell: bash
      run: |
        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/.github
        python3 -m scripts.pr_build_and_test_matrix_plan
      env:
          CONTAINS_BLOCKSTORE: ${{ contains(github.event.pull_request.labels.*.name, 'blockstore') && 'true' || 'false' }}
          CONTAINS_FILESTORE: ${{ contains(github.event.pull_request.labels.*.name, 'filestore') && 'true' || 'false' }}
          CONTAINS_DISK_MANAGER: ${{ contains(github.event.pull_request.labels.*.name, 'disk_manager') && 'true' || 'false' }}
          CONTAINS_TASKS: ${{ contains(github.event.pull_request.labels.*.name, 'tasks') && 'true' || 'false' }}
          CONTAINS_STORAGE: ${{ contains(github.event.pull_request.labels.*.name, 'storage') && 'true' || 'false' }}

          HAS_ASAN_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'asan') && 'true' || 'false' }}
          HAS_TSAN_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'tsan') && 'true' || 'false' }}
          HAS_MSAN_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'msan') && 'true' || 'false' }}
          HAS_UBSAN_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'ubsan') && 'true' || 'false' }}

          HAS_ON_DEMAND_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'on_demand') && 'true' || 'false' }}
          HAS_POOLED_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'pooled') && 'true' || 'false' }}
          HAS_HYBRID_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'hybrid') && 'true' || 'false' }}

          HAS_LARGE_TESTS_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'large-tests') && 'true' || 'false' }}

          SCHEDULING_TYPE: ${{ inputs.scheduling_type }}
