name: Set sleep_after_tests variable
description: Set up sleep after tests variable
inputs:
  sleep_after_tests:
    required: false
    default: '7200'
    description: default sleep_after_tests value
outputs:
  sleep_after_tests:
    value: ${{ steps.result.outputs.sleep_after_tests }}
    description: "sleep_after_tests"
runs:
  using: composite
  steps:
    - id: result
      name: set sleep_after_tests
      shell: bash
      run: |
        echo "sleep_after_tests=${{inputs.sleep_after_tests}}" >> $GITHUB_OUTPUT

