// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.0
// source: cloud/blockstore/public/api/protos/cms.proto

package protos

import (
	protos "github.com/ydb-platform/nbs/cloud/storage/core/protos"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TAction_EType int32

const (
	TAction_UNKNOWN             TAction_EType = 0
	TAction_REMOVE_DEVICE       TAction_EType = 1
	TAction_REMOVE_HOST         TAction_EType = 2
	TAction_GET_DEPENDENT_DISKS TAction_EType = 3
	TAction_ADD_DEVICE          TAction_EType = 4
	TAction_ADD_HOST            TAction_EType = 5
)

// Enum value maps for TAction_EType.
var (
	TAction_EType_name = map[int32]string{
		0: "UNKNOWN",
		1: "REMOVE_DEVICE",
		2: "REMOVE_HOST",
		3: "GET_DEPENDENT_DISKS",
		4: "ADD_DEVICE",
		5: "ADD_HOST",
	}
	TAction_EType_value = map[string]int32{
		"UNKNOWN":             0,
		"REMOVE_DEVICE":       1,
		"REMOVE_HOST":         2,
		"GET_DEPENDENT_DISKS": 3,
		"ADD_DEVICE":          4,
		"ADD_HOST":            5,
	}
)

func (x TAction_EType) Enum() *TAction_EType {
	p := new(TAction_EType)
	*p = x
	return p
}

func (x TAction_EType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TAction_EType) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_blockstore_public_api_protos_cms_proto_enumTypes[0].Descriptor()
}

func (TAction_EType) Type() protoreflect.EnumType {
	return &file_cloud_blockstore_public_api_protos_cms_proto_enumTypes[0]
}

func (x TAction_EType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TAction_EType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TAction_EType(num)
	return nil
}

// Deprecated: Use TAction_EType.Descriptor instead.
func (TAction_EType) EnumDescriptor() ([]byte, []int) {
	return file_cloud_blockstore_public_api_protos_cms_proto_rawDescGZIP(), []int{0, 0}
}

type TAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Action type.
	Type *TAction_EType `protobuf:"varint,1,opt,name=Type,enum=NCloud.NBlockStore.NProto.TAction_EType" json:"Type,omitempty"`
	// Host name.
	Host *string `protobuf:"bytes,2,opt,name=Host" json:"Host,omitempty"`
	// Device path.
	Device *string `protobuf:"bytes,3,opt,name=Device" json:"Device,omitempty"`
	// Flag to not apply changes.
	DryRun *bool `protobuf:"varint,4,opt,name=DryRun" json:"DryRun,omitempty"`
}

func (x *TAction) Reset() {
	*x = TAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_public_api_protos_cms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TAction) ProtoMessage() {}

func (x *TAction) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_public_api_protos_cms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TAction.ProtoReflect.Descriptor instead.
func (*TAction) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_public_api_protos_cms_proto_rawDescGZIP(), []int{0}
}

func (x *TAction) GetType() TAction_EType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return TAction_UNKNOWN
}

func (x *TAction) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

func (x *TAction) GetDevice() string {
	if x != nil && x.Device != nil {
		return *x.Device
	}
	return ""
}

func (x *TAction) GetDryRun() bool {
	if x != nil && x.DryRun != nil {
		return *x.DryRun
	}
	return false
}

type TActionResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Result.
	Result *protos.TError `protobuf:"bytes,1,opt,name=Result" json:"Result,omitempty"`
	// Timeout to retry if E_TRY_AGAIN returned (in seconds).
	Timeout *uint32 `protobuf:"varint,2,opt,name=Timeout" json:"Timeout,omitempty"`
	// Disks that depend on the supplied host.
	DependentDisks []string `protobuf:"bytes,3,rep,name=DependentDisks" json:"DependentDisks,omitempty"`
}

func (x *TActionResult) Reset() {
	*x = TActionResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_public_api_protos_cms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TActionResult) ProtoMessage() {}

func (x *TActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_public_api_protos_cms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TActionResult.ProtoReflect.Descriptor instead.
func (*TActionResult) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_public_api_protos_cms_proto_rawDescGZIP(), []int{1}
}

func (x *TActionResult) GetResult() *protos.TError {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TActionResult) GetTimeout() uint32 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

func (x *TActionResult) GetDependentDisks() []string {
	if x != nil {
		return x.DependentDisks
	}
	return nil
}

type TCmsActionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Optional request headers.
	Headers *THeaders `protobuf:"bytes,1,opt,name=Headers" json:"Headers,omitempty"`
	// List of actions to perform.
	Actions []*TAction `protobuf:"bytes,2,rep,name=Actions" json:"Actions,omitempty"`
}

func (x *TCmsActionRequest) Reset() {
	*x = TCmsActionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_public_api_protos_cms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TCmsActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCmsActionRequest) ProtoMessage() {}

func (x *TCmsActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_public_api_protos_cms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCmsActionRequest.ProtoReflect.Descriptor instead.
func (*TCmsActionRequest) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_public_api_protos_cms_proto_rawDescGZIP(), []int{2}
}

func (x *TCmsActionRequest) GetHeaders() *THeaders {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *TCmsActionRequest) GetActions() []*TAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type TCmsActionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Optional error, set only if error happened.
	Error *protos.TError `protobuf:"bytes,1,opt,name=Error" json:"Error,omitempty"`
	// Action result.
	ActionResults []*TActionResult `protobuf:"bytes,2,rep,name=ActionResults" json:"ActionResults,omitempty"`
}

func (x *TCmsActionResponse) Reset() {
	*x = TCmsActionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_public_api_protos_cms_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TCmsActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCmsActionResponse) ProtoMessage() {}

func (x *TCmsActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_public_api_protos_cms_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCmsActionResponse.ProtoReflect.Descriptor instead.
func (*TCmsActionResponse) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_public_api_protos_cms_proto_rawDescGZIP(), []int{3}
}

func (x *TCmsActionResponse) GetError() *protos.TError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *TCmsActionResponse) GetActionResults() []*TActionResult {
	if x != nil {
		return x.ActionResults
	}
	return nil
}

var File_cloud_blockstore_public_api_protos_cms_proto protoreflect.FileDescriptor

var file_cloud_blockstore_public_api_protos_cms_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19,
	0x4e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x2e, 0x4e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x30, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x25, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xfc, 0x01, 0x0a, 0x07, 0x54, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x4e,
	0x43, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x2e, 0x4e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x45, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x48, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x6f, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x72, 0x79, 0x52,
	0x75, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x44, 0x72, 0x79, 0x52, 0x75, 0x6e,
	0x22, 0x6f, 0x0a, 0x05, 0x45, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45,
	0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x45, 0x4d,
	0x4f, 0x56, 0x45, 0x5f, 0x48, 0x4f, 0x53, 0x54, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x47, 0x45,
	0x54, 0x5f, 0x44, 0x45, 0x50, 0x45, 0x4e, 0x44, 0x45, 0x4e, 0x54, 0x5f, 0x44, 0x49, 0x53, 0x4b,
	0x53, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x44, 0x44, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43,
	0x45, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x44, 0x44, 0x5f, 0x48, 0x4f, 0x53, 0x54, 0x10,
	0x05, 0x22, 0x80, 0x01, 0x0a, 0x0d, 0x54, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x2d, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x4e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x26, 0x0a, 0x0e,
	0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x6b, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x44,
	0x69, 0x73, 0x6b, 0x73, 0x22, 0x90, 0x01, 0x0a, 0x11, 0x54, 0x43, 0x6d, 0x73, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x07, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x4e, 0x43,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x2e, 0x4e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x52, 0x07, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x3c, 0x0a, 0x07, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x4e, 0x43, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x4e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e,
	0x4e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x91, 0x01, 0x0a, 0x12, 0x54, 0x43, 0x6d, 0x73,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b,
	0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x4e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x4e, 0x0a, 0x0d, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x4e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4e, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x4e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0d, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x42, 0x35, 0x5a, 0x33, 0x61,
	0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x72, 0x75, 0x2f,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73,
}

var (
	file_cloud_blockstore_public_api_protos_cms_proto_rawDescOnce sync.Once
	file_cloud_blockstore_public_api_protos_cms_proto_rawDescData = file_cloud_blockstore_public_api_protos_cms_proto_rawDesc
)

func file_cloud_blockstore_public_api_protos_cms_proto_rawDescGZIP() []byte {
	file_cloud_blockstore_public_api_protos_cms_proto_rawDescOnce.Do(func() {
		file_cloud_blockstore_public_api_protos_cms_proto_rawDescData = protoimpl.X.CompressGZIP(file_cloud_blockstore_public_api_protos_cms_proto_rawDescData)
	})
	return file_cloud_blockstore_public_api_protos_cms_proto_rawDescData
}

var file_cloud_blockstore_public_api_protos_cms_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cloud_blockstore_public_api_protos_cms_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cloud_blockstore_public_api_protos_cms_proto_goTypes = []interface{}{
	(TAction_EType)(0),         // 0: NCloud.NBlockStore.NProto.TAction.EType
	(*TAction)(nil),            // 1: NCloud.NBlockStore.NProto.TAction
	(*TActionResult)(nil),      // 2: NCloud.NBlockStore.NProto.TActionResult
	(*TCmsActionRequest)(nil),  // 3: NCloud.NBlockStore.NProto.TCmsActionRequest
	(*TCmsActionResponse)(nil), // 4: NCloud.NBlockStore.NProto.TCmsActionResponse
	(*protos.TError)(nil),      // 5: NCloud.NProto.TError
	(*THeaders)(nil),           // 6: NCloud.NBlockStore.NProto.THeaders
}
var file_cloud_blockstore_public_api_protos_cms_proto_depIdxs = []int32{
	0, // 0: NCloud.NBlockStore.NProto.TAction.Type:type_name -> NCloud.NBlockStore.NProto.TAction.EType
	5, // 1: NCloud.NBlockStore.NProto.TActionResult.Result:type_name -> NCloud.NProto.TError
	6, // 2: NCloud.NBlockStore.NProto.TCmsActionRequest.Headers:type_name -> NCloud.NBlockStore.NProto.THeaders
	1, // 3: NCloud.NBlockStore.NProto.TCmsActionRequest.Actions:type_name -> NCloud.NBlockStore.NProto.TAction
	5, // 4: NCloud.NBlockStore.NProto.TCmsActionResponse.Error:type_name -> NCloud.NProto.TError
	2, // 5: NCloud.NBlockStore.NProto.TCmsActionResponse.ActionResults:type_name -> NCloud.NBlockStore.NProto.TActionResult
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_cloud_blockstore_public_api_protos_cms_proto_init() }
func file_cloud_blockstore_public_api_protos_cms_proto_init() {
	if File_cloud_blockstore_public_api_protos_cms_proto != nil {
		return
	}
	file_cloud_blockstore_public_api_protos_headers_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cloud_blockstore_public_api_protos_cms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_public_api_protos_cms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TActionResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_public_api_protos_cms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TCmsActionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_public_api_protos_cms_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TCmsActionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cloud_blockstore_public_api_protos_cms_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_blockstore_public_api_protos_cms_proto_goTypes,
		DependencyIndexes: file_cloud_blockstore_public_api_protos_cms_proto_depIdxs,
		EnumInfos:         file_cloud_blockstore_public_api_protos_cms_proto_enumTypes,
		MessageInfos:      file_cloud_blockstore_public_api_protos_cms_proto_msgTypes,
	}.Build()
	File_cloud_blockstore_public_api_protos_cms_proto = out.File
	file_cloud_blockstore_public_api_protos_cms_proto_rawDesc = nil
	file_cloud_blockstore_public_api_protos_cms_proto_goTypes = nil
	file_cloud_blockstore_public_api_protos_cms_proto_depIdxs = nil
}
