// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.0
// source: cloud/blockstore/public/api/protos/local_ssd.proto

package protos

import (
	protos "github.com/ydb-platform/nbs/cloud/storage/core/protos"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EStoragePoolKind int32

const (
	// Named local pools.
	EStoragePoolKind_STORAGE_POOL_KIND_LOCAL EStoragePoolKind = 0
	// Default global pool without name.
	EStoragePoolKind_STORAGE_POOL_KIND_DEFAULT EStoragePoolKind = 1
	// Named global pools.
	EStoragePoolKind_STORAGE_POOL_KIND_GLOBAL EStoragePoolKind = 2
)

// Enum value maps for EStoragePoolKind.
var (
	EStoragePoolKind_name = map[int32]string{
		0: "STORAGE_POOL_KIND_LOCAL",
		1: "STORAGE_POOL_KIND_DEFAULT",
		2: "STORAGE_POOL_KIND_GLOBAL",
	}
	EStoragePoolKind_value = map[string]int32{
		"STORAGE_POOL_KIND_LOCAL":   0,
		"STORAGE_POOL_KIND_DEFAULT": 1,
		"STORAGE_POOL_KIND_GLOBAL":  2,
	}
)

func (x EStoragePoolKind) Enum() *EStoragePoolKind {
	p := new(EStoragePoolKind)
	*p = x
	return p
}

func (x EStoragePoolKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EStoragePoolKind) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_blockstore_public_api_protos_local_ssd_proto_enumTypes[0].Descriptor()
}

func (EStoragePoolKind) Type() protoreflect.EnumType {
	return &file_cloud_blockstore_public_api_protos_local_ssd_proto_enumTypes[0]
}

func (x EStoragePoolKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EStoragePoolKind.Descriptor instead.
func (EStoragePoolKind) EnumDescriptor() ([]byte, []int) {
	return file_cloud_blockstore_public_api_protos_local_ssd_proto_rawDescGZIP(), []int{0}
}

type TAvailableStorageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId string `protobuf:"bytes,1,opt,name=AgentId,proto3" json:"AgentId,omitempty"`
	// Size of single chunk (in bytes)
	ChunkSize  uint64 `protobuf:"varint,2,opt,name=ChunkSize,proto3" json:"ChunkSize,omitempty"`
	ChunkCount uint32 `protobuf:"varint,3,opt,name=ChunkCount,proto3" json:"ChunkCount,omitempty"`
}

func (x *TAvailableStorageInfo) Reset() {
	*x = TAvailableStorageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_public_api_protos_local_ssd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TAvailableStorageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TAvailableStorageInfo) ProtoMessage() {}

func (x *TAvailableStorageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_public_api_protos_local_ssd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TAvailableStorageInfo.ProtoReflect.Descriptor instead.
func (*TAvailableStorageInfo) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_public_api_protos_local_ssd_proto_rawDescGZIP(), []int{0}
}

func (x *TAvailableStorageInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TAvailableStorageInfo) GetChunkSize() uint64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *TAvailableStorageInfo) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

type TQueryAvailableStorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Headers *THeaders `protobuf:"bytes,1,opt,name=Headers,proto3" json:"Headers,omitempty"`
	// List of agent ids.
	AgentIds []string `protobuf:"bytes,2,rep,name=AgentIds,proto3" json:"AgentIds,omitempty"`
	// Storage pool name.
	StoragePoolName string `protobuf:"bytes,3,opt,name=StoragePoolName,proto3" json:"StoragePoolName,omitempty"`
	// Storage pool kind.
	StoragePoolKind EStoragePoolKind `protobuf:"varint,4,opt,name=StoragePoolKind,proto3,enum=NCloud.NBlockStore.NProto.EStoragePoolKind" json:"StoragePoolKind,omitempty"`
}

func (x *TQueryAvailableStorageRequest) Reset() {
	*x = TQueryAvailableStorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_public_api_protos_local_ssd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TQueryAvailableStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TQueryAvailableStorageRequest) ProtoMessage() {}

func (x *TQueryAvailableStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_public_api_protos_local_ssd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TQueryAvailableStorageRequest.ProtoReflect.Descriptor instead.
func (*TQueryAvailableStorageRequest) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_public_api_protos_local_ssd_proto_rawDescGZIP(), []int{1}
}

func (x *TQueryAvailableStorageRequest) GetHeaders() *THeaders {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *TQueryAvailableStorageRequest) GetAgentIds() []string {
	if x != nil {
		return x.AgentIds
	}
	return nil
}

func (x *TQueryAvailableStorageRequest) GetStoragePoolName() string {
	if x != nil {
		return x.StoragePoolName
	}
	return ""
}

func (x *TQueryAvailableStorageRequest) GetStoragePoolKind() EStoragePoolKind {
	if x != nil {
		return x.StoragePoolKind
	}
	return EStoragePoolKind_STORAGE_POOL_KIND_LOCAL
}

type TQueryAvailableStorageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error            *protos.TError           `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	AvailableStorage []*TAvailableStorageInfo `protobuf:"bytes,2,rep,name=AvailableStorage,proto3" json:"AvailableStorage,omitempty"`
}

func (x *TQueryAvailableStorageResponse) Reset() {
	*x = TQueryAvailableStorageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_blockstore_public_api_protos_local_ssd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TQueryAvailableStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TQueryAvailableStorageResponse) ProtoMessage() {}

func (x *TQueryAvailableStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_blockstore_public_api_protos_local_ssd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TQueryAvailableStorageResponse.ProtoReflect.Descriptor instead.
func (*TQueryAvailableStorageResponse) Descriptor() ([]byte, []int) {
	return file_cloud_blockstore_public_api_protos_local_ssd_proto_rawDescGZIP(), []int{2}
}

func (x *TQueryAvailableStorageResponse) GetError() *protos.TError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *TQueryAvailableStorageResponse) GetAvailableStorage() []*TAvailableStorageInfo {
	if x != nil {
		return x.AvailableStorage
	}
	return nil
}

var File_cloud_blockstore_public_api_protos_local_ssd_proto protoreflect.FileDescriptor

var file_cloud_blockstore_public_api_protos_local_ssd_proto_rawDesc = []byte{
	0x0a, 0x32, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x73, 0x73, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x4e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4e, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x4e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x30, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x25, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x15, 0x54, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x43,
	0x68, 0x75, 0x6e, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x43,
	0x68, 0x75, 0x6e, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xfb, 0x01, 0x0a, 0x1d, 0x54, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x07, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x4e,
	0x43, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x2e, 0x4e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x52, 0x07, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x55, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x4b,
	0x69, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x4e, 0x43, 0x6c, 0x6f,
	0x75, 0x64, 0x2e, 0x4e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x4e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50, 0x6f,
	0x6f, 0x6c, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x0f, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50,
	0x6f, 0x6f, 0x6c, 0x4b, 0x69, 0x6e, 0x64, 0x22, 0xab, 0x01, 0x0a, 0x1e, 0x54, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x4e, 0x43, 0x6c, 0x6f,
	0x75, 0x64, 0x2e, 0x4e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x5c, 0x0a, 0x10, 0x41, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x30, 0x2e, 0x4e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4e, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x4e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x10, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x2a, 0x6c, 0x0a, 0x10, 0x45, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x17, 0x53, 0x54, 0x4f,
	0x52, 0x41, 0x47, 0x45, 0x5f, 0x50, 0x4f, 0x4f, 0x4c, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x4c,
	0x4f, 0x43, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47,
	0x45, 0x5f, 0x50, 0x4f, 0x4f, 0x4c, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x44, 0x45, 0x46, 0x41,
	0x55, 0x4c, 0x54, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45,
	0x5f, 0x50, 0x4f, 0x4f, 0x4c, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x47, 0x4c, 0x4f, 0x42, 0x41,
	0x4c, 0x10, 0x02, 0x42, 0x35, 0x5a, 0x33, 0x61, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2d,
	0x74, 0x65, 0x61, 0x6d, 0x2e, 0x72, 0x75, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_cloud_blockstore_public_api_protos_local_ssd_proto_rawDescOnce sync.Once
	file_cloud_blockstore_public_api_protos_local_ssd_proto_rawDescData = file_cloud_blockstore_public_api_protos_local_ssd_proto_rawDesc
)

func file_cloud_blockstore_public_api_protos_local_ssd_proto_rawDescGZIP() []byte {
	file_cloud_blockstore_public_api_protos_local_ssd_proto_rawDescOnce.Do(func() {
		file_cloud_blockstore_public_api_protos_local_ssd_proto_rawDescData = protoimpl.X.CompressGZIP(file_cloud_blockstore_public_api_protos_local_ssd_proto_rawDescData)
	})
	return file_cloud_blockstore_public_api_protos_local_ssd_proto_rawDescData
}

var file_cloud_blockstore_public_api_protos_local_ssd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cloud_blockstore_public_api_protos_local_ssd_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cloud_blockstore_public_api_protos_local_ssd_proto_goTypes = []interface{}{
	(EStoragePoolKind)(0),                  // 0: NCloud.NBlockStore.NProto.EStoragePoolKind
	(*TAvailableStorageInfo)(nil),          // 1: NCloud.NBlockStore.NProto.TAvailableStorageInfo
	(*TQueryAvailableStorageRequest)(nil),  // 2: NCloud.NBlockStore.NProto.TQueryAvailableStorageRequest
	(*TQueryAvailableStorageResponse)(nil), // 3: NCloud.NBlockStore.NProto.TQueryAvailableStorageResponse
	(*THeaders)(nil),                       // 4: NCloud.NBlockStore.NProto.THeaders
	(*protos.TError)(nil),                  // 5: NCloud.NProto.TError
}
var file_cloud_blockstore_public_api_protos_local_ssd_proto_depIdxs = []int32{
	4, // 0: NCloud.NBlockStore.NProto.TQueryAvailableStorageRequest.Headers:type_name -> NCloud.NBlockStore.NProto.THeaders
	0, // 1: NCloud.NBlockStore.NProto.TQueryAvailableStorageRequest.StoragePoolKind:type_name -> NCloud.NBlockStore.NProto.EStoragePoolKind
	5, // 2: NCloud.NBlockStore.NProto.TQueryAvailableStorageResponse.Error:type_name -> NCloud.NProto.TError
	1, // 3: NCloud.NBlockStore.NProto.TQueryAvailableStorageResponse.AvailableStorage:type_name -> NCloud.NBlockStore.NProto.TAvailableStorageInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_cloud_blockstore_public_api_protos_local_ssd_proto_init() }
func file_cloud_blockstore_public_api_protos_local_ssd_proto_init() {
	if File_cloud_blockstore_public_api_protos_local_ssd_proto != nil {
		return
	}
	file_cloud_blockstore_public_api_protos_headers_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cloud_blockstore_public_api_protos_local_ssd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TAvailableStorageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_public_api_protos_local_ssd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TQueryAvailableStorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_blockstore_public_api_protos_local_ssd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TQueryAvailableStorageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cloud_blockstore_public_api_protos_local_ssd_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_blockstore_public_api_protos_local_ssd_proto_goTypes,
		DependencyIndexes: file_cloud_blockstore_public_api_protos_local_ssd_proto_depIdxs,
		EnumInfos:         file_cloud_blockstore_public_api_protos_local_ssd_proto_enumTypes,
		MessageInfos:      file_cloud_blockstore_public_api_protos_local_ssd_proto_msgTypes,
	}.Build()
	File_cloud_blockstore_public_api_protos_local_ssd_proto = out.File
	file_cloud_blockstore_public_api_protos_local_ssd_proto_rawDesc = nil
	file_cloud_blockstore_public_api_protos_local_ssd_proto_goTypes = nil
	file_cloud_blockstore_public_api_protos_local_ssd_proto_depIdxs = nil
}
