RECURSE_FOR_TESTS(
    acl-set-test
    mount-kikimr-test
    mount-local-test
    qemu-kikimr-multishard-test
    qemu-kikimr-multishard2-test
    qemu-kikimr-nemesis-test
    qemu-kikimr-test
    qemu-local-test
)
