name: configure s3cmd
description: configure s3cmd
inputs:
  s3_key_id:
    required: true
    description: "s3 key id"
  s3_key_secret:
    required: true
    description: "s3 key secret"
  s3_bucket:
    required: true
    description: "s3 bucket"
  s3_endpoint:
    required: true
    description: "s3 endpoint"
  s3_website_suffix:
    required: true
    description: "s3 website suffix"
  folder_prefix:
    required: true
    description: "folder prefix"
  build_preset:
    required: true
    description: "build preset like relwithdebinfo"
  user:
    required: false
    description: "github user"
  install:
    required: false
    default: true
    description: "install s3cmd and awscli"

runs:
  using: composite
  steps:
    - name: install s3cmd
      if: inputs.install == 'true'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends s3cmd awscli
    - name: configure s3cmd
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: |
        export S3CMD_CONFIG=$(sudo -E -H -u $user mktemp -p /home/$user)
        sudo chown $user: $S3CMD_CONFIG
        echo "S3CMD_CONFIG=$S3CMD_CONFIG" >> $GITHUB_ENV
        export GITHUB_WORKFLOW_NO_SPACES=${GITHUB_WORKFLOW// /-}
        cat <<EOF | sudo -E -H -u $user tee $S3CMD_CONFIG
        [default]
        access_key = ${s3_key_id}
        secret_key = ${s3_secret_access_key}
        bucket_location = eu-north1
        host_base = storage.ai.nebius.cloud
        host_bucket = %(bucket)s.storage.ai.nebius.cloud
        EOF

        sudo -E -H -u $user mkdir -p /home/$user/.aws/
        cat <<EOF | sudo -E -H -u $user tee /home/$user/.aws/credentials
        [default]
        aws_access_key_id = ${s3_key_id}
        aws_secret_access_key = ${s3_secret_access_key}
        EOF
        cat <<EOF | sudo -E -H -u $user tee /home/$user/.aws/config
        [default]
        region = eu-north1
        endpoint_url=https://storage.ai.nebius.cloud/
        s3 =
          max_concurrent_requests = 32
          multipart_chunksize = 32MB
          max_queue_size = 10240
        EOF

        sudo mkdir -p /root/.aws/
        cat <<EOF | sudo tee /root/.aws/credentials
        [default]
        aws_access_key_id = ${s3_key_id}
        aws_secret_access_key = ${s3_secret_access_key}
        EOF
        cat <<EOF | sudo tee /root/.aws/config
        [default]
        region = eu-north1
        endpoint_url=https://storage.ai.nebius.cloud/
        s3 =
          max_concurrent_requests = 32
          multipart_chunksize = 32MB
          max_queue_size = 10240
        EOF

        folder="${{ runner.arch == 'X64' && 'x86-64' || runner.arch == 'ARM64' && 'arm64' || 'unknown' }}"

        case "${{ inputs.build_preset }}" in
          relwithdebinfo|release)
            ;;
          debug)
            folder+="-debug"
            ;;
          release-asan)
            folder+="-asan"
            ;;
          release-tsan)
            folder+="-tsan"
            ;;
          release-msan)
            folder+="-msan"
            ;;
          release-ubsan)
            folder+="-ubsan"
            ;;
          *)
            echo "Invalid preset: ${{ inputs.build_preset }}"
            exit 1
            ;;
        esac

        echo "S3_BUCKET_PATH=s3://${{ inputs.s3_bucket }}/${{ github.repository }}/${GITHUB_WORKFLOW_NO_SPACES}/${{ github.run_id }}/${{ github.run_attempt || '1' }}/${{ inputs.folder_prefix }}${folder}" >> $GITHUB_ENV
        echo "S3_URL_PREFIX=${{ inputs.s3_endpoint }}/${{ inputs.s3_bucket }}/${{ github.repository }}/${GITHUB_WORKFLOW_NO_SPACES}/${{ github.run_id }}/${{ github.run_attempt || '1' }}/${{ inputs.folder_prefix }}${folder}" >> $GITHUB_ENV
        echo "S3_WEBSITE_PREFIX=https://${{ inputs.s3_bucket }}.${{ inputs.s3_website_suffix }}/${{ github.repository }}/${GITHUB_WORKFLOW_NO_SPACES}/${{ github.run_id }}/${{ github.run_attempt || '1' }}/${{ inputs.folder_prefix }}${folder}" >> $GITHUB_ENV
      env:
        s3_key_id: ${{ inputs.s3_key_id }}
        s3_secret_access_key: ${{ inputs.s3_key_secret }}
        user: ${{ inputs.user || 'github'}}
    - name: test s3cmd
      shell: bash
      run: sudo -E -H -u $user s3cmd ls
      env:
        user: ${{ inputs.user || 'github'}}
