name: Prepare VM for build (used only in act or on github runners)
description: Install required packages
runs:
  using: composite
  steps:
    - name: install build dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get -o Dpkg::Lock::Timeout=600 install -y --no-install-recommends git wget gnupg lsb-release curl xz-utils \
          tzdata python3-dev python3-pip antlr3 libidn11-dev file distcc strace qemu-kvm \
          qemu-utils dpkg-dev atop pigz pbzip2 xz-utils pixz gdb unzip
        sudo apt-get -o Dpkg::Lock::Timeout=600 remove -y unattended-upgrades
        # shellcheck disable=SC2102
        sudo pip3 install pytest pytest-timeout pytest-xdist setproctitle grpcio grpcio-tools \
             PyHamcrest tornado xmltodict pyarrow boto3 psutil PyGithub==2.5.0 pyinstaller \
             cryptography protobuf packaging six pyyaml rapidgzip pyOpenSSL typing-extensions nebius
    - name: add user github to kvm group if exists
      shell: bash
      run: |
        id -u github 2>/dev/null && {
        sudo usermod -a -G kvm github
        id github
        grep kvm /etc/group
        } || echo "user github not found"
