name: Prepare VM for build (used only in act)
description: Install required packages
runs:
  using: composite
  steps:
    - name: install build dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends git wget gnupg lsb-release curl xz-utils \
          tzdata python3-dev python3-pip antlr3 libidn11-dev file distcc strace qemu-kvm \
          qemu-utils dpkg-dev atop pigz pbzip2 xz-utils pixz gdb unzip
        sudo apt-get remove -y unattended-upgrades
        sudo pip install https://github.com/librarian/python-sdk/releases/download/v0.1.1/nebiusai-0.1.1-py3-none-any.whl
        # shellcheck disable=SC2102
        sudo pip3 install pytest pytest-timeout pytest-xdist setproctitle grpcio grpcio-tools \
             PyHamcrest tornado xmltodict pyarrow boto3 psutil yandexcloud==0.330.0 PyGithub==2.5.0 pyinstaller \
             cryptography packaging six pyyaml rapidgzip pyOpenSSL typing-extensions==4.10.0
    - name: add user github to kvm group if exists
      shell: bash
      run: |
        id -u github 2>/dev/null && {
        sudo usermod -a -G kvm github
        id github
        grep kvm /etc/group
        } || echo "user github not found"
