name: Create runner VM
description: Create runner VM using nebius-manage-vm.py
inputs:
  org:
    required: false
    description: "org name"
  team:
    required: false
    description: "team slug name"
  repo_owner:
    required: true
    description: "repo owner"
  repo:
    required: true
    description: "repo name"
  service_account_key:
    required: true
    description: "service account key"
  token:
    required: true
    description: "GITHUB_TOKEN"
  vm_parent_id:
    required: true
    description: "vm parent id"
  vm_name:
    required: true
    description: "vm name"
  vm_platform_id:
    required: true
    description: "vm platform id"
  vm_preset:
    required: true
    description: "vm cpu"
  vm_disk_type:
    required: true
    description: "vm disk type"
  vm_disk_size:
    required: true
    description: "vm disk size"
  vm_subnet:
    required: true
    description: "vm subnet"
  vm_image:
    required: true
    description: "vm image id"
  vm_labels:
    required: true
    description: "vm labels"
  vm_user_passwd:
    required: true
    description: "vm user password"
  vm_allow_downgrade:
    required: false
    description: "allow downgrade"

outputs:
  label:
    description: >-
      Name of the unique label assigned to the runner.
      The label is used in two cases:
      - to use as the input of 'runs-on' property for the following jobs;
      - to remove the runner from GitHub when it is not needed anymore.
    value: ${{ steps.create-vm.outputs.label }}
  instance-id:
    description: >-
      Instance id of the created runner.
      The id is used to terminate the instance when the runner is not needed anymore.
    value: ${{ steps.create-vm.outputs.instance-id }}
  local-ipv4:
    description: >-
      Local ipv4 address of the created runner.
      The address is used to connect to the runner via SSH.
    value: ${{ steps.create-vm.outputs.local-ipv4 }}
  external-ipv4:
    description: >-
      External ipv4 address of the created runner.
      The address is used to connect to the runner via SSH.
    value: ${{ steps.create-vm.outputs.external-ipv4 || '0.0.0.0' }}
  vm-preset:
    description: >-
      Resulting VM preset of the created runner.
    value: ${{ steps.create-vm.outputs.vm-preset || inputs.vm_preset }}



runs:
  using: composite
  steps:
    - name: write service account key to file
      shell: bash
      run: |
        export SERVICE_ACCOUNT_KEY=$(mktemp)
        echo "SERVICE_ACCOUNT_KEY=${SERVICE_ACCOUNT_KEY}" >> $GITHUB_ENV
        echo "${key_contents}" > $SERVICE_ACCOUNT_KEY
      env:
        key_contents: ${{ inputs.service_account_key }}
    - name: install dependencies
      shell: bash
      run: |
        pip install PyGithub==2.5.0 nebius==0.2.28
    - name: create vm
      id: create-vm
      shell: bash
      run: |
        python .github/scripts/nebius-manage-vm.py create ${ORG} ${TEAM} ${VM_ALLOW_DOWNGRADE} \
          --github-repo-owner "${REPO_OWNER}" \
          --github-repo "${REPO}" \
          --service-account-key "${SERVICE_ACCOUNT_KEY}" \
          --name "${VM_NAME}" \
          --parent-id "${VM_PARENT_ID}" \
          --platform-id "${VM_PLATFORM_ID}" \
          --preset "${VM_PRESET}" --disk-size "${VM_DISK_SIZE}" \
          --disk-type "${VM_DISK_TYPE}" \
          --subnet-id "${VM_SUBNET}" \
          --image-id "$VM_IMAGE" \
          --labels "$VM_LABELS" \
          --apply
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        ORG: ${{ inputs.org && format('--github-org {0}', inputs.org) || ''}}
        TEAM: ${{ inputs.team && format('--github-team-slug {0}', inputs.team) || ''}}
        REPO_OWNER: ${{ inputs.repo_owner }}
        REPO: ${{ inputs.repo }}
        VM_NAME: ${{ inputs.vm_name }}
        VM_PARENT_ID: ${{ inputs.vm_parent_id }}
        VM_PLATFORM_ID: ${{ inputs.vm_platform_id }}
        VM_PRESET: ${{ inputs.vm_preset }}
        VM_DISK_SIZE: ${{ inputs.vm_disk_size }}
        VM_DISK_TYPE: ${{ inputs.vm_disk_type }}
        VM_SUBNET: ${{ inputs.vm_subnet }}
        VM_IMAGE: ${{ inputs.vm_image }}
        VM_LABELS: ${{ inputs.vm_labels }}
        VM_USER_PASSWD: ${{ inputs.vm_user_passwd }}
        VM_ALLOW_DOWNGRADE: ${{ inputs.vm_allow_downgrade == 'yes' && '--allow-downgrade' || '' }}

    - name: save console output if we had any
      if: ${{ steps.create-vm.outputs.console-output }}
      uses: actions/upload-artifact@v4
      with:
        name: console-output-${{ inputs.vm_name }}
        path: ${{ steps.create-vm.outputs.console-output }}
