apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-blk
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 1Gi
  storageClassName: nbs-csi-sc
