{% include "trace_report/constants.js" %}
{% include "trace_report/state.js" %}
{% include "trace_report/format.js" %}
{% include "trace_report/test_phases.js" %}
{% include "trace_report/timeline.js" %}
{% include "trace_report/trace_index.js" %}
{% include "trace_report/filters.js" %}
{% include "trace_report/controls.js" %}
{% include "trace_report/rows.js" %}
{% include "trace_report/metadata.js" %}
{% include "trace_report/columns.js" %}
{% include "trace_report/bootstrap.js" %}
