// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.0
// source: cloud/filestore/config/http_proxy.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type THttpProxyConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port *uint32 `protobuf:"varint,1,opt,name=Port" json:"Port,omitempty"`
	// Use "localhost-expanded" special value to set this to `hostname --fqdn`
	NfsVhostHost *string `protobuf:"bytes,2,opt,name=NfsVhostHost" json:"NfsVhostHost,omitempty"`
	NfsVhostPort *uint32 `protobuf:"varint,3,opt,name=NfsVhostPort" json:"NfsVhostPort,omitempty"`
}

func (x *THttpProxyConfig) Reset() {
	*x = THttpProxyConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_filestore_config_http_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *THttpProxyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*THttpProxyConfig) ProtoMessage() {}

func (x *THttpProxyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_filestore_config_http_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use THttpProxyConfig.ProtoReflect.Descriptor instead.
func (*THttpProxyConfig) Descriptor() ([]byte, []int) {
	return file_cloud_filestore_config_http_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *THttpProxyConfig) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *THttpProxyConfig) GetNfsVhostHost() string {
	if x != nil && x.NfsVhostHost != nil {
		return *x.NfsVhostHost
	}
	return ""
}

func (x *THttpProxyConfig) GetNfsVhostPort() uint32 {
	if x != nil && x.NfsVhostPort != nil {
		return *x.NfsVhostPort
	}
	return 0
}

var File_cloud_filestore_config_http_proxy_proto protoreflect.FileDescriptor

var file_cloud_filestore_config_http_proxy_proto_rawDesc = []byte{
	0x0a, 0x27, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x4e, 0x43, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x4e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x4e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x10, 0x54, 0x48, 0x74, 0x74, 0x70, 0x50, 0x72, 0x6f, 0x78,
	0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x4e,
	0x66, 0x73, 0x56, 0x68, 0x6f, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x4e, 0x66, 0x73, 0x56, 0x68, 0x6f, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x12,
	0x22, 0x0a, 0x0c, 0x4e, 0x66, 0x73, 0x56, 0x68, 0x6f, 0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x4e, 0x66, 0x73, 0x56, 0x68, 0x6f, 0x73, 0x74, 0x50,
	0x6f, 0x72, 0x74, 0x42, 0x29, 0x5a, 0x27, 0x61, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2d,
	0x74, 0x65, 0x61, 0x6d, 0x2e, 0x72, 0x75, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
}

var (
	file_cloud_filestore_config_http_proxy_proto_rawDescOnce sync.Once
	file_cloud_filestore_config_http_proxy_proto_rawDescData = file_cloud_filestore_config_http_proxy_proto_rawDesc
)

func file_cloud_filestore_config_http_proxy_proto_rawDescGZIP() []byte {
	file_cloud_filestore_config_http_proxy_proto_rawDescOnce.Do(func() {
		file_cloud_filestore_config_http_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_cloud_filestore_config_http_proxy_proto_rawDescData)
	})
	return file_cloud_filestore_config_http_proxy_proto_rawDescData
}

var file_cloud_filestore_config_http_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cloud_filestore_config_http_proxy_proto_goTypes = []interface{}{
	(*THttpProxyConfig)(nil), // 0: NCloud.NFileStore.NProto.THttpProxyConfig
}
var file_cloud_filestore_config_http_proxy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cloud_filestore_config_http_proxy_proto_init() }
func file_cloud_filestore_config_http_proxy_proto_init() {
	if File_cloud_filestore_config_http_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cloud_filestore_config_http_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*THttpProxyConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cloud_filestore_config_http_proxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_filestore_config_http_proxy_proto_goTypes,
		DependencyIndexes: file_cloud_filestore_config_http_proxy_proto_depIdxs,
		MessageInfos:      file_cloud_filestore_config_http_proxy_proto_msgTypes,
	}.Build()
	File_cloud_filestore_config_http_proxy_proto = out.File
	file_cloud_filestore_config_http_proxy_proto_rawDesc = nil
	file_cloud_filestore_config_http_proxy_proto_goTypes = nil
	file_cloud_filestore_config_http_proxy_proto_depIdxs = nil
}
