name: Debug workflows using act and cmake

on:
  workflow_dispatch:
    inputs:
      build_preset:
        type: choice
        default: "relwithdebinfo"
        description: "Build preset"
        options:
          - debug
          - release
          - relwithdebinfo
  workflow_call:
    inputs:
      build_preset:
        type: string
        default: "release"
      nebius:
        type: string
        default: "no"
        description: "Run on new nebius runners"

jobs:
  checkout:
    name: Checkout ${{ inputs.build_preset }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR
      uses: actions/checkout@v4
      with:
        submodules: true
        ref: refs/heads/stable-23-3

    - name: Configure NCP
      uses: ./.github/actions/ncp
      with:
        runner_label: dp7329odurnhplpf5ff0
        sa_json: ${{ secrets.NEBIUS_GITHUB_USER_SA_JSON}}
    - name: add user github if not exists
      shell: bash
      run: |
        id -u github || sudo adduser github --gecos "" --disabled-password
    - name: Prepare VM
      uses: ./.github/actions/prepare
    - name: Prepare s3cmd
      uses: ./.github/actions/s3cmd
      with:
        s3_bucket: ${{ vars.AWS_BUCKET }}
        s3_endpoint: ${{ inputs.nebius == 'yes' && vars.NEBIUS_AWS_ENDPOINT || vars.AWS_ENDPOINT }}
        s3_website_suffix: ${{ inputs.nebius == 'yes' && vars.NEBIUS_AWS_WEBSITE_SUFFIX || vars.AWS_WEBSITE_SUFFIX }}
        s3_key_id: ${{ inputs.nebius == 'yes' && secrets.NEBIUS_AWS_ACCESS_KEY_ID || secrets.AWS_ACCESS_KEY_ID }}
        s3_key_secret: ${{ inputs.nebius == 'yes' && secrets.NEBIUS_AWS_SECRET_ACCESS_KEY || secrets.AWS_SECRET_ACCESS_KEY }}
        folder_prefix: nebius-
        build_preset: ${{ inputs.build_preset }}

    - name: Build
      uses: ./.github/actions/build_cmake
      with:
        build_preset: ${{ inputs.build_preset }}
        bazel_remote_uri: ${{ inputs.nebius == 'yes' && vars.NEBIUS_BAZEL_REMOTE_CACHE_URL || vars.REMOTE_CACHE_URL_YA }}
        bazel_remote_username: ${{ secrets.REMOTE_CACHE_USERNAME }}
        bazel_remote_password: ${{ secrets.REMOTE_CACHE_PASSWORD }}
      timeout-minutes: 1440

    - name: Run tests
      uses: ./.github/actions/test_cmake
      timeout-minutes: 1440


