name: Build and test NBS on demand

on:
  workflow_dispatch:
    inputs:
      build_target:
        type: string
        default: "cloud/tasks/"
        description: "limit build to specific target"
      test_target:
        type: string
        default: "cloud/tasks/"
        description: "limit test to specific target"
      build_preset:
        type: choice
        default: "relwithdebinfo"
        description: "Build preset"
        options:
          - debug
          - relwithdebinfo
          - release-asan
          - release-tsan
          - release-msan
          - release-ubsan
      cache_update:
        type: boolean
        default: false
        description: "Update build cache for build and cache"
      test_size:
        type: choice
        default: "small"
        description: "test size to run"
        options:
          - small
          - small,medium
          - small,medium,large
      test_type:
        type: choice
        default: "unittest"
        description: "type of tests to run"
        options:
          - unittest,clang_tidy,gtest
          - py3test,py2test,pytest,flake8,black,py2_flake8
          - go_test,gofmt
          - unittest,clang_tidy,gtest,py3test,py2test,pytest,flake8,black,py2_flake8,go_test,gofmt
      sleep_after_tests:
        type: string
        default: "0"
        description: "Amount of seconds to sleep after tests"
      run_build:
        type: boolean
        default: true
        description: "run build"
      run_tests:
        type: boolean
        default: true
        description: "run tests"
      nebius:
        description: "Run on new nebius runners"
        type: choice
        default: "no"
        options:
          - "yes"
          - "no"
  workflow_call:
    inputs:
      build_target:
        type: string
        default: "cloud/blockstore/apps/,cloud/filestore/apps/,cloud/disk_manager/,cloud/tasks/,cloud/storage/"
        description: "limit build to specific target"
      test_target:
        type: string
        default: "cloud/blockstore/,cloud/filestore/,cloud/disk_manager/,cloud/tasks/,cloud/storage/"
        description: "limit test to specific target"
      build_preset:
        type: string
        default: "relwithdebinfo"
      vm_name_suffix:
        type: string
        default: ""
      test_size:
        type: string
        default: "small,medium,large"
      test_type:
        type: string
        default: "unittest,clang_tidy,gtest,py3test,py2test,pytest,flake8,black,py2_flake8,go_test,gofmt"
      run_build:
        type: boolean
        default: true
      run_tests:
        type: boolean
        default: true
      sleep_after_tests:
        type: string
        default: "0"
        description: "Amount of seconds to sleep after tests"
      cache_update_build:
        type: boolean
        default: false
        description: "Update build cache in build stage"
      cache_update_tests:
        type: boolean
        default: false
        description: "Update build cache in test stage"
      link_threads:
        type: string
        default: "24"
        description: "--link-threads in ya make"
      test_threads:
        type: string
        default: "32"
        description: "--test-threads in ya test"
      upload_ya_dir:
        type: string
        default: "no"
        description: "Upload ya dir to s3"
      clean_ya_dir:
        type: string
        default: "no"
        description: "Clean ya dir from image before building"
      use_network_cache:
        type: string
        default: "yes"
        description: "Use network cache"
      disk_type:
        type: string
        default: "network-ssd-nonreplicated"
        description: "Disk type for VM"
      allow_downgrade:
        type: string
        default: "no"
        description: "Allow downgrade of VM"
      nebius:
        type: string
        default: "no"
        description: "Run on new nebius runners"

env:
  nebius: ${{ vars.GLOBAL_RUN_ON_NEBIUS == 'yes' || ((github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'nebius')) || inputs.nebius == 'yes') }}
  allow_downgrade: ${{ vars.GLOBAL_ALLOW_DOWNGRADE == 'yes' || ((github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'allow-downgrade')) || inputs.allow_downgrade == 'yes') }}

jobs:
  provide-runner:
    name: Start self-hosted runner (${{ inputs.build_preset }})
    timeout-minutes: 60
    if: always()
    runs-on: [ self-hosted, "self-hosted", "runner_heavy"]
    outputs:
      label: ${{ steps.get-runner.outputs.LABEL }}
      runner_flavor: ${{ steps.get-runner.outputs.RUNNER_FLAVOR }}
      instance-id: ${{ runner.name }}
      old-instance-name: ${{ steps.get-runner.outputs.OLD_INSTANCE_NAME }}
      runner_ipv4: ${{ steps.get-runner.outputs.EXTERNAL_IPV4 }}
      runner_local_ipv4: ${{ steps.get-runner.outputs.LOCAL_IPV4 }}
      build_threads: ${{ steps.calculate-threads.outputs.build_threads || '60' }}
      test_threads: ${{ steps.calculate-threads.outputs.test_threads || '32' }}
      link_threads: ${{ steps.calculate-threads.outputs.link_threads || '24' }}
      nebius: ${{ env.nebius == 'false' && 'no' || 'yes' }}
    steps:
      - name: checkout PR
        uses: actions/checkout@v4
        if: github.event.pull_request.head.sha != ''
        with:
          submodules: false
          sparse-checkout: '.github'
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ !contains(github.event.pull_request.labels.*.name, 'rebase') && 1 || 0 }}
      - name: rebase PR
        if: ${{ github.event.pull_request.head.sha != '' && contains(github.event.pull_request.labels.*.name, 'rebase') }}
        shell: bash
        run: |
          git config user.email "librarian@nebius.com"
          git config user.name "Rebase Robotovich"
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git rebase origin/${{ github.event.pull_request.base.ref }}
      - name: checkout
        uses: actions/checkout@v4
        if: github.event.pull_request.head.sha == ''
        with:
          submodules: false
          sparse-checkout: '.github'
      - name: set up home
        run: echo "HOME=/root" >> $GITHUB_ENV
  
      - name: set up path
        run: echo "PATH=$PATH:$HOME/nebius-cloud/bin:$HOME/.nebius/bin" >> $GITHUB_ENV
      - name: Set up Nebius CLI
        run: |
          set -x
          [ ! -f "$HOME/.nebius/bin/nebius" ] && {
            curl -sSL https://storage.eu-north1.nebius.cloud/cli/install.sh | bash
            cat <<EOF > sa.json
          ${sa_json}
          EOF
          } || echo "Nebius CLI already installed"
          [ ! -f "$HOME/.nebius/config.yaml" ] && {
            jq -r '."subject-credentials"."private-key"'  sa.json > private.pem
            echo "::add-mask::$(jq -r '."subject-credentials"."kid"' sa.json)"
            public_key_id=$(jq -r '."subject-credentials"."kid"' sa.json)
            echo "::add-mask::$(jq -r '."subject-credentials"."iss"' sa.json)"
            service_account_id=$(jq -r '."subject-credentials"."iss"' sa.json)
            echo "::add-mask::tenant-e00en3r863f7me6wtd"
            
            nebius profile create --endpoint api.eu-north1.nebius.cloud \
                                  --profile nbs-github-user-sa \
                                  --parent-id tenant-e00en3r863f7me6wtd \
                                  --public-key-id "${public_key_id}" \
                                  --private-key-file private.pem \
                                  --service-account-id "${service_account_id}"
            } || echo "Nebius profile already created"
        env:
          sa_json: ${{ secrets.NEW_NEBIUS_SA_JSON_CREDENTIALS }}
      - name: Update VM name and get runner settings
        id: get-runner
        run: |
          set -x
          nebius compute instance get --id $INSTANCE_ID --format json > instance.json
          OLD_INSTANCE_NAME=$(jq -r '.metadata.name' instance.json)
          LABEL=$(jq -r '.metadata.labels."runner-label"' instance.json)
          RUNNER_FLAVOR=$(jq -r '.metadata.labels."runner-flavor"' instance.json)
          EXTERNAL_IPV4=$(jq -r '.status.network_interfaces[0].ip_address.public_ip_address' instance.json | sed -e 's/\/32//g')
          LOCAL_IPV4=$(jq -r '.status.network_interfaces[0].ip_address.address' instance.json | sed -e 's/\/32//g')
          PRESET=$(jq -r '.spec.resources.preset' instance.json)
          DATE=$(date +%s);
          INSTANCE_NAME="running-${GITHUB_RUN_ID}-ydb-platform-nbs-${DATE}"
          nebius compute instance update --id $INSTANCE_ID --name $INSTANCE_NAME
          {
            echo LABEL=$LABEL;
            echo RUNNER_FLAVOR=$RUNNER_FLAVOR;
            echo INSTANCE_ID=$INSTANCE_ID;
            echo RUNNER_IPV4=$EXTERNAL_IPV4;
            echo RUNNER_LOCAL_IPV4=$LOCAL_IPV4;
            echo OLD_INSTANCE_NAME=$OLD_INSTANCE_NAME;
            echo VM_PRESET=$PRESET;
          } >> $GITHUB_OUTPUT
        env:
          INSTANCE_ID: ${{ runner.name }}


      - name: Calculate threads
        id: calculate-threads
        if: env.nebius == 'true' && always() || false
        uses: ./.github/actions/nebius_threads_calculator
        with:
          vm_preset: ${{ steps.get-runner.outputs.VM_PRESET }}
          tests_size: ${{ inputs.test_size }}

  build-and-test:
    name: Build and test NBS (${{ inputs.build_preset }}) [id=${{ needs.provide-runner.outputs.instance-id }} local_ip=${{ needs.provide-runner.outputs.runner_local_ipv4 }} ip=${{ needs.provide-runner.outputs.runner_ipv4 }}]
    uses: ./.github/workflows/build_and_test_ya.yaml
    needs:
      - provide-runner
    with:
      runner_kind: self-hosted
      runner_label: ${{ needs.provide-runner.outputs.label }}
      runner_flavor: ${{ needs.provide-runner.outputs.runner_flavor }}
      runner_instance_id: ${{ needs.provide-runner.outputs.instance-id }}
      runner_ipv4: ${{ needs.provide-runner.outputs.runner_ipv4 }}
      build_target: ${{ inputs.build_target }}
      test_target: ${{ inputs.test_target }}
      build_preset: ${{ inputs.build_preset }}
      run_build: ${{ inputs.run_build }}
      run_tests: ${{ inputs.run_tests }}
      test_size: ${{ inputs.test_size }}
      test_type: ${{ inputs.test_type }}
      build_threads: ${{ needs.provide-runner.outputs.build_threads || '60' }}
      link_threads: ${{ needs.provide-runner.outputs.link_threads || '24' }}
      test_threads: ${{ needs.provide-runner.outputs.test_threads || '12' }}
      sleep_after_tests: ${{ inputs.sleep_after_tests }}
      cache_update_build: ${{ fromJson(github.event_name == 'workflow_dispatch' && format('{0}', inputs.cache_update) || format('{0}', inputs.cache_update_build)) }}
      cache_update_tests: ${{ fromJson(github.event_name == 'workflow_dispatch' && format('{0}', inputs.cache_update) || format('{0}', inputs.cache_update_tests)) }}
      upload_ya_dir: ${{ github.event_name == 'workflow_dispatch' && 'no' || inputs.upload_ya_dir}}
      clean_ya_dir: ${{ github.event_name == 'workflow_dispatch' && 'no' || inputs.clean_ya_dir }}
      use_network_cache: ${{ github.event_name == 'workflow_dispatch' && 'yes'|| inputs.use_network_cache }}
      nebius: ${{ needs.provide-runner.outputs.nebius }}
      truncate_enabled: ${{ contains(github.event.pull_request.labels.*.name, 'disable_truncate') && 'no' || 'yes' }}
    secrets: inherit

  sleep-if-needed:
    name: Sleep ${{ needs.build-and-test.outputs.sleep_after_tests || '0' }}s if build failed
    if: ${{ !cancelled() }}
    needs:
      - provide-runner # required to get output from the start-runner job
      - build-and-test # required to wait when the main job is done
    runs-on: ubuntu-latest
    steps:
      - name: Sleep ${{ needs.build-and-test.outputs.sleep_after_tests  || '0' }}s if build failed
        shell: bash
        if: ${{ needs.build-and-test.outputs.sleep_after_tests && needs.build-and-test.outputs.sleep_after_tests != '0'  }}
        # we need to use binary because builting doesn't produce process
        # which we can kill to stop the vm before it's done
        run: |
          echo "sleeping ${{ needs.build-and-test.outputs.sleep_after_tests }}s"
          /usr/bin/sleep ${{ needs.build-and-test.outputs.sleep_after_tests }}

  release-runner:
    name: Release self-hosted runner (${{ inputs.build_preset }}) [id=${{ needs.provide-runner.outputs.instance-id }} local_ip=${{ needs.provide-runner.outputs.runner_local_ipv4 }} ip=${{ needs.provide-runner.outputs.runner_ipv4 }}]
    needs:
      - provide-runner  # required to get output from the start-runner job
      - build-and-test  # required to wait when the main job is done
      - sleep-if-needed # required to wait until all debug is done
    runs-on: [ self-hosted, "self-hosted", "runner_heavy", "${{ needs.provide-runner.outputs.label }}" ]
    if: always()
    steps:
      - name: checkout PR
        uses: actions/checkout@v4
        if: github.event.pull_request.head.sha != ''
        with:
          submodules: false
          sparse-checkout: '.github'
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ !contains(github.event.pull_request.labels.*.name, 'rebase') && 1 || 0 }}
      - name: rebase PR
        if: ${{ github.event.pull_request.head.sha != '' && contains(github.event.pull_request.labels.*.name, 'rebase') }}
        shell: bash
        run: |
          git config user.email "librarian@nebius.com"
          git config user.name "Rebase Robotovich"
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git rebase origin/${{ github.event.pull_request.base.ref }}
      - name: checkout
        uses: actions/checkout@v4
        if: github.event.pull_request.head.sha == ''
        with:
          submodules: false
          sparse-checkout: '.github'
      - name: Rename VM to old name
        id: rename
        run: |
          set -x
          nebius compute instance update --id $INSTANCE_ID --name $INSTANCE_NAME
        env:
          INSTANCE_ID: ${{ runner.name }}
          INSTANCE_NAME: ${{ needs.provide-runner.outputs.old-instance-name }}
