name: Hourly build
run-name: |
  ${{ github.event_name == 'schedule'
      && format('Hourly build (schedule)')
      || (
            inputs.comment != ''
            && format('Hourly build (manual) (comment: {0})', inputs.comment)
            || format('Hourly build (manual)')
          )
    }}
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Build target'
        type: string
        required: false
        default: 'cloud/tasks/'
        #default: 'cloud/blockstore/apps/,cloud/filestore/apps/,cloud/disk_manager/,cloud/tasks/,cloud/storage/'
      test_target:
        description: 'Test target'
        type: string
        required: false
        default: 'cloud/tasks/'
        #default: 'cloud/blockstore/,cloud/filestore/,cloud/disk_manager/,cloud/tasks/,cloud/storage/'
      comment:
        description: 'Comment'
        type: string
        required: false
        default: ""



jobs:
  build_dispatch:
    name: Build/test x86_64 using YA (relwithdebinfo) (dispatch)
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/build_and_test_on_demand.yaml
    secrets: inherit
    with:
      build_target: ${{ inputs.build_target }}
      test_target: ${{ inputs.test_target }}
      build_preset: relwithdebinfo
      cache_update_build: true
      cache_update_tests: true
      sleep_after_tests: 1
      number_of_retries: 1
  build_schedule:
    name: Build/test x86_64 using YA (relwithdebinfo) (schedule)
    if: github.event_name == 'schedule'
    uses: ./.github/workflows/build_and_test_on_demand.yaml
    secrets: inherit
    with:
      build_target: 'cloud/tasks/'
      test_target: 'cloud/tasks/'
      build_preset: relwithdebinfo
      cache_update_build: true
      cache_update_tests: true
      sleep_after_tests: 1
      number_of_retries: 1
