name: Nightly build
on:
  workflow_dispatch:

jobs:
  build:
    name: Build/test x86_64 using YA (relwithdebinfo)
    uses: ./.github/workflows/build_and_test_on_demand.yaml
    secrets: inherit
    with:
      build_target: "cloud/disk_manager/"
      test_target: "cloud/disk_manager/internal/pkg/dataplane/url/vmdk/tests/"
      build_preset: relwithdebinfo
      cache_update_build: true
      cache_update_tests: false
      test_threads: 6
      upload_ya_dir: true
