name: Populate VMs
on:
  workflow_dispatch:
    inputs:
      max_vms_to_create:
        description: 'Max VMs to create'
        type: number
        required: true
        default: 1
      vms_ttl:
        description: 'VMs TTL'
        type: number
        required: true
        default: 86400
      preset:
        description: 'VM preset'
        type: string
        required: true
        default: '32vcpu-128gb'
      disk_size:
        description: 'Disk size'
        type: number
        required: true
        default: 1023
      flavor:
        description: 'Runner flavor'
        type: choice
        options:
          - heavy
          - light
        required: true
        default: 'heavy'

jobs:
  calculate_missing_vms:
    name: Calculate missing VMs
    runs-on: ubuntu-latest
    outputs:
      running_vms: ${{ steps.list.outputs.RUNNING_VMS_COUNT }}
      vms_to_create: ${{ steps.list.outputs.VMS_TO_CREATE }}
      vms_to_remove: ${{ steps.list.outputs.VMS_TO_REMOVE }}
      date: ${{ steps.list.outputs.DATE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: '.github'
      - name: set up path
        run: echo "PATH=$PATH:$HOME/nebius-cloud/bin:$HOME/.nebius/bin" >> $GITHUB_ENV

      - name: set up cli
        id: get-runner
        uses: ./.github/actions/nebius_cli
        with:
          sa_json: ${{ secrets.NEW_NEBIUS_SA_JSON_CREDENTIALS }}
          
      - name: List VMs and prepare removal (vms older than 24h) and creation lists
        id: list
        run: |
          nebius compute instance list --parent-id ${PARENT_ID} --format json |  jq --arg owner ${OWNER} --arg repo ${REPO} --arg flavor ${FLAVOR} -r '
            .items[] |
            select(.metadata.labels.repo == $repo) |
            select(.metadata.labels.owner == $owner) |
            select(.metadata.labels.idle == "true") |
            select(.status.state == "RUNNING") |
            select(.metadata.labels."runner-flavor" == $flavor) |
          "\(.metadata.created_at) \(.metadata.id) \(.metadata.name) \(.status.state) \(.metadata.labels."runner-label") \((.metadata.labels | to_entries | map("\(.key)=\(.value)") | join(",")))"' > instances.list || touch instances.list

          RUNNING_VMS_COUNT=$(wc -l instances.list | awk '{print $1}')
          VMS_TO_REMOVE='[]'
          echo $VMS_TO_REMOVE > vms_to_remove.json
          echo 0 > vms_count_to_remove
          VMS_COUNT_TO_REMOVE=0
          DATE=$(date +%s);
          while read vm_creation_date vm_id vm_name vm_state vm_runner_label vm_labels; do
            echo "Checking $vm_id"
            vm_creation_date_ts=$(date -u -d "$vm_creation_date" +%s)
            echo "VM $vm_id created at $vm_creation_date ($vm_creation_date_ts)"
            echo "VM $vm_id is $((DATE - vm_creation_date_ts)) seconds old"
            if [ $((DATE - vm_creation_date_ts)) -gt $VMS_OLDER_THAN ]; then
              echo "VM $vm_id is older than $VMS_OLDER_THAN seconds"
              VMS_TO_REMOVE=$(echo $VMS_TO_REMOVE | jq --arg vm_id $vm_id '. + [$vm_id]')
              VMS_COUNT_TO_REMOVE=$(($VMS_COUNT_TO_REMOVE + 1))
              echo $VMS_TO_REMOVE > vms_to_remove.json
            fi
          done < instances.list
          echo "VMS_TO_REMOVE=$(cat vms_to_remove.json)"
          echo "VMS_COUNT_TO_REMOVE=$VMS_COUNT_TO_REMOVE"
          echo "MAX_VMS_TO_CREATE=$MAX_VMS_TO_CREATE"
          echo "RUNNING_VMS_COUNT=$RUNNING_VMS_COUNT"
          NUMBER_VMS_TO_CREATE=$((MAX_VMS_TO_CREATE - RUNNING_VMS_COUNT + VMS_COUNT_TO_REMOVE))
          echo "NUMBER_VMS_TO_CREATE=$NUMBER_VMS_TO_CREATE"
          if [ $NUMBER_VMS_TO_CREATE -le 0 ]; then
            echo "No VMs to create";
            echo "[]" > vms_to_create.json;
          else
            for i in $(seq 1 $NUMBER_VMS_TO_CREATE); do
              echo "${FLAVOR}-${GITHUB_REPOSITORY_OWNER}-${{ github.event.repository.name }}-$i";
            done | jq -R -s 'split("\n") | map(select(. != ""))' > vms_to_create.json
          fi
          {
            echo RUNNING_VMS_COUNT=$RUNNING_VMS_COUNT;
            echo VMS_TO_CREATE=$(cat vms_to_create.json);
            echo VMS_TO_REMOVE=$(cat vms_to_remove.json);
            echo DATE=$DATE;
          } | tee -a $GITHUB_OUTPUT
        env:
          PARENT_ID: ${{ vars.NEBIUS_PARENT_ID }}
          MAX_VMS_TO_CREATE: ${{ github.event.inputs.max_vms_to_create }}
          FLAVOR: ${{ github.event.inputs.flavor }}
          VMS_OLDER_THAN: ${{ github.event.inputs.vms_ttl }}
  remove_vms:
    needs: calculate_missing_vms
    name: Remove VMs
    if: needs.calculate_missing_vms.outputs.vms_to_remove != '[]'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        vms_to_remove: ${{ fromJson(needs.calculate_missing_vms.outputs.vms_to_remove) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: '.github'
      - name: Remove VM ${{ matrix.vms_to_remove }}
        id: remove-runner-nebius
        uses: ./.github/actions/nebius_runner_remove
        timeout-minutes: 60
        with:
          service_account_key: ${{ secrets.NEW_NEBIUS_SA_JSON_CREDENTIALS }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          repo_owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          vm_parent_id: ${{ vars.NEBIUS_PARENT_ID }}
          vm_id: ${{ matrix.vms_to_remove }}
  populate_vms:
    needs: calculate_missing_vms
    name: Populate VMs
    if: needs.calculate_missing_vms.outputs.vms_to_create != '[]'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        vms_to_create: ${{ fromJson(needs.calculate_missing_vms.outputs.vms_to_create) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: '.github'
      - name: Create VM ${{ matrix.vms_to_create }}
        id: start-runner-nebius
        uses: ./.github/actions/nebius_runner_create
        timeout-minutes: 60
        with:
          org: ydb-platform
          team: nbs
          repo_owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          service_account_key: ${{ secrets.NEW_NEBIUS_SA_JSON_CREDENTIALS }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          vm_parent_id: ${{ vars.NEBIUS_PARENT_ID }}
          vm_name: ${{ matrix.vms_to_create }}
          vm_platform_id: ${{ vars.NEBIUS_PLATFORM_ID }}
          vm_preset: ${{ github.event.inputs.preset }}
          vm_disk_type: 'network-ssd-nonreplicated'
          vm_disk_size: ${{ github.event.inputs.disk_size }}
          vm_subnet: ${{ vars.NEBIUS_SUBNET_ID }}
          vm_image: ${{ vars.NEBIUS_IMAGE_ID_2204 }}
          vm_labels: ${{ format('run={0}-{1},repo={2},owner={3},idle=true', github.run_id, github.run_attempt, github.event.repository.name, github.repository_owner) }}
          vm_flavor: ${{ inputs.flavor }}
          vm_user_passwd: ${{ secrets.VM_USER_PASSWD }}
          vm_allow_downgrade: 'no'
    
    