name: Scheduled maintaning of VMs count
run-name: ${{ format('Scheduled maintaning of VMs count (schedule)') }}
      
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

concurrency:
  group: 'populate-vms-schedule'
  cancel-in-progress: true
  
jobs:
  light:
    name: Populate light VMs
    uses: ./.github/workflows/populate.yaml
    secrets: inherit
    with:
      max_vms_to_create: 1
      vms_ttl: 3600
      flavor: light
  heavy:
    name: Populate heavy VMs
    uses: ./.github/workflows/populate.yaml
    secrets: inherit
    with:
      max_vms_to_create: 1
      vms_ttl: 3600
      flavor: heavy
