name: pre-commit

on:
  pull_request_target:
    branches:
      - 'main'
    paths-ignore:
      - 'ydb/docs/**'
      - '.github/**'
      - '!.github/config/**'
      - '!.github/workflows/pre-commit.yaml'
      - 'example/**'
      - 'doc/**'
      - '**.md'
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
      - 'labeled'

concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number }}-${{
      (
        github.event.action != 'labeled' ||
        contains(
          fromJSON(vars.LABELS_ALLOWED_TO_TRIGGER_PR_CHECKS || '[]'),
          github.event.label.name
        )
      ) && 'pre-commit' || 'ignored'
    }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  GIT_CONFIG_COUNT: "1"
  GIT_CONFIG_KEY_0: http.version
  GIT_CONFIG_VALUE_0: HTTP/1.1

jobs:
  check-running-allowed:
    if: >-
      ${{
        (
          github.event.action != 'labeled' ||
          contains(
            fromJSON(vars.LABELS_ALLOWED_TO_TRIGGER_PR_CHECKS || '[]'),
            github.event.label.name
          )
        ) &&
        (
          (github.event.action == 'labeled' && github.event.label.name == 'recheck') ||
          github.event.pull_request.stack == null ||
          github.event.pull_request.stack.base.ref == github.event.pull_request.base.ref
        )
      }}
    runs-on: [ self-hosted, "self-hosted", "runner_light" ]
    outputs:
      result: ${{ steps.check-ownership-membership.outputs.result }}
    steps:
    - name: checkout workflow scripts
      uses: actions/checkout@v7
      with:
        submodules: false
        sparse-checkout: '.github'
        clean: true
        ref: ${{ github.event.pull_request.base.sha }}
    - name: Check if running pre-commit is allowed
      id: check-ownership-membership
      uses: actions/github-script@v9
      with:
        github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        script: |
          const checkOwnershipMembership = require('./.github/scripts/check-ownership-membership.js');
          return await checkOwnershipMembership({ github, context, core });

  pre-commit:
    needs:
      - check-running-allowed
    if: needs.check-running-allowed.outputs.result == 'true'
    runs-on: [ self-hosted, "self-hosted", "runner_light" ]
    steps:
    - uses: actions/checkout@v7
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
        clean: true
    - uses: actions/setup-python@v7.0.0
      with:
        python-version: "3.10"
    - uses: ./.github/actions/pre_commit
      with:
        extra_args: --from "origin/main" --to "HEAD" --show-diff-on-failure
