name: Remove runner
run-name: Remove runner
on:
  workflow_dispatch:
    inputs:
      id:
        description: 'VM ID'
        type: string
        required: true
        default: ''

concurrency:
  group: 'remove-runner-${{ inputs.id }}'
  


jobs:
  remove_vms:
    name: Remove VM
    runs-on: [ self-hosted, "self-hosted", "runner_light" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: '.github'
      - name: Remove VM ${{ inputs.id }}
        id: remove-runner
        uses: ./.github/actions/nebius_runner_remove
        timeout-minutes: 60
        with:
          service_account_key: ${{ secrets.NEW_NEBIUS_SA_JSON_CREDENTIALS }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          repo_owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          vm_parent_id: ${{ vars.NEBIUS_PARENT_ID }}
          vm_id: ${{ inputs.id }}

    