name: Build VS Code yatool extension

on:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  check-running-allowed:
    runs-on: [self-hosted, "self-hosted", "runner_light"]
    outputs:
      result: ${{ steps.allow-local.outputs.result || steps.check-ownership-membership.outputs.result }}
    steps:
      - name: Allow local act run
        if: ${{ env.ACT == 'true' }}
        id: allow-local
        run: echo "result=true" >> "$GITHUB_OUTPUT"

      - name: checkout workflow scripts
        if: ${{ env.ACT != 'true' }}
        uses: actions/checkout@v7
        with:
          submodules: false
          sparse-checkout: ".github"
          clean: true
          ref: ${{ github.event.repository.default_branch }}

      - name: disable sparse checkout (workaround for actions/checkout/issues/2249)
        if: ${{ env.ACT != 'true' }}
        run: git config core.sparseCheckout false
        continue-on-error: true

      - name: Check if running extension build is allowed
        if: ${{ env.ACT != 'true' }}
        id: check-ownership-membership
        uses: actions/github-script@v9
        with:
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          script: |
            const checkOwnershipMembership = require('./.github/scripts/check-ownership-membership.js');
            return await checkOwnershipMembership({ github, context, core });

  package:
    needs:
      - check-running-allowed
    if: needs.check-running-allowed.outputs.result == 'true'
    runs-on: [self-hosted, "self-hosted", "runner_light"]

    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          submodules: false
          sparse-checkout: |
            .github/vscode-yatool-extension
          clean: true

      - name: disable sparse checkout (workaround for actions/checkout/issues/2249)
        if: ${{ always() }}
        run: git config core.sparseCheckout false
        continue-on-error: true

      - name: setup node
        uses: actions/setup-node@v6.3.0
        with:
          node-version: "22"

      - name: install packager
        working-directory: .github/vscode-yatool-extension
        run: npm install --no-save --no-package-lock @vscode/vsce

      - name: check extension syntax
        working-directory: .github/vscode-yatool-extension
        run: npm run check

      - name: run extension tests
        working-directory: .github/vscode-yatool-extension
        run: npm test

      - name: package extension
        working-directory: .github/vscode-yatool-extension
        run: npm run package

      - name: upload vsix
        uses: actions/upload-artifact@v7.0.1
        with:
          name: vscode-yatool-extension
          path: .github/vscode-yatool-extension/vscode-yatool-extension.vsix
          if-no-files-found: error
